### ISSUE TITLE
Propuesta de guia para convención de commits de departamento

### ISSUE THREAD

**Issue by albertcastaned** [Solify-IT/docs#10]
## Objetivo
* Definir una forma estandarizada de hacer commits dentro del departamento para tener mayor claridad de los cambios realizados al código fuente.

## Commits convencionales

Para los proyectos dentro de Solify se utilizará el estándar de Commits Convencionales 1.0.0 debido a sus especificaciones ligeras, legibles, y por su encaje con la convencion de [Versionamiento Semantico](https://semver.org/). Además, la sintaxis de los commits convencionales nos da la oportunidad de generar Changelogs de forma automatizada.

### Formatos de un commit convencional:
```
<tipo>[ámbito opcional]: <descripción>

[cuerpo opcional]

[nota de pie opcional]
```

### Tipos de elementos estructurales

| Tipo | Descripción |
| -------- | -------- |
| fix     | Solución de un error     |
| feat     | Implementación de nueva funcionalidad     |
| BREAKING CHANGE:     | Un cambio drástico que rompe la compatibilidad en el uso de la API (si aplica)     |
| chore     | Cambios relacionados con la configuración del sistema o de CI     |
| docs     | Cambios solamente de documentación     |
| refactor     | Cambio de código que no arregla un bug ni agrega nueva funcionalidad      |
| test     | Cambios relacionados con pruebas sea agregar nuevas o modificar existentes      |
| style     | Cambios estéticos de código o de interfaz gráfica      |
| perf     | Cambio que mejora el rendimiento del sistema     |

### Idioma
El idioma de los mensajes de los commits deberá ser seleccionado por cada equipo, pero debe mantenerse consistente durante el transcurso del proyecto. Lo recomendado es utilizar el inglés para no preocuparse de errores ortográficos y que los mensajes sean más cortos.

### Ejemplos
* `feat: add login functionality`
* `feat(users):  create user profile management` 
* `fix: wrong data being returned`
* `chore(backend): update dependencies`

### Más información
Si desea conocer más sobre Commits Convencionales, podrá hacerlo en la siguiente liga: 

[Commits Convencionales 1.0.0](https://www.conventionalcommits.org/es/v1.0.0-beta.3/) 

## Squash commits
Para facilitar la navegación del historial de commits, se recomienda utilizar Squash Commits al momento de hacer pull requests.

"Squash" en Git se refiere a combinar varios commits en uno solo. De esta forma, al integrar una rama a otra se puede evitar pasar un posible historial largo de commits de una rama a otra.

![](https://i.imgur.com/TgqynuJ.png)

## Commits convencionales e integración continua
Para mantener la integridad y la consistencia dentro de los repositorios del departamento, se deberá tener un proceso de verificación para comprobar que se está siguiendo la convención establecido por el departamento. Se recomienda tener una herramienta de integración continua que valide la convención de los commits o del pull request al momento de querer integrar a la línea base.

## Referencias
1. [Commits Convencionales](https://www.conventionalcommits.org/es/v1.0.0-beta.3/)
1. [Versionamiento Semantico](https://semver.org/)

**Comment by Topi99** [comment]
Me gusta. Tal vez solo faltaría poner algún ejemplo de commit semántico.

**Comment by AdrizPaola** [comment]
Coincido con Topii en que faltaría un ejemplo, y talvez en no solo integrar el formato como tal sino poner un ejemplo realista para que les resulte más fácil a quiénes lo ven por primera vez. Fuera de eso, súper bien!

**Comment by albertcastaned** [comment]
Agregue algunos ejemplos :) si pueden checarlo de nuevo por favor y si lo ven bien pueden reaccionar a este comentario para pasar a subirlo.
