### ISSUE TITLE
Propuesta para G08 Propuestas de mejora continua

### ISSUE THREAD

**Issue by LaloGMelgoza** [Solify-IT/docs#13]
## Descripción
Esta guía existe con el propósito de establecer lineamientos a seguir para proponer mejoras a la forma de trabajo. Puede referirse a esta guía para mejora de:
- Procesos
- Políticas
- Guías
- Estándares

## Objetivos
  1. Mejorar continuamente la forma en que se llevan acabo las actividades del departamento

## Involucrados
  1. Dueño de la propuesta
  2. SEPG
  3. Quality Owners

## Entradas
  1. Issue de propuesta

## Pasos
  1. Como dueño de propuesta, abrir un issue en [pestaña de Issues](https://github.com/Solify-IT/docs/issues) en GitHub
  2. Si la propuesta involucra actualización de [Wiki](https://github.com/Solify-IT/docs/wiki), redactar propuesta en formato de markdown; sino, el formato es libre
  3. En el issue, mencionar a las personas involucradas para revisión
  4. Esperar comentarios o aprobación de personas encargadas de la revisión
  5. Si existen propuestas de cambios, hacer los correspondientes y solicitar revisión de nuevo hasta obtener aprobación final
  6. Como Quality Owners, verificar e integrar a Wiki, cerrar issue

**Comment by albertcastaned** [comment]
👍
