### ISSUE TITLE
Propuesta para crear un Pull Request

### ISSUE THREAD

**Issue by Topi99** [Solify-IT/docs#14]
# P12: Proceso para crear un Pull Request

## Objetivos

  1. Crear una solicitud de incorporación de código entendible por humanos y máquinas. 

## Involucrados
  1. Todo el equipo de desarrollo

## Entradas

  1. Cambios en el código
  2. Necesidad de revisión de código. 

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Practica del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan=6>Creación del PR</td>
      <td>
        Asigna un nombre al PR, siguiendo el siguiente formato
        `<feat|fix|cualquier prefijo aceptado por <a href="https://www.conventionalcommits.org/en/v1.0.0/">CC<a>>/<jira ticket ID>/<nombre del cambio>`. Este formato permite tener un versionamiento semántico. 
      </td>
      <td rowspan=8>Desarrollador asignado del cambio</td>
      <td>VER1.1, CM2.1</td>
    </tr>
    <tr>
      <td>Llenar todos los campos (o los que apliquen) de la descripción del PR, para así dar más información a los reviewers del cambio.</td>
      <td>VER1.1, CM2.1</td>
    </tr>
    <tr>
      <td>Asignar al encargado del PR (o a si mismo si es que aplica).</td>
      <td>VER2.1, CM2.1</td>
    </tr>
    <tr>
      <td>Seleccionar encargados de la revisión (reviewers), o dejar que Github asigne automáticamente.</td>
      <td>VER2.1, CM2.1</td>
    </tr>
    <tr>
      <td>Seleccionar el tab "state:ready-for-review".</td>
      <td>VER2.1, CM2.1</td>
    </tr>
    <tr>
      <td>En la descripción del PR, añada preguntas para sus reviewers. También, si aplica, personalice los elementos del checklist al final de la descripción.</td>
      <td>VER1.3, CM2.1</td>
    </tr>
    <tr>
      <td rowspan=2>Creación de entorno de prueba</td>
      <td>Decidir si se necesita un entorno de prueba en la nube o solamente descargar la rama con los cambios y probar localmente. Si se necesita un entorno en la nube, en el pipeline actual de Heroku crear dos nuevas aplicaciones: una para backend y otra para frontend. Apoyarse de su dueño de arquitectura para tener la configuración adecuada o siga el <a href="#">proceso para crear un entorno de verificación</a> (pendiente).</td>
      <td>VER1.2, CM2.1</td>
    </tr>
    <tr>
      <td>Notificar en el medio de comunicación adecuado que se ha creado un nuevo PR y que está listo para revisión. Así mismo, notificar si es necesario o no el entorno de pruebas en la nube.</td>
      <td>VER2.1, CM2.1</td>
    </tr>

  </tbody>
</table>

## Salidas

  1. Pull Request completo
  2. Entorno de pruebas (ya sea en la nube o local). 

## Referencias
[Conventional Commits V1.0.0 (CC)][1]

[1]: https://www.conventionalcommits.org/en/v1.0.0/

**Comment by Topi99** [comment]
@Solify-IT/wiki-owners

**Comment by albertcastaned** [comment]
## Checklist
- [x] El título del proceso tiene un identificador único y un nombre como verbo en infinitivo. (Ejemplo: Mejorar, Conducir, Crear)
- [x] El proceso cubre los apartados que contiene la [plantilla de procesos](https://github.com/Solify-IT/docs/wiki/P00---Plantilla-para-procesos)
- [ ] Las prácticas de CMMI incluidas en las etapas del proceso están completas y correctas

La sub practica SG2.1 "Seguir las peticiones de cambio" creo que aplica en todo el proceso. 

- [ ] El proceso no tiene faltas ortográficas o errores gramaticales.

La etapa 2.1 tiene algunos detalles (nuebas y baclend)
- [x] La sintaxis de markdown funciona.


## Notas
Lo veo muy bien. Solo me quedo duda con la etapa 1.1 el formato de los títulos de PR. ¿Se seguira la [guia de commits](https://github.com/Solify-IT/docs/wiki/G7-Gu%C3%ADa-de-convenci%C3%B3n-de-commits) o seria otro formato? Podría servir un ejemplo.

**Comment by Topi99** [comment]
> Lo veo muy bien. Solo me quedo duda con la etapa 1.1 el formato de los títulos de PR. ¿Se seguira la guia de commits o seria otro formato? Podría servir un ejemplo.

Sí, se sigue el mismo formato.

**Comment by Topi99** [comment]
> La sub practica SG2.1 "Seguir las peticiones de cambio" creo que aplica en todo el proceso.

¿Es VER2.1?

**Comment by Topi99** [comment]
Ya está arreglado, solo me queda duda sobre si es `VER2.1` o `SG2.1`.

**Comment by albertcastaned** [comment]
Perdon, me referia a la práctica SG2.1 del CMMI. Sería CM2.1.

@Topi99

**Comment by Topi99** [comment]
Ahh vale, vale, ahorita lo cambio.

**Comment by albertcastaned** [comment]
👍

**Comment by AdrizPaola** [comment]
Está súper bien!! :D
