### ISSUE TITLE
Propuesta - Proceso para Revisión de Pull Requests

### ISSUE THREAD

**Issue by Topi99** [Solify-IT/docs#15]
# P13: Revisar de Pull Request

## Objetivos

  1. Verificar y validar los cambios del Pull Request (PR).

## Involucrados
  1. Revisores del PR (miembros del equipo).
  2. Dueño del PR.

## Entradas

  1. Un PR listo para revisión. 

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Practica del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan=2>Pre revisión.</td>
        <td>
          De acuerdo al checklist del dueño del PR definido al escribir la descripción, realiza la verificación de los items escritos. Si algo no se encuentra presente, registra el defecto en el Defect Log actual y corrige a la brevedad. 
        </td>
        <td rowspan=2>Dueño del PR.</td>
        <td>VER3.1, M&A2.1, M&A2.3</td>
    </tr>
    <tr>
        <td>
          Revisa que el entorno de verificación/validación permita probar los criterios de aceptación. 
        </td>
        <td>VAL2.1, CM2.1</td>
    </tr>
    <tr>
      <td>Pre revisión.</td>
        <td>
          Hablar con algún miembro del equipo (a excepción del dueño del PR) para hacer revisión en parejas.
        </td>
        <td rowspan=10>Revisores.</td>
        <td>VER2.1</td>
    </tr>
    <tr>
      <td rowspan=4>Revisión estática</td>
      <td>Lee la descripción del PR para saber más sobre los nuevos cambios a la base de código (code base).</td>
      <td>VER1.3, VER2.1, VAL1.3</td>
    </tr>
    <tr>
      <td>Abre el ticket relacionado al PR, revisa y analiza los criterios de aceptación y cualquier diagrama o modelo proporcionado en el ticket que servirán para realizar la validación del cambio.</td>
      <td>VAL1.1, VER1.1</td>
    </tr>
    <tr>
      <td>Realiza una revisión del código de acuerdo al checklist propuesto por el encargado del PR en la descripción. Si algo se cumple, marca la casilla correspondiente. Realicen esto en parejas para mejorar la detección de defectos. Registra cualquier defecto en el Defect Log.</td>
      <td>VER1.2, VER2.2, VAL1.2, M&A2.1, M&A2.3</td>
    </tr>
    <tr>
      <td>Si hay modelos del código presentes en el ticket, valida que estén implementados de manera correcta.</td>
      <td>VAL2.1</td>
    </tr>
    <tr>
      <td rowspan=3>Revisión con el cambio corriendo.</td>
      <td>Si el ambiente de verificación/validación es local, descarga los cambios, aplica migraciones y cualquier otra configuración establecida en la descripción del PR. Si el ambiente es en la nube, solamente abre el link proporcionado.</td>
      <td>VER1.2, VAL1.2, CM2.1</td>
    </tr>
    <tr>
      <td>Valida que los criterios de aceptación estén presentes y se cumplan. Si alguno no se cumple, registralo en el Defect Log actual.</td>
      <td>VAL2.1, M&A2.1, M&A2.3</td>
    </tr>
    <tr>
      <td>Valida que los modelos de interfaz gráfica se cumplan. Si alguno no se cumple, registralo en el Defect Log actual.</td>
      <td>VAL2.1, M&A2.1, M&A2.3</td>
    </tr>
    <tr>
      <td rowspan=2>Post revisión.</td>
        <td>
          Si encontraste defectos, una vez registrados en el Defect Log, solicita cambios en el PR para que sean atendidos por el dueño a la brevedad, comunicando los defectos registrados en el Defect Log. 
        </td>
        <td>M&A2.4</td>
    </tr>
    <tr>
        <td>
         Si no se encontraron defectos, aprueba los cambios del PR para poder hacer merge y hacer deploy a staging (si aplica). 
        </td>
        <td>M&A2.4</td>
    </tr>
  </tbody>
</table>

## Salidas

  1. Posible aprobación de PR.
  2. Posibles cambios solicitados al PR. 
  3. Posibles nuevas entradas al Defect Log.

**Comment by Topi99** [comment]
@Solify-IT/wiki-owners

**Comment by albertcastaned** [comment]
## Objetivos
* Verificar que los procesos cumplan con los estándares del departamento para la documentación de los procesos.

## Checklist
- [x] El título del proceso tiene un identificador único y un nombre como verbo en infinitivo. (Ejemplo: Mejorar, Conducir, Crear)

 Solo sería pasar en la wiki de "revisión de pull requests" a "revisar pull requests"
- [x] El proceso cubre los apartados que contiene la [plantilla de procesos](https://github.com/Solify-IT/docs/wiki/P00---Plantilla-para-procesos)
- [ ] Las prácticas de CMMI incluidas en las etapas del proceso están completas y correctas

Creo que la práctica de CM que aplica al igual que el proceso pasado de commits es CM SG2.1 "Seguir las peticiones de cambio"
- [x] El proceso no tiene faltas ortográficas o errores gramaticales.
- [x] La sintaxis de markdown funciona.

👍

**Comment by Topi99** [comment]
Listo

**Comment by albertcastaned** [comment]
## Objetivos
* Verificar que los procesos cumplan con los estándares del departamento para la documentación de los procesos.

## Checklist
- [x] El título del proceso tiene un identificador único y un nombre como verbo en infinitivo. (Ejemplo: Mejorar, Conducir, Crear)
- [x] El proceso cubre los apartados que contiene la [plantilla de procesos](https://github.com/Solify-IT/docs/wiki/P00---Plantilla-para-procesos)
- [x] Las prácticas de CMMI incluidas en las etapas del proceso están completas y correctas
- [x] El proceso no tiene faltas ortográficas o errores gramaticales.
- [x] La sintaxis de markdown funciona.

👍Lo veo bien

**Comment by LaloGlzMlz** [comment]
- [x] El título del proceso tiene un identificador único y un nombre como verbo en infinitivo. (Ejemplo: Mejorar, Conducir, Crear)
- [x] El proceso cubre los apartados que contiene la [plantilla de procesos](https://github.com/Solify-IT/docs/wiki/P00---Plantilla-para-procesos)
- [x] Las prácticas de CMMI incluidas en las etapas del proceso están completas y correctas
- [x] El proceso no tiene faltas ortográficas o errores gramaticales.
- [x] La sintaxis de markdown funciona.

👍🏼

**Comment by LaloGlzMlz** [comment]
Super bien Topi, lo subo a la wiki

**Comment by LaloGlzMlz** [comment]
Topi, la sección de referencias se quedará vacía o la eliminamos?

**Comment by Topi99** [comment]
> Topi, la sección de referencias se quedará vacía o la eliminamos?

Creo que la podemos eliminar.

**Comment by LaloGlzMlz** [comment]
Perfecto, lo corrijo a la hora de subirlo 👍🏼
