### ISSUE TITLE
Propuesta - Guía para escribir una descripción de PR completa.

### ISSUE THREAD

**Issue by Topi99** [Solify-IT/docs#16]
## Objetivos

  * Escribir una descripción de PR que comunique correctamente los cambios realizados a la base de código. 

## Creación de PR

Al crear un nuevo PR, la sección de "Descripción" se va a pre llenar con el siguiente template. 

```md
#### ¿Qué hace este PR?

#### ¿Cómo debería ser probado manualmente?

#### ¿Algún background que desees proveer? 

#### ¿Cuáles son los tickets relevantes? 

Usa el formato: SIGLAS-XX (ejemplo SNLX-99)

#### Screenshots

#### Preguntas

#### Checklist

**Assignees:**
- [ ] Añadí la documentación necesaria, si es necesario. 
- [ ] Agregué tests para probar que mi código funciona
- [ ] Revisé PRs existentes antes de publicar el mío. 

**Reviewers:**
- [ ] La Inyección de dependencias es correcta.
- [ ] No se importan archivos de niveles superiores de la arquitectura. 
- [ ] Los nombres de variables, objetos, clases y demás son entendibles. 
- [ ] El CI/CD Pipeline pasa.
 
```

Para comunicar los cambios de manera correcta, es necesario que llenes la mayor cantidad de secciones de template. Tal vez hayan ocasiones en las que no se necesiten algunas, pero las que recomendamos llenar el 100% de las veces son: 
  * **¿Qué hace este PR?**: Nos permite saber la intención del cambio, con una descripción detallada de las nuevas funcionalidades o arreglos a defectos introducidos. 
  * **¿Cómo debería ser probado manualmente?**: Tal vez la sección más importante de la descripción. Permite a los inspectores del PR saber cómo verificar/validar los nuevos cambios. Sin esta sección, puede que los revisores inviertan tiempo de más investigando cómo probar de manera correcta el cambio. 
  * **¿Cuáles son los tickets relevantes?**:  Permite a los inspectores saber más a detalle el ticket relacionado al PR. Da acceso a los criterios de aceptación, modelos y diagramas de la solución. 
  * **Checklist**: Permite llevar un registro individual de la calidad en el nuevo cambio del código.

**Comment by LaloGlzMlz** [comment]
## Objetivos
* Verificar que las guías cumplan con los estándares del departamento para la documentación de guías.


## Checklist
- [ ] El título de la guía comienza con G#, en donde # es un número único igual al número de la última guía +1, seguido de un nombre descriptivo, relevante a lo que la guía detalla comenzando por un sustantivo común o propio (Ejemplos: G04 Product Owner, G08 Propuestas de mejora continua).
- [ ] El primer apartado en la guía se llama "Descripción" y en este se da una breve descripción del propósito de existir de la guía en cuestión.
- [ ] En caso de ser una guía que propone mejora continua, esta sigue las especificaciones que describe la [G08 Propuestas de mejora continua](https://github.com/Solify-IT/docs/wiki/G08-Propuestas-de-mejora-continua).
- [ ] La redacción de la guía no tiene faltas ortográficas ni errores gramaticales.
- [ ] La sintaxis de markdown funciona.

**Comment by LaloGlzMlz** [comment]
- [ ] El título de la guía comienza con G#, en donde # es un número único igual al número de la última guía +1, seguido de un nombre descriptivo, relevante a lo que la guía detalla comenzando por un sustantivo común o propio (Ejemplos: G04 Product Owner, G08 Propuestas de mejora continua).

*solo sería agregarle el título correspondiente antes de subirla. Si quieres proponlo hasta arriba y ya cuando se suba a la wiki, este lo pondremos en el campo apropiado.*

- [ ] El primer apartado en la guía se llama "Descripción" y en este se da una breve descripción del propósito de existir de la guía en cuestión.

*Por motivos de consistencia, al ser esta una guía y no un proceso, solo sería cambiar el apartado de "Objetivos" a "Descripción y cambiar la redacción del mismo a uno de descripción".*

- [x] En caso de ser una guía que propone mejora continua, esta sigue las especificaciones que describe la [G08 Propuestas de mejora continua](https://github.com/Solify-IT/docs/wiki/G08-Propuestas-de-mejora-continua).
- [x] La redacción de la guía no tiene faltas ortográficas ni errores gramaticales.
- [x] La sintaxis de markdown funciona.

👍🏼

**Comment by LaloGlzMlz** [comment]
- [ ] El título de la guía comienza con G#, en donde # es un número único igual al número de la última guía +1, seguido de un nombre descriptivo, relevante a lo que la guía detalla comenzando por un sustantivo común o propio (Ejemplos: G04 Product Owner, G08 Propuestas de mejora continua).

*solo sería agregarle el título correspondiente antes de subirla. Si quieres proponlo hasta arriba y ya cuando se suba a la wiki, este lo pondremos en el campo apropiado.*

- [ ] El primer apartado en la guía se llama "Objetivos" y en este se listan numéricamente los objetivos de la guía en cuestión.

*Cambiar formato de listado de bullets a numérico*

- [x] En caso de ser una guía que propone mejora continua, esta sigue las especificaciones que describe la [G08 Propuestas de mejora continua](https://github.com/Solify-IT/docs/wiki/G08-Propuestas-de-mejora-continua).
- [x] La redacción de la guía no tiene faltas ortográficas ni errores gramaticales.
- [x] La sintaxis de markdown funciona.

👍🏼

**Comment by LaloGlzMlz** [comment]
- [ ] El título de la guía comienza con G#, en donde # es un número único igual al número de la última guía +1, seguido de un nombre descriptivo, relevante a lo que la guía detalla comenzando por un sustantivo común o propio (Ejemplos: G04 Product Owner, G08 Propuestas de mejora continua).

*solo sería agregarle el título correspondiente antes de subirla. Si quieres proponlo hasta arriba y ya cuando se suba a la wiki, este lo pondremos en el campo apropiado.*

- [x] El primer apartado en la guía se llama "Objetivos" y en este se listan con bullet points los objetivos de la guía en cuestión.

- [x] En caso de ser una guía que propone mejora continua, esta sigue las especificaciones que describe la [G08 Propuestas de mejora continua](https://github.com/Solify-IT/docs/wiki/G08-Propuestas-de-mejora-continua).
- [x] La redacción de la guía no tiene faltas ortográficas ni errores gramaticales.
- [x] La sintaxis de markdown funciona.

👍🏼

**Comment by LaloGlzMlz** [comment]
- [x] El primer apartado en la guía se llama "Objetivos" y en este se listan con bullet points los objetivos de la guía en cuestión.

- [x] En caso de ser una guía que propone mejora continua, esta sigue las especificaciones que describe la [G08 Propuestas de mejora continua](https://github.com/Solify-IT/docs/wiki/G08-Propuestas-de-mejora-continua).

- [x] El contenido de la guía es apropiado y cumple correctamente con los objetivos establecidos en el apartado de "Objetivos" de la misma.

- [x] La redacción de la guía no tiene faltas ortográficas ni errores gramaticales.

- [x] La sintaxis de markdown funciona.

👍🏼





- [ ] El título de la guía comienza con G#, en donde # es un número único igual al número de la última guía +1, seguido de un nombre descriptivo, relevante a lo que la guía detalla comenzando por un sustantivo común o propio (Ejemplos: G4 Product Owner, G8 Propuestas de mejora continua).

*solo sería agregarle el título correspondiente antes de subirla. Si quieres proponlo hasta arriba y ya cuando se suba a la wiki, este lo pondremos en el campo apropiado.*

- [x] El primer apartado en la guía se llama "Objetivos" y en este se listan con bullet points los objetivos de la guía en cuestión.

- [x] Se puede agregar el apartado opcional de "Descripción" en el cual se da una breve descripción de la guía propuesta; dicho apartado se encuentra antes del apartado de objetivos.

- [x] En caso de ser una guía que propone mejora continua, esta sigue las especificaciones que describe la [G8 Propuestas de mejora continua](https://github.com/Solify-IT/docs/wiki/G08-Propuestas-de-mejora-continua).

- [x] El contenido de la guía es apropiado y cumple correctamente con los objetivos establecidos en el apartado de "Objetivos" de la misma.

- [x] La redacción de la guía no tiene faltas ortográficas ni errores gramaticales.

- [x] Para listas se utilizan elementos numerados si es relevante el orden de importancia o una secuencia específica, de lo contrario utilizar siempre bullet points.

- [x] La sintaxis de markdown funciona.

**Comment by LaloGlzMlz** [comment]
- [ ] El título de la guía comienza con G#, en donde # es un número único igual al número de la última guía +1, seguido de un nombre descriptivo, relevante a lo que la guía detalla comenzando por un sustantivo común o propio (Ejemplos: G4 Product Owner, G8 Propuestas de mejora continua).

*solo sería agregarle el título correspondiente antes de subirla. Si quieres proponlo hasta arriba y ya cuando se suba a la wiki, este lo pondremos en el campo apropiado.*

- [x] El primer apartado en la guía se llama "Objetivos" y en este se listan con bullet points los objetivos de la guía en cuestión.

- [x] Se puede agregar el apartado opcional de "Descripción" en el cual se da una breve descripción de la guía propuesta; dicho apartado se encuentra antes del apartado de objetivos.

- [x] En caso de ser una guía que propone mejora continua, esta sigue las especificaciones que describe la [G8 Propuestas de mejora continua](https://github.com/Solify-IT/docs/wiki/G08-Propuestas-de-mejora-continua).

- [x] El contenido de la guía es apropiado y cumple correctamente con los objetivos establecidos en el apartado de "Objetivos" de la misma.

- [x] La redacción de la guía no tiene faltas ortográficas ni errores gramaticales.

- [x] Para listas se utilizan elementos numerados si es relevante el orden de importancia o una secuencia específica, de lo contrario utilizar siempre bullet points.

- [x] La sintaxis de markdown funciona.

👍🏼

**Comment by albertcastaned** [comment]
👍
