### ISSUE TITLE
Propuesta de mejora - P08 Conducir juntas de coordinación

### ISSUE THREAD

**Issue by Topi99** [Solify-IT/docs#18]
## Objetivos

  1. Planear las actividades a realizar durante el día
  2. Poder tener un estado real y preciso del estado del proyecto
  3. Poder mitigar retrasos de tareas y actualizar el plan de actividades a realizar durante la iteración

## Involucrados
  1. Team Leader
  2. Product Owner
  3. Architecture Owner
  4. Team Members
  5. Planning Owner (si aplica)
  6. Stakeholder o Mentor (si aplica y participa como observador)

## Entradas
  1. Lista de tareas realizadas con sus respectivos puntos ágiles y tiempos de realización
  2. Lista de tareas no realizadas y el blocker de las mismas (si aplica)

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Práctica del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan=3>Coordinación de Actividades</td>
      <td>Cada miembro responde a la pregunta: <b>¿Qué hice ayer?</b></td>
      <td>Miembro del Equipo</td>
      <td>PMC1.6, M&A2.1</td>
    </tr>
    <tr>
      <td>Cada miembro responde a la pregunta: <b>¿Qué voy a hacer hoy?</b></td>
      <td>Miembro del Equipo</td>
      <td>PP2.1, PP3.3, PMC1.2</td>
    </tr>
    <tr>
      <td>Cada miembro responde a la pregunta: <b>¿Qué me detiene?</b></td>
      <td>Miembro del Equipo</td>
      <td>PP2.2, PP2.5, PMC1.3</td>
    </tr>
    <tr>
      <td rowspan=3>Actualizar Herramientas de seguimiento de Tareas</td>
      <td>Actualizar el tablero de Tareas, moviendo las tareas con base a su estado y asignando el responsable.</td>
      <td rowspan=4>Team Leader</td>
      <td>PP3.2</td>
    </tr>
    <tr>
      <td>Actualizar Tabla de Valor Ganado ingresando los datos correspondientes de cada tarea. 
</td>
      <td>PP3.2, M&A2.3</td>
    </tr>
       <tr>
      <td>Verificar que los valores de SPI y CPI no estén fuera de los valores normales, si sí seguir proceso para replanear tareas de la iteración. 
      </td>
      <td>PP3.2, M&A2.2</td>
    </tr>

  </tbody>
</table>

## Salidas

  1. Tareas a realizar durante el día
  2. Posibles blockers
  3. Tablero de tareas actualizado
  4. Tabla y gráfica de valor ganado actualizado

**Comment by albertcastaned** [comment]
## Checklist
- [x] El título del proceso tiene un identificador único y un nombre como verbo en infinitivo. (Ejemplo: Mejorar, Conducir, Crear)
- [x] El proceso cubre los apartados que contiene la [plantilla de procesos](https://github.com/Solify-IT/docs/wiki/P00---Plantilla-para-procesos)
- [x] Las prácticas de CMMI incluidas en las etapas del proceso están completas y correctas
- [x] El proceso no tiene faltas ortográficas o errores gramaticales.
- [x] La sintaxis de markdown funciona.


💯 👍

**Comment by AdrizPaola** [comment]
Las prácticas están súper bien. 
De errores gramaticales, solo cambiaría esto:
    Cada miembro responde a **la pregunta:** ¿Qué voy a hacer hoy?
    Cada miembro responde a **la pregunta**: ¿Qué me detiene?

**Comment by LaloGlzMlz** [comment]
- [x] El título del proceso tiene un identificador único y un nombre como verbo en infinitivo. (Ejemplo: Mejorar, Conducir, Crear)
- [x] El proceso cubre los apartados que contiene la [plantilla de procesos](https://github.com/Solify-IT/docs/wiki/PL0---Plantilla-para-procesos)
- [x] Las prácticas de CMMI incluidas en las etapas del proceso están completas y correctas.
- [ ] Para listas se utilizan elementos numerados si es relevante el orden de importancia o una secuencia específica, de lo contrario utilizar siempre bullet points.

*Agregamos este punto en la checklist para mantener una mayor consistencia en las páginas de la wiki, sería solo cambiar los elementos de las listas por bullet points.*

- [ ] El proceso no tiene faltas ortográficas o errores gramaticales.

*Estoy de acuerdo con Adri, en las preguntas "qué voy a hacer hoy" y "qué me detiene", cambiar pregunta a singular.*

- [x] La sintaxis de markdown funciona.

👍🏼

**Comment by Topi99** [comment]
Listo, se me había pasado cambiar a singular

**Comment by LaloGlzMlz** [comment]
perfecto, lo subo
