### ISSUE TITLE
G10 Gestión de Riesgos

### ISSUE THREAD

**Issue by scarlosro** [Solify-IT/docs#19]
# Plan de Gestión de Riesgos

### Introducción

Al inicio de un nuevo proyecto, siempre es necesario considerar los riesgos que podrían afectar el desarrollo del producto hasta tal grado que no podamos concluir en tiempo y forma, por lo cual, este plan de gestión de riesgos es necesario para establecer una metodología en el cual los miembros identificarán riesgos , realizarán la evaluación que a continuación se describirá y se desarrollarán estrategias para mitigar o prevenir estos riesgos.

### Objetivo

Acordar la planificación de los riesgos, para llegar al éxito del proyecto y poder llevar la gestión de los riesgos iniciales y los que se puedan generar durante el desarrollo del proyecto.

### Definición de Riesgo

Un riesgo es una situación en la cual si llegara a ocurrir impactaría con el avance del proyecto; teniendo como consecuencia máxima la cancelación del proyecto, por lo cual, es todo aquello que nos pondría en peligro como equipo y departamento.

### Responsable de los Riesgos

El o los responsables de riesgo se definen de acuerdo con el tipo de riesgo, pues hay que considerar que hay personas que contienen una mayor relación con ese riesgo, por lo cual, aunque todos son responsables, hay quienes deben de dar una continuidad y revisión al riesgo, por lo cual, se irán identificando de acuerdo al riesgo.

### Identificación de Riesgos

La identificación de riesgos, se dará en la fase de inicio del proyecto y durante el ciclo de vida del proyecto, para esto se realizará seguimientos que posteriormente se estipulan, para revisión de ellos y realizar los cambios necesarios.

Posteriormente entraremos a un diálogo, considerando los siguientes puntos:

1. Debe estar relacionada a los procesos del proyecto.
2. Todos deben formar parte de las decisiones.
3. Tratar la incertidumbre explícitamente, es decir, su naturaleza y cómo puede tratarse.
4. La mejora continua de la organización.

Para ello se obtienen a través de:

1. Análisis del FODA el cual se lleva a cabo en junta con todo el departamento para hacer la identificación correcta de nuestras fortalezas, oportunidades, debilidades y amenazas, las cual nos ayudará a identificar riesgos y una discusión colaborativa.
2. Reunión de seguimiento de riesgos, donde se identifican riesgos de acuerdo con el contexto actual del proyecto y de la situación de los miembros.
3. Experiencias con proyectos similares, esto con el fin de tener conocimiento de estas situaciones que ya se hayan tenido experiencia y podemos mitigar en el proyecto actual

### Escala para el análisis cuantitativo de los riesgos (Probabilidad) :

Está evaluación en nuestros riesgos nos ayudará identificar cuánto es la posibilidad que pase dicho riesgo analizando la situación actual del proyecto y de los miembros del equipo, por lo cual, se define los rangos para tener una guía de apoyo en el análisis de riesgo; la cual también puede sufrir modificaciones.

<img width="605" alt="Captura de Pantalla 2021-05-05 a la(s) 20 43 54" src="https://user-images.githubusercontent.com/33816613/117230404-9ccfa480-ade2-11eb-910d-42c74a16dd2c.png">

### Escala para el análisis cuantitativo de los riesgos (Impacto) :

Cuando hablamos de impacto, nos referimos a que tanto afectaría el progreso del proyecto, es decir, las consecuencias que tendremos en el proyecto, esto al igual se analiza a través de la situación de los miembros del equipo y contexto actual del proyecto.

<img width="605" alt="Captura de Pantalla 2021-05-05 a la(s) 20 46 02" src="https://user-images.githubusercontent.com/33816613/117230537-e9b37b00-ade2-11eb-8a67-2ea5a2a1b3fd.png">

#### Prioridad de Riesgos
Ahora que definimos los valores y referencias para las probabilidades e impactos tenemos que tomar decisiones sobre estos valores para poder determinar la prioridad en el proyecto y darle la atención necesaria a través de los planes de mitigación y contingencia.

Por lo cual, para continuar con este paso es necesario identificar qué nivel de prioridad nos representa el riesgo a evaluar, por lo cual, el procedimiento fue multiplicar el valor del impacto por el valor de la probabilidad para obtener una magnitud, teniendo como máximo 8.1 y mínimo 0.1, quedando la matriz de la siguiente manera:

<img width="579" alt="Captura de Pantalla 2021-05-05 a la(s) 20 47 32" src="https://user-images.githubusercontent.com/33816613/117230625-1f586400-ade3-11eb-8290-8e89172d8683.png">

Definida la matriz, procedemos a darle un valor cualitativo al riesgo que fue definido acorde a la siguiente tabla:

<img width="602" alt="Captura de Pantalla 2021-05-05 a la(s) 20 47 53" src="https://user-images.githubusercontent.com/33816613/117230653-2b442600-ade3-11eb-97c7-ce45dd1025e9.png">

### Estado de los Riesgos:

Los riesgos al ser identificados y puesto en la matriz de riesgos podemos cambiarlo de estatus de acuerdo con la siguiente tabla con sus respectivas referencias:

<img width="551" alt="Captura de Pantalla 2021-05-05 a la(s) 20 50 55" src="https://user-images.githubusercontent.com/33816613/117230859-9857bb80-ade3-11eb-9ce7-669f20bafc5e.png">

### Fecha de seguimiento:

De acuerdo con la reunión de riesgos se acordó que se llevará a cabo cada semana en el día Jueves para realizar las actualizaciones, así como análisis de los riesgos que ocurrieron, eliminamos y nuevos que se detectaron.

**Comment by Topi99** [comment]
Me parece bien, solamente estaría mejor si la guía estuviera en Markdown, para seguir con el estándar de las demás en nuestra Wiki.

**Comment by LaloGlzMlz** [comment]
Estoy de acuerdo con topi, también por favor usa la checklist [CL2](https://github.com/Solify-IT/docs/wiki/CL2-Revisión-de-gu%C3%ADas) para revisarla y asegurarte que quede como las demás para que tú mismo la integres a la wiki

**Comment by scarlosro** [comment]
@Topi99 @LaloGlzMlz  Listo, espero su retro.

**Comment by albertcastaned** [comment]
👍
