### ISSUE TITLE
PL3 MATRIZ DE RIESGOS

### ISSUE THREAD

**Issue by scarlosro** [Solify-IT/docs#20]
https://docs.google.com/spreadsheets/d/1r24sFOnDGjIt0TvR-WsYcckXOIqTnW4pbiQfAV7dN-0/edit#gid=0

Es la pestaña "PLANTILLA MATRIZ".

**Comment by albertcastaned** [comment]
A lo mejor la plantilla podría estar en un archivo aparte y versionado para cumplir con la guia de gestion de la configuración en Google Drive que estamos desarrollando.

**Comment by LaloGlzMlz** [comment]
Si, el link que pusiste es ya a nuestra matriz, no realmente a una plantilla. Podríamos hacer un archivo en formato de plantilla para "llenar" en caso de que se hiciera una nueva o para que alguien externo sepa como la creamos

**Comment by scarlosro** [comment]
@albertcastaned ya realicé el cambio solicitado siguiendo la guía de gestión de la configuración.
@LaloGlzMlz

**Comment by albertcastaned** [comment]
👍
