### ISSUE TITLE
P14 PLANTEAR MATRIZ DE RIESGO

### ISSUE THREAD

**Issue by scarlosro** [Solify-IT/docs#21]
# P14 : PLANTEAR MATRIZ DE RIESGO

## Objetivos

  1. Generar la matriz inicial de riesgos de un proyecto.
  2. Conocer el sistema de evaluación y los puntos importantes para la gestión de riesgos.

## Involucrados
  1. Equipo de desarrollo

## Entradas

  1. Proyecto

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Practica del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan=2>1. Conociendo la Guía de Monitoreo de Riesgo.</td>
      <td>1.1 Leer la guía de gestión de riesgos para poder conocer la clasificación, evaluación y plan de seguimiento.</td>
      <td>Todos</td>
      <td> DAR 1.1 DAR 1.2 DAR 1.3 RSKM 1.1 RSKM 1.2</td>
    </tr>
    <tr>
      <td>1.2  Conocer la Matriz [plantilla](https://docs.google.com/spreadsheets/d/1r24sFOnDGjIt0TvR-WsYcckXOIqTnW4pbiQfAV7dN-0/edit#gid=0) de Riesgo con el fin de familiarizarse y conocer los campos a llenar y su significado. </td>
      <td>Todos</td>
      <td> DAR 1.1 RSKM 1.3 </td>
    </tr>
    <tr>
      <td rowspan=4>2. Planteo y análisis de riesgos.</td>
      <td>2.1  Elegir persona encargada a documentar.</td>
      <td>Todos</td>
      <td> RSKM 1.3 </td>
    </tr>
    <tr>
      <td>2.2 Dialogar sobre los riesgos presentes en el proyecto.</td>
      <td>Todos</td>
      <td>RSKM 2.1</td>
    </tr>
     <tr>
      <td>2.3 Documentar el riesgo y evaluar probabilidad e impacto.</td>
      <td>Encargado</td>
      <td>PP 2.2 RSKM 2.2 </td>
    </tr>
    <tr>
      <td>2.4 Documentar plan de mitigación y contingencia para los riesgos detectados y responsables para el seguimiento a la mitigación de ellos .</td>
      <td>Encargado</td>
      <td>RSKM 3.1 RSKM 3.2</td>
    </tr>
<tr>
      <td> 3. Seguimiento</td>
      <td>3.1 Acordar fechas de monitorización de riesgos. </td>
      <td>RSKM 1.3</td>
      <td> DAR 1.1 DAR 1.2 DAR 1.3 RSKM 1.1 RSKM 1.2</td>
    </tr>
  </tbody>
</table>

## Salidas

  1. Matriz de Riesgos y planes de mitigación y contingencia.

## Referencias
G10

**Comment by scarlosro** [comment]
La referencia pretendo corregirla en cuanto se haga el ajuste solicitado.

**Comment by LaloGlzMlz** [comment]
Opino que este proceso podría más bien se una plantilla, está bien planteado pero creo que no es necesario un proceso para hacer este archivo.

**Comment by LaloGlzMlz** [comment]
ya vi que si hiciste issue para la plantilla jajaja agregué comentarios en el otro issue de la plantilla

**Comment by Topi99** [comment]
## Checklist
- [x] El título del proceso tiene un identificador único y un nombre como verbo en infinitivo. (Ejemplo: Mejorar, Conducir, Crear)
- [x] El proceso cubre los apartados que contiene la [plantilla de procesos](https://github.com/Solify-IT/docs/wiki/PL0---Plantilla-para-procesos)
- [x] Las prácticas de CMMI incluidas en las etapas del proceso están completas y correctas.
Están bien las prácticas, aunque podemos igual implementar M&A. Estoy trabajando en el proceso de crear nuevas métricas, pero cuando esté listo, podemos hacer referencia de ese en este proceso. 

Igual estaría bien hacer referencia a la plantilla del paso 1.2.
- [x] Para listas se utilizan elementos numerados si es relevante el orden de importancia o una secuencia específica, de lo contrario utilizar siempre bullet points.
- [x] El proceso no tiene faltas ortográficas o errores gramaticales.
- [x] La sintaxis de markdown funciona.

**Comment by scarlosro** [comment]
Corrección añadida.
