### ISSUE TITLE
P15 MONITOREO DE RIESGOS

### ISSUE THREAD

**Issue by scarlosro** [Solify-IT/docs#22]
# P15: Monitoreo de Riesgos

## Objetivos

  * Validar la situación de los riesgos y el estado actual de ellos.
  * Actualizar los riegos, documentar nuevos riesgos y quitar aquellos que han sido eliminados totalmente.

## Involucrados
  * Equipo del Proyecto.
 
## Entradas

  * Proyecto
  * Matriz de Riesgos

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Practica del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan=4>Seguimiento de Riesgos</td>
      <td>1.1 Dar a conocer los riesgos que han sucedido, su estado actual y resultados.</td>
      <td>Todos</td>
      <td>MA 2.4 PMC 1.3</td>
    </tr>
    <tr>
      <td>1.2 Identificar los riegos nuevos y eliminados de acuerdo con la discusión.</td>
      <td>Todos</td>
      <td> PMC 1.3 PMC 1.7 PMC 2.2 RSKM 2.2 RSKM 3.1 RSKM 3.2</td>
    </tr>
    <tr>
      <td>1.3 Revaluación de los riesgos restantes para verificar su prioridad y probabilidad, así como su seguimiento.</td>
      <td>Todos</td>
      <td>PMC 1.7 PMC 2.2 RSKM 2.2 </td>
    </tr>
    <tr>
      <td>1.4 Registrar los datos de acuerdo con la información obtenida en la discusión  y elaborar el resumen del status global de acuerdo con los datos previos y actuales.</td>
      <td>Encargado</td>
      <td>MA 2.1MA 2.2MA 2.3MA 2.4</td>
    </tr>
    
  </tbody>
</table>

## Salidas

  * Matriz de Riesgos actualizada.
  * Decisiones para la forma de trabajo

## Referencias
G9

**Comment by scarlosro** [comment]
Igual que el proceso anterior (P14)

**Comment by albertcastaned** [comment]
Lo veo bien 👍 . De salida tambien podria ser cambios en la forma de trabajo o decisiones tomadas

**Comment by LaloGlzMlz** [comment]
Igual creo que de ahí en salidas podríamos ligarlo de alguna manera al proceso de toma de decisiones. Falta de mejorar ese proceso tambien pero creo que pueden ir de la mano.

**Comment by scarlosro** [comment]
Listo, ya esta corregido esa salida @albertcastaned. @LaloGlzMlz podrías ser un poco más explicito que cambios solicitarías.
Gracias.

**Comment by albertcastaned** [comment]
Del checklist solo faltaria cambiar el titulo a un verbo en infinitivo https://github.com/Solify-IT/docs/wiki/CL1---Revisi%C3%B3n-de-procesos. 

Cerrare el issue para que lo puedas subir a esta wiki y desde allí cambiar el título.
