### ISSUE TITLE
P7 Planificar iteración

### ISSUE THREAD

**Issue by A01702321** [Solify-IT/docs#24]
## Objetivos

  * Establecer y mantener planes que definan las actividades de la iteración

## Involucrados
  * Team members
  * Product Owner
  * Architecture Owner
  * Team Leader
  * Planning Owner (si aplica)

## Entradas
  * Ítems de trabajo

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Área del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Disponibilidad de Equipo</td>
      <td>Compartir la cantidad de horas disponibles para trabajar en el proyecto.</td>
      <td>Miembro del departamento involucrado</td>
      <td rowspan=11>PP, PMC, RA, RM</td>
    </tr>
    <tr>
      <td rowspan=7>Definición de Elemento de Trabajo</td>
      <td>Seleccionar un elemento de trabajo.</td>
      <td>Product Owner</td>
   </tr>
      <tr>
	      <td>Obtener los detalles del elemento de trabajo.</td>
	      <td>Product Owner</td>
	   </tr>
    <tr>
      <td>Modelar una solución potencial.</td>
      <td>Miembros del equipo</td>
   </tr>
    <tr>
      <td>Descomponer el elemento de trabajo en tareas.</td>
      <td>Miembros del equipo</td>
   </tr>
    <tr>
      <td>Asignar responsable del cumplimiento del elemento de trabajo</td>
      <td>Miembros del equipo</td>
   </tr>
    <tr>
      <td>Agregar elemento de trabajo a la pila de tareas</td>
      <td>Miembros del equipo</td>
   </tr>
    <tr>
      <td>Actualización de la estimación.</td>
      <td>Miembro del departamento involucrado</td>
   </tr>
   <tr>
    <td rowspan=3>Sanity Check</td>
    <td>Revisar la sensatez del plan (sanity check).</td>
    <td>Miembros del equipo</td>
  </tr>
    <tr>
      <td>Asignar de manera voluntaria una tarea a cada miembro para ser encargados de desarrollarla</td>
      <td>Miembro del departamento involucrado</td>
   </tr>
    <tr>
      <td>Verificar si los miembros del equipo se compromenten a completar sus tareas.</td>
      <td>Team Leader</td>
   </tr>
  </tbody>
</table>

## Salidas

  * Plan de la iteración
  * Pila de tareas
  * Sanity check

**Comment by A01702321** [comment]
Cambie el enrolarse en las tareas por asignar responsable para cumplir con parte de RM de CMMI, tambien en la parte de sanity check igual en vez de enrolar especificar que se asigne un encargado de desarrollar la tarea. Asi cumplimos con parte de compromiso de RM de CMMI. Tambien agregue la stack de trabajo a la planeación de iteración en vez de sólo tener ítems de trabajo y tareas.

**Comment by A01702321** [comment]
También cambié 'ítem de trabajo' por 'elemento de trabajo'

**Comment by albertcastaned** [comment]
👍
