### ISSUE TITLE
G12 Pair programming 

### ISSUE THREAD

**Issue by arcosmarce** [Solify-IT/docs#26]
**Descripción**

Esta guía existe con el propósito de establecer lineamientos a seguir cuando se implemente la técnica de Pair Programming

**Objetivos**

- Programar utilizando la práctica de Pair programming

**Involucrados**

- Escritor de código
- Supervisor de código 

**Pasos**

1. Abrir el ambiente de desarrollo en ambas computadoras
2. Colocarse en la misma rama para tener el mismo contenido de código
3. El escritor y supervisor de código deben establecer un tiempo en minutos para la rotación de roles
4. El primer escritor de código debe compartir el link de LiveShare con el primer supervisor de código, con el propósito de que los dos tengan en tiempo real el código y las pestañas por las cuales el escritor de código navega
5. Cuando el escritor de código está programando, el supervisor de código debe estar observando el procedimiento de codificación
6. Cuando el supervisor de código detecte algún defecto o error, debe registrarlo en el defect log del equipo y comunicarlo al escritor de código
7. Es de suma importancia registrar la detección y corrección de defectos en el defect log
8. El escritor de código debe corregir el defecto y el supervisor registrar los datos en el defect log
9. Cuando se cumpla el tiempo que establecieron al principio, los roles deben cambiar y seguir programando mediante LiveShare
10. Continuar desde el paso 5

**Comment by albertcastaned** [comment]
Por los pasos a lo mejor podría ser un proceso. El tiempo establecido de rotación podría ser con Pomodoro

**Comment by LaloGlzMlz** [comment]
Estoy de acuerdo, e incluso algunos de los pasos parecen más bien políticas, podríamos hacer una página de políticas para esta práctica si creen apropiado (ejemplo: [PO1 Manejo de unidad de Solify en Google Drive](https://github.com/Solify-IT/docs/wiki/PO1-Manejo-de-unidad-de-Solify-en-Google-Drive))

**Comment by arcosmarce** [comment]
Okay! entonces lo convierto a proceso!
Me parece más un proceso
