### ISSUE TITLE
G14 Creación de Métricas

### ISSUE THREAD

**Issue by Topi99** [Solify-IT/docs#28]
# G14: Creación de Métricas

## Contenido

* [Objetivo](#objetivo)
* [Definición de métrica](#definición-de-métrica)
* [Definir una meta](#definir-una-meta)
* [Desarrollar preguntas](#desarrollar-preguntas)
* [Especificar las métricas](#especificar-las-métricas)

## Objetivo

Guiar el establecimiento de objetivos y preguntas relacionadas a una métrica, para así poder obtener mejores datos sobre los cuales tomas aún mejor decisiones. 

## Definición de métrica

Las métricas son aquellos valores expresados numéricamente que sirven para analizar el rendimiento de una determinada acción o proceso dentro de una empresa. Cualquier cosa que se realice dentro del ámbito empresarial y sea medible, es una métrica.

## Definir una meta

Para definir una meta, hay que identificar un conjunto de objetivos, ya sean de calidad/productividad/bienestar, a nivel del departamento/proyecto de socio formador/personal.

Los objetivos identificados deben ser:

* específicos: ¿qué quiero lograr?
* medible: ¿se puede cuantizar el esfuerzo/avanze/logro del objetivo? 

Ejemplo: Identificar desviaciones del plan del proyecto.

## Desarrollar preguntas

Tomando como base los objetivos identificados, desarrolla un conjunto de preguntas para concretar la forma en que dichos objetivos serán alcanzados. Respondiendo las preguntas generadas, se podrá saber si el objetivo fue alcanzado y medido de la manera esperada.

Ejemplo: ¿cuál es la desviación actual de mi plan? ¿con qué velocidad avanzamos actualmente? ¿qué procentaje del proyecto deberíamos de haber alcanzado para el día de hoy? 

## Especificar las métricas

Ahora que tienes preguntas definidas, asocia cada una a un dato (o un conjunto de estos), de manera que puedan cuantizar las respuestas de cada pregunta. 

Una vez identificados todos los datos anteriores, tu métrica debe contar con:

* Nombre
* Objetivos
* Preguntas
* Fórmula (¿cómo se puede replicar la extracción de dicha métrica?)
* Ubicación (el lugar exacto en donde se encuentra la métrica con información actualizada)

**Comment by albertcastaned** [comment]
Lo veo bien 👍

**Comment by LaloGlzMlz** [comment]
## Objetivos
* Verificar que las guías cumplan con los estándares del departamento para la documentación de guías.


## Checklist
- [x] El título de la guía comienza con G#, en donde # es un número único igual al número de la última guía +1, seguido de un nombre descriptivo, relevante a lo que la guía detalla comenzando por un sustantivo común o propio (Ejemplos: G4 Product Owner, G8 Propuestas de mejora continua).

- [ ] El primer apartado en la guía se llama "Objetivos" y en este se listan con bullet points los objetivos de la guía en cuestión.

_Nada más sería agregar el apartado de objetivo, lo demás lo veo super_

- [x] Se puede agregar el apartado opcional de "Descripción" en el cual se da una breve descripción de la guía propuesta; dicho apartado se encuentra antes del apartado de objetivos.

- [x] En caso de ser una guía que propone mejora continua, esta sigue las especificaciones que describe la [G8 Propuestas de mejora continua](https://github.com/Solify-IT/docs/wiki/G8-Propuestas-de-mejora-continua).

- [ ] El contenido de la guía es apropiado y cumple correctamente con los objetivos establecidos en el apartado de "Objetivos" de la misma.

_Ya con el objetivo quedaría esta_

- [x] La redacción de la guía no tiene faltas ortográficas ni errores gramaticales.

- [ ] Para listas se utilizan elementos numerados si es relevante el orden de importancia o una secuencia específica, de lo contrario utilizar siempre bullet points.

- [x] La sintaxis de markdown funciona.

**Comment by Topi99** [comment]
Listo

**Comment by Topi99** [comment]
Integrado a la wiki https://github.com/Solify-IT/docs/wiki/G14-Creaci%C3%B3n-de-M%C3%A9tricas
