### ISSUE TITLE
G15 - Identificación de elementos de la configuración y líneas base

### ISSUE THREAD

**Issue by albertcastaned** [Solify-IT/docs#29]
## Descripción
Esta guía busca explicar qué es un elementos de configuración y cuales serán serán puestos bajo gestión de la configuración dentro del departamento para poder así tener un mayor control de los productos que conforman una línea base.

## Objetivos
* Conocer los elementos que serán puestos bajo gestión de configuración dentro del departamento y los criterios para identificarlos.
* Conocer las líneas bases establecidas dentro de Solify

### Elemento de configuración
Corresponde a un elemento que es parte del producto final. Un elemento de configuración puede incluir hardware, equipo, artefactos, software, documentación y cualquier entidad que pueda ser entregado al cliente o que involucre la forma de trabajo del departamento.

Un elemento no necesariamente debe mantenerse bajo control de configuración. Por lo tanto, se deben seleccionar cuáles se deben mantener.

#### Criterios para identificar un elemento de configuración
* Todos los elementos que deban ser incluidos en un entregable o liberación.
* Todos los elementos que se espera que cambien con el tiempo por errores o cambio de requisitos.
* Código fuente o herramientas necesarias para construir un producto.
* Documentos que servirán como base para el desarrollo de un equipo.
* Todos los elementos  dependientes de otros.

#### Criterios para identificar un elemento que no es un elemento de configuración
* Herramientas y documentos que no se espera que cambien durante el transcurso de un proyecto

### Productos de trabajo bajo gestión de la configuración
Con los criterios establecidos en la sección anterior, hemos identificado los siguientes productos para ponerlos bajo gestión de la configuración.

#### Productos de trabajo internos
* Guías
* Procesos
* Plantillas
* Checklists
* WBS
* Mapa de procesos

#### Productos entregados al cliente
* Código fuente
* Builds
* Manual de usuario

#### Productos recbididos de evaluadores
* Evaluaciones de SCAMPI

#### Herramientas del entorno de trabajo del proyecto
* Base de datos
* Stack tecnológico

#### Elementos para crear/describir los productos de trabajo
* Plan de backlog de tareas
* Diagramas y documentacion tecnica de requisitos
* Manual de arquitectura

#### Identificadores únicos
Para poder distinguir y buscar los elementos de configuración de una forma más sencilla y limpia se utilizarán identificadores únicos para cada tipo de elemento.

En la siguiente tabla puede ver el producto y el identificador. El # representa un número que será autoincrementado al crear nuevos productos del mismo tipo.

| Producto | Identificador |
| -------- | -------- |
| Políticas     | PO#     |
| Guías     | G#     |
| Procesos     | P#     |
| Plantillas     | PL#     |
| Checklists     | CL#     |
| WBS     | WBS#     |
| Mapa de procesos | MAP |
| Codigo fuente     | CO#     |
| Builds     | V#.#.# |
| Manual de usuario     | MU#     |
| Base de datos     | BD#     |
| Stack tecnológico     | STCK#     |
| Plan de backlog de tareas   | BACKLOG#     |
| Manual de arquitectura | ARQ# |
| Diagramas y documentacion tecnica de requisitos | DI#     |

En el caso de los equipos, se debera poner como prefijo el identificador unico utilizado para el equipo.

##### Ejemplo

| Descripcion | Identificador |
| -------- | -------- |
| Archivo de checklist de revision de codigo de Soolers: | SOOL CL1 - Checklist de revision de codigo |

## Niveles de los elementos de configuración

Los elementos de configuración tienen 3 niveles por los que puede estar en una instancia de tiempo. Los tres niveles son:
* ### Nivel dinámico:
     En este nivel no existe ningún control ni restricción sobre lo que pueda tener el elemento de configuración. Para que un elemento de configuración de nivel dinámico pase a nivel controlado debe haber un proceso o algún mecanismo que permita registrar estos cambios en alguna bitácora y a la vez guardar el historial de versiones.
* ### Nivel controlado
     Este es el nivel intermedio entre el nivel dinámico y estático. Para que un elemento de configuración entre o salga de nivel controlado se debe tener mecanismos, procesos, y/o aprobaciones que permitan tener control sobre los elementos de configuración. 
* ### Nivel estático
     El junto de todos los elementos de configuración en nivel estático en una instancia de tiempo forman una línea base. Una línea base es un snapshot o una versión de los elementos de configuración que han sido aprobados y gestionados previamente en el nivel controlado.

## Líneas bases identificadas

Una linea base es un conjunto de productos de trabajo que han sido revisados y validados. Se llaman linea base ya que estas sirven como el inicio para un desarrollo posterior. Para integrar cambios de los productos a una nueva version o snapshot de una linea base, se debe tener un procedimiento establecido para el control de cambios.

### Código fuente
* Repositorio de PSYQUE-ING
* Repositorio de SNORLAX

Esta línea base es controlada directamente con el control de versiones que brinda la herramienta Git. Los repositorios de los proyectos dentro del departamento tendrán un flujo de trabajo basado en el [modelo de ramas Driessen](https://nvie.com/posts/a-successful-git-branching-model/). De esta forma, se puede controlar los niveles del elemento de configuración de código fuente. Las ramas base junto con su equivalente en el nivel de elemento de configuración serian los siguientes:

* **Rama máster o main**:
     Representa el nivel estático del código fuente. Además, establece una versión o un snapshot de la línea base del código fuente. El código en este nivel sería el utilizado en ambiente de producción.
* **Rama develop**:
     Representa el nivel controlado del código fuente. Para pasar de un nivel dinámico a nivel controlado, o de nivel controlado a nivel estático se deben emplear mecanismos y validaciones que permiten verificar que se estén cumpliendo con los estándares de calidad del departamento.
* **Rama dinámica**:
     En este tipo de rama va de todo. Todo lo nuevo dentro de los repositorios que se esté desarrollando debe iniciar desde una rama dinámica y una vez terminada y validada pasar a una rama de control (develop).

#### Wiki de Solify
* Procesos
* Guias
* Políticas
* Plantillas
* Checklists
#### Wiki de PSYQUE-ING
* Checklists
* Plantillas
* Manual de arquitectura
#### Wiki de SNORLAX
* Checklists
* Plantillas
* Manual de arquitectura

### Descripción de los productos de trabajo
* Google Drive
  * Plantillas
  * Manuales de usuario

## Comité de Control de la Configuración (CCB)

El CCB es el comité responsable de asegurar que se esté cumpliendo con el plan de gestión de la configuración dentro de todo el departamento. Es importante que haya por lo menos un miembro del comité en cada equipo para poder asegurar que se esté cumpliendo la gestión de la configuración en ambos equipos.

Los miembros dentro del CCB actual (04/04/2021) son:
* Alberto Castañeda
* Eduardo González
* Javier Iñiguez

**Comment by arcosmarce** [comment]
La veo muy bien! muy completa

**Comment by arcosmarce** [comment]
- [ ] El título de la guía comienza con G#, en donde # es un número único igual al número de la última guía +1, seguido de un nombre descriptivo, relevante a lo que la guía detalla comenzando por un sustantivo común o propio (Ejemplos: G4 Product Owner, G8 Propuestas de mejora continua).

- [x] El primer apartado en la guía se llama "Objetivos" y en este se listan con bullet points los objetivos de la guía en cuestión.

- [ ] Se puede agregar el apartado opcional de "Descripción" en el cual se da una breve descripción de la guía propuesta; dicho apartado se encuentra antes del apartado de objetivos.

- [x] El contenido de la guía es apropiado y cumple correctamente con los objetivos establecidos en el apartado de "Objetivos" de la misma.

- [x] La redacción de la guía no tiene faltas ortográficas ni errores gramaticales.

- [x] Para listas se utilizan elementos numerados si es relevante el orden de importancia o una secuencia específica, de lo contrario utilizar siempre bullet points.

- [x] La sintaxis de markdown funciona.
`

**Comment by albertcastaned** [comment]
@arcosmarce

**Comment by arcosmarce** [comment]
Súper bien amigo! lo veo genial
