### ISSUE TITLE
P18 Gestionar métricas

### ISSUE THREAD

**Issue by Topi99** [Solify-IT/docs#32]
# P18: Gestionar métricas

## Objetivos

  * Generar un plan basado en las métricas obtenidas.
  * Asegurar la obtención, análisis, almacenamiento y comunicación de métricas de los proyectos. 

## Involucrados
  * Todos los miembros del equipo.

## Entradas

  * Datos generados en el periodo de tiempo que aplique para la métrica. 
  * [Guía de creación de métricas](https://github.com/Solify-IT/docs/wiki/G14-Creaci%C3%B3n-de-M%C3%A9tricas) (solo si es la primera gestión de la métrica). 
  * Repositorio de métricas. 

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Práctica del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Creación</td>
      <td>Si es la primera vez que se gestiona la métrica, regístrala en el reposiotorio de métricas, asignando id, nombre, objetivos y pregunta que responde. Para mas detalles, consulta la <a href="https://github.com/Solify-IT/docs/wiki/G14-Creaci%C3%B3n-de-M%C3%A9tricas">Guía de creación de métricas</a>.</td>
      <td rowspan=10>Miembros del equipo</td>
      <td>M&A1.1, M&A1.2, CM</td>
    </tr>
    <tr>
      <td rowspan=2>Obtención</td>
      <td>Diaramente recolecta los datos que alimentan el repositorio de métricas, para tenerlo lo mas actualizado posible.</td>
      <td rowspan=2>M&A2.1, M&A1.3</td>
    </tr>
    <tr>
      <td>Obtener las métricas generadas con los datos ingresados al repositorio de métricas.</td>
    </tr>
    <tr>
      <td rowspan=5>Análisis</td>
      <td>Identifica los objetivos y preguntas clave de relacionadas a la métrica.</td>
      <td rowspan=2>M&A2.2, M&A1.4</td>
    </tr>
    <tr>
      <td>Responder a las preguntas definidas en el repositorio de métricas.</td>
    </tr>
    <tr>
      <td>Compara los resultados actuales con los anteriores, y si hay una gráfica de tendencia, observa su comportamiento.</td>
      <td>M&A1.4, PMC (aplican varias prácticas específicas)</td>
    </tr>
    <tr>
      <td>Después de enteder el comportamiento de las tendencias de las métricas obtenidas, llena el historial de análisis y decisiones del repositorio de métricas con lo observado.</td>
      <td rowspan=2>M&A2.3, PMC (aplican varias prácticas específicas)</td>
    </tr>
    <tr>
      <td>Después de documentar el análisis, tomen una decisión como equipoy regístrenla de igual manera en la misma fila del historial.</td>
    </tr>
    <tr>
      <td rowspan=2>Comunicación</td>
      <td>Documenta las métricas y decisiones obtenidas de esta gestión de métricas en el siguiente reporte de estado del departamento.</td>
      <td>M&A2.3</td>
    <tr>
      <td>Comunica las métricas y decisiones obtenidas en la siguiente presentación del reporte de estado del departamento.</td>
      <td>M&A2.4, PP3.1</td>
    </tr>
  </tbody>
</table>

## Salidas

  * Repositorio de métricas actualizado.

## Referencias
  * [Guía de creación de métricas](https://github.com/Solify-IT/docs/wiki/G14-Creaci%C3%B3n-de-M%C3%A9tricas)

**Comment by LaloGlzMlz** [comment]
- [x] El título del proceso tiene un identificador único, un nombre como verbo en infinitivo y es descriptivo
- [x] Estructura organizada, siguiendo los lineamientos establecidos en la [plantilla de procesos](https://github.com/Solify-IT/docs/wiki/PL0---Plantilla-para-procesos)
- [x] Para cada actividad tener asignada una práctica de CMMI de manera completa y correcta
- [x] Todas las actividades deben estar asignadas a una etapa
- [x] Todas las actividades deben tener un encargado
- [x] El contenido cumple con los objetivos del proceso 
- [x] Las entradas y salidas tienen congruencia con las etapas y descripciones
- [x] Para listas se utilizan elementos numerados si es relevante el orden de importancia o una secuencia específica, de lo contrario utilizar siempre bullet points.
- [x] El proceso no tiene faltas ortográficas o errores gramaticales.
- [x] La sintaxis de markdown funciona.

👍🏼 aprobado

**Comment by arcosmarce** [comment]
- [x] El título del proceso tiene un identificador único, un nombre como verbo en infinitivo y es descriptivo
- [x] Estructura organizada, siguiendo los lineamientos establecidos en la [plantilla de procesos](https://github.com/Solify-IT/docs/wiki/PL0---Plantilla-para-procesos)
- [x] Para cada actividad tener asignada una práctica de CMMI de manera completa y correcta
- [x] Todas las actividades deben estar asignadas a una etapa
- [ ] Todas las actividades deben tener un encargado **idealmente debería ser un encargado individual y no uno general**
- [x] El contenido cumple con los objetivos del proceso 
- [x] Las entradas y salidas tienen congruencia con las etapas y descripciones
- [ ] Para listas se utilizan elementos numerados si es relevante el orden de importancia o una secuencia específica, de lo contrario utilizar siempre bullet points. **En involucrados tal vez sería conveniente que no fuera numeración**
- [ ] El proceso no tiene faltas ortográficas o errores gramaticales. **En análisis en la ultima celda falta un espacio y falta un acento en la palabra Práctica**
- [x] La sintaxis de markdown funciona.

**Comment by arcosmarce** [comment]
Ahí te dejo los comentarios Topi

**Comment by Topi99** [comment]
> idealmente debería ser un encargado individual y no uno general

¿Qué miembro del equipo crees que deba ser el encargado?

**Comment by arcosmarce** [comment]
No, así está bien, noi ví que arriba decía que todos los miembros del equipo.
Super bien Topi, nadamás el acento y el espacio :D

**Comment by Topi99** [comment]
Creo que ya quedó todo 😄
