### ISSUE TITLE
PO3 Manejo de la wiki de Solify

### ISSUE THREAD

**Issue by albertcastaned** [Solify-IT/docs#33]
## Objetivos

* Establecer lineamientos bajo los cuales realizar cambios en la wiki de Solify.

## Artículos

1. La wiki de Solify está actualmente bajo un [nivel de control "No controlado"](https://github.com/Solify-IT/docs/wiki/G15-Identificaci%C3%B3n-de-elementos-de-la-configuraci%C3%B3n-y-l%C3%ADneas-base#mecanismos-para-gestionar-niveles-de-control) para los miembros que conforman Solify y tienen un usuario dentro de la organización de Solify en Github. Los usuarios externos podrán acceder y leer la wiki pero no hacer contribuciones directas.
2. Está prohibido eliminar o modificar algún elemento dentro de la wiki sin antes comunicarlo al departamento.
3. Las contribuciones nuevas en la wiki deberán ser verificadas utilizando alguna checklist de revisión y validadas con al menos otro miembro de Solify.
4. El [comité de control de la configuracion](https://github.com/Solify-IT/docs/wiki/G15-Identificaci%C3%B3n-de-elementos-de-la-configuraci%C3%B3n-y-l%C3%ADneas-base#comit%C3%A9-de-control-de-la-configuraci%C3%B3n-ccb) deberá hacer una auditoria (gestión) semanalmente para verificar que no existan defectos y se mantenga la integridad de la wiki.
5. Todas las páginas nuevas deberán ser agregadas al Sidebar en la categoría adecuada para facilitar la navegación dentro de la wiki.
6. Los elementos dentro de la wiki serán versionados automáticamente con la herramienta implementada Git. Si se desea volver volver a una versión anterior de un elemento, o comparar los cambios entre diferentes versiones de un elemento, se puede utilizar la [siguiente guia.](https://docs.github.com/en/communities/documenting-your-project-with-wikis/viewing-a-wikis-history-of-changes#:~:text=You%20can%20only%20revert%20changes,added%2C%20removed%2C%20and%20modified.)

## Enlaces

- [G15 Identificación de elementos de la configuración y líneas base](https://github.com/Solify-IT/docs/wiki/G15-Identificaci%C3%B3n-de-elementos-de-la-configuraci%C3%B3n-y-l%C3%ADneas-base#comit%C3%A9-de-control-de-la-configuraci%C3%B3n-ccb)
- [Documentacion de Github - Usando Wikis](https://docs.github.com/en/communities/documenting-your-project-with-wikis/viewing-a-wikis-history-of-changes#:~:text=You%20can%20only%20revert%20changes,added%2C%20removed%2C%20and%20modified.)

**Comment by LaloGlzMlz** [comment]
Super! Le corrijo unos pequeños acentos y la subo a la wiki
