### ISSUE TITLE
P20 Gestionar requerimientos

### ISSUE THREAD

**Issue by JavierIQ** [Solify-IT/docs#34]
# P20 Gestionar requerimientos

## Objetivos

  * Analizar las necesidades del cliente
  * Listar los criterios para distinguir los requerimientos apropiados
  * Crear un conjunto de requerimientos

## Involucrados
  * Miembros del equipo
 
## Entradas

  * Las necesidades identificadas del socio para la solución 

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Práctica del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan=2>Identificación</td>
      <td>Reunión con socios Formadores: 
Esto promueve estar con los socios para conocer los criterios de su problema, por ese motivo se necesita estar con las personas indicadas que conozcan la gestión de la empresa y una claridad sobre lo que se requiere.</td>
      <td>PO</td>
      <td>PMI 2.1, REQM</td>
    </tr>
    <tr>
      <td>Identifica la necesidad del socio.</td>
      <td>PO, Miembros del Equipo</td>
      <td>RM 1.1, REQM</td>
    </tr>
    <tr>
      <td rowspan=4>Análisis</td>
      <td>Analiza si la necesidad añade valor a la solución</td>
      <td>PO, Miembros del Equipo</td>
      <td>RM 1.1, REQM</td>
    </tr>
    <tr>
      <td>Establece el criterio de aceptación para los requerimientos:
      <p>*Clara y correctamente enunciados.</p>              <p>*Completos</p>
<p>
* Consistencia entre requerimientos.
</p>
<p>
* Identificador único
</p>
<p>
* Consistencia con el enfoque arquitectónico y atributos de calidad.
</p>
<p>
* Apropiados de implementar.
</p>
<p>
* Verificable
</p>
<p>
* Alcanzable
</p>
<p>
* Atado a valor del negocio.
</p>
<p>* Identificado como una prioridad para el cliente.</p>
      </td>
      <td>PO, Miembros del Equipo</td>
      <td>RM 1.1, REQM</td>
    </tr>
    <tr>
      <td>Priorizar los requerimientos con su grado de valor ágil.</td>
      <td>PO, Miembros del Equipo</td>
      <td>RM 1.2, REQM</td>
    </tr>
     <tr>
      <td>Identificar los posibles riesgos de los requisitos.</td>
      <td>PO, Miembros del Equipo</td>
      <td>RM 1.2, REQM</td>
    </tr>
    <tr>
      <td rowspan=2>Revisión</td>
      <td>Evalúa los requerimientos en base a los criterios establecidos.</td>
      <td>PO, Miembros del Equipo</td>
      <td>RM 1.3, REQM</td>
    </tr>
    <tr>
      <td>Documentar requisitos en Plan de valor ganado y matriz de trazabilidad.</td>
      <td>PO, Miembros del Equipo</td>
      <td>RM 1.3, REQM</td>
    </tr>
    <tr>
    <td rowspan=1>Aceptación</td>
      <td>Validar y entender los requerimientos.
      <p>
        *Verificación con stakeholder
        *Validación de la necesidad a solucionar.
      </p>
      </td>
      <td>PO, Miembros del Equipo</td>
      <td>RM 1.4, REQM</td>
    </tr>
  </tbody>
</table>

## Salidas

  * Lista de requisitos para la solución del proyecto.

## Enlaces

[Reunión Stakeholders](https://github.com/Solify-IT/docs/wiki/P2-Realizar-juntas-con-socios-formadores)

**Comment by LaloGlzMlz** [comment]
- [ ] El título del proceso tiene un identificador único, un nombre como verbo en infinitivo y es descriptivo

_Yo le cambiaría el título, me parece que hay algunas palabras que funcionan mejor que creación_

- [x] Estructura organizada, siguiendo los lineamientos establecidos en la [plantilla de procesos](https://github.com/Solify-IT/docs/wiki/PL0---Plantilla-para-procesos)
- [ ] Para cada actividad tener asignada una práctica de CMMI de manera completa y correcta

_Faltaría especificar a qué subpráctica de RM corresponde cada actividad del proceso_

- [x] Todas las actividades deben estar asignadas a una etapa
- [x] Todas las actividades deben tener un encargado
- [x] El contenido cumple con los objetivos del proceso 
- [x] Las entradas y salidas tienen congruencia con las etapas y descripciones
- [x] Para listas se utilizan elementos numerados si es relevante el orden de importancia o una secuencia específica, de lo contrario utilizar siempre bullet points.
- [x] El proceso no tiene faltas ortográficas o errores gramaticales.

_tenía algunos pero ya se los corregí_

- [x] La sintaxis de markdown funciona.

**Comment by albertcastaned** [comment]
Igual estoy de acuerdo con Lalo falta especificar las subpracticas. Las actividades deben ser acciones concretas como si el proceso fuera una receta.

**Comment by Topi99** [comment]
Siento que todavía le falta más desarrollo a este proceso.

* El tiempo de los verbos creo debería ser en presente subjuntivo (recolecta, reúne, evalúa).
* Estaría bien hacer referencia a las herramientas que se utilizan para el almacenamiento y administración de los requisitos (Jira, Plan de valor ganado, matriz de trazabilidad). 
* Hay que dar más descripción a las actividades realizadas: 
  * > Establecer los criterios para la aceptación de requerimientos
    * ¿en dónde se establecen los criterios?
* ¿cómo se prioriza?
* ¿en dónde se registran y documentan los requerimientos? 
* ¿cuáles son los criterios establecidos de evaluación de requerimientos? 
* ¿cómo se validan los requerimientos? ¿con quién se validan? 

Yo creo que este proceso bien definido nos puede dar por completada el área de RM.

**Comment by Topi99** [comment]
Para complementar este proceso, estaría bien definir una guía de apoyo con más descripción sobre conceptos y pasos más complejos.

**Comment by Topi99** [comment]
¿Creen poder cambiar el enfoque del proceso? Para que sea de **Gestión de requerimientos** en lugar de creación?
