### ISSUE TITLE
P21 Actualizar/cambiar requerimientos del proyecto

### ISSUE THREAD

**Issue by JuanCarlosCV** [Solify-IT/docs#35]
## Objetivos

  * Actualizar requerimientos acuerdo a las necesidades del cliente

## Involucrados
  * Miembros del equipo
 
## Entradas

  * Una nueva necesidad identificada 

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Práctica del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan=2>Identificacion</td>
      <td>Reunión con socios formadores</td>
      <td>PO</td>
      <td>IPM 2.1</td>
    </tr>
    <tr>
      <td>Identificación de las necesidades del socio</td>
      <td>PO, Miembros del Equipo</td>
      <td>RM 1.1</td>
    </tr>
    <tr>
      <td rowspan=2>Analisis</td>
      <td>Comparar necesidad del requerimiento </td>
      <td>PO, Miembros del Equipo</td>
      <td>RM 1.2 </td>
    </tr>
    <tr>
      <td>Establecer los criterios para la aceptación de requerimiento</td>
      <td>PO,Miembros del Equipo</td>
      <td>RM 1.2</td>
    </tr>
    <tr>
      <td rowspan=2>Revision</td>
      <td>Evaluación del requerimiento con base en los criterios establecidos</td>
      <td>PO, Miembros del Equipo</td>
      <td>RM 1.3</td>
    </tr>
    <tr>
      <td>Validacion y entendimiento de los requerimiento</td>
      <td>PO,Miembros del Equipo</td>
      <td>RM 1.4</td>
    </tr>
     
  </tbody>
</table>

## Salidas

  * Nuevo Requisito funcional

## Referencias

[Reunion Stakeholders](https://github.com/Solify-IT/docs/wiki/P2-Realizar-juntas-con-socios-formadores)

**Comment by LaloGlzMlz** [comment]
- [x] El título del proceso tiene un identificador único, un nombre como verbo en infinitivo y es descriptivo
- [x] Estructura organizada, siguiendo los lineamientos establecidos en la [plantilla de procesos](https://github.com/Solify-IT/docs/wiki/PL0---Plantilla-para-procesos)
- [x] Para cada actividad tener asignada una práctica de CMMI de manera completa y correcta
- [x] Todas las actividades deben estar asignadas a una etapa
- [x] Todas las actividades deben tener un encargado
- [x] El contenido cumple con los objetivos del proceso 
- [x] Las entradas y salidas tienen congruencia con las etapas y descripciones
- [x] Para listas se utilizan elementos numerados si es relevante el orden de importancia o una secuencia específica, de lo contrario utilizar siempre bullet points.
- [x] El proceso no tiene faltas ortográficas o errores gramaticales.
- [x] La sintaxis de markdown funciona.

👍🏼

**Comment by LaloGlzMlz** [comment]
listo, lo subo a la wiki
