### ISSUE TITLE
P22 Administrar un plan de valor ganado

### ISSUE THREAD

**Issue by KevinWoolfolk** [Solify-IT/docs#36]
# P22 Crear proceso para Administrar un plan de valor ganado

## Objetivos

  * Administrar los work items del plan de valor ganador.
  * Poder tener control de la iteración del proyecto.

## Involucrados
  * Miembros del equipo
 
## Entradas

  * Historias de usuarios.
  * Seguimiento de progreso.
  * Backlog

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Área del CMMI</th>
    </tr>
  </thead>
  <tbody>
  <tr>
      <td rowspan=2>Documentación</td>
      <td>Se llenan las historias de usuarios en el plan</td>
      <td rowspan=10> Miembros del Equipo </td>
      <td rowspan=10> M&A </td>
  </tr>
  <tr>
      <td>Se definen los parámetros por cada work item como: puntos ágiles, y fecha estimada</td>
  </tr>
  <tr>
  <td rowspan=2>Gestión</td>
  <td>Se identifica cada  work item con su respectivo contenido y se divide en varias tareas</td>
  </tr>
  <tr>
  <td>Se verifica cuantas horas disponibles tiene cada miembro del equipo</td>
  </tr>
  <td rowspan=2>Seguimiento</td>
  <td> Lo miembros del equipo actualizan el progreso diario de su backlog</td>
  </tr>
  <tr>
  </tr>
  <td rowspan=2>Análisis</td>
  <td>Se actualiza la gráfica de progreso donde vemos valor ganado y valor planeado</td>
  </tr>
  <tr>
  </tr>
  </tbody>
</table>

## Salidas

  * Creación de plan de valor ganado con las fechas planeadas de entrega.
 

## Referencias

**Comment by Topi99** [comment]
Este proceso le veo más cara de guía, porque ya tenemos un proceso para la gestión de métricas que toca todas las actividades que mencionas en este proceso. 

En cuanto a las áreas, sí es M&A, pero también PP y PMC.

**Comment by Topi99** [comment]
Igual hay que especificar qué prácticas específicas de cada área son las relacionadas a cada actividad, no solo el área.

**Comment by Topi99** [comment]
También puedes hablar con @JavierIQ y @JuanCarlosCV para que unan esfuerzos y creen el proceso "Gestionar requerimientos", en el que también toquen el valor de plan ganado.
