### ISSUE TITLE
P23 Hacer un reporte de estado

### ISSUE THREAD

**Issue by LaloGlzMlz** [Solify-IT/docs#37]
## Objetivos

  * Actualizar a todos los miembros del departamento sobre el estado actual de cada uno de los proyectos en curso.
 
## Involucrados
  * Todo el departamento
 
## Entradas

  * Proyectos en desarrollo
  * Métricas
  * Análisis de resultados de las métricas 

## Etapas y descripciones

<table>
	<thead>
		<tr>
			<th>Etapa</th>
			<th>Actividad</th>
			<th>Encargado</th>
			<th>Pr&aacute;ctica del CMMI</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>Reuni&oacute;n</td>
			<td>Cada equipo se re&uacute;ne entre s&iacute; para comenzar a preparar diapositivas de su proyecto de equipo.<br />
			PM se re&uacute;ne con un miembro de cada equipo para preparar diapositivas de proyecto de departamento.</td>
			<td>Todo el departamento</td>
			<td rowspan="3">M&A 2.1,<br />
			<span>M&A 2.3,</span><br />
			M&amp;A 2.4</td>
		</tr>
		<tr>
			<td rowspan="2">Preparaci&oacute;n</td>
			<td>Actualizaci&oacute;n de m&eacute;tricas semanales. Para hacer esto, seguir el <a href="https://github.com/Solify-IT/docs/wiki/P18-Gestionar-métricas">proceso para gestionar m&eacute;tricas</a>.</td>
			<td>PM, Team Leader con su equipo</td>
		</tr>
		<tr>
			<td>En presentaci&oacute;n de reporte de estado, pegar capturas de pantalla de las distintas m&eacute;tricas, sus resultados y la comparaci&oacute;n de estos con los de la semana anterior. Para conocer m&aacute;s a detalle sobre las m&eacute;tricas que se incluyen en el reporte de estado, <a href="">gu&iacute;a de reportes de estado</a></td>
			<td>Todo el departamento</td>
		</tr>
		<tr>
			<td rowspan="4">Ejecuci&oacute;n</td>
			<td>Analizar datos obtenidos de las m&eacute;tricas, comparando con resultados de an&aacute;lisis anteriores para observar tendencias y tomar nuevas decisiones. Con este análisis se busca responder a las preguntas clave: ¿Dónde estoy?, ¿Dónde debería estar?, ¿Cuánto me ha costado?, ¿Por qué estoy dónde estoy? y ¿Cómo está la calidad?</td>
			<td>PM, Cada equipo</td>
			<td>M&A 2.2</td>
		</tr>
		<tr>
			<td>Una vez que las diapositivas est&eacute;n listas, juntar a todo el departamento para presentar reporte de estado internamente.</td>
			<td rowspan="2">Todo el departamento</td>
			<td rowspan="3">M&A 2.4</td>
		</tr>
		<tr>
			<td>PM presentar estado de proyecto de departamento al resto del departamento utilizando la presentaci&oacute;n.<br />
			Cada equipo presentar estado de respectivo proyecto de equipo al resto del departamento utilizando la presentaci&oacute;n. Establecer miembros del departamento para presentar cada proyecto a asesores.</td>
		</tr>
		<tr>
			<td>Presentar reporte a asesores para obtener retroalimentaci&oacute;n.</td>
			<td>Presentadores</td>
		</tr>
		<tr>
			<td>Retroalimentaci&oacute;n</td>
			<td>Analizar retroalimentaci&oacute;n obtenida de los asesores para atender para el siguiente reporte de estado.</td>
			<td>Todo el departamento</td>
			<td>SP 1.2</td>
		</tr>
	</tbody>
</table>

## Salidas

  * Reporte de estado

## Enlaces

* [P18 Gestionar métricas](https://github.com/Solify-IT/docs/wiki/P18-Gestionar-métricas)
* [Guía de reportes de estado]()

**Comment by Topi99** [comment]
* Creo que podemos hacer referencia a el proceso de gestión de métricas en la parte de `Actualización de métricas semanales`.
* Tal vez podríamos agregar una etapa que se llame "Retroalimentación", para atender los cambios y mejoras que podemos hacer para el siguiente reporte de estado.

**Comment by LaloGlzMlz** [comment]
perfecto muchas gracias topi, lo actualizo

**Comment by LaloGlzMlz** [comment]
para lo de las preguntas, eso creo que quedaría mejor mencionarlo en la guía auxiliar que crearé después, que opinas?

**Comment by LaloGlzMlz** [comment]
va, me parece. Sabes por qué la tabla se ve así en la row de "presentar reporte a asesores"? jajaja

**Comment by LaloGlzMlz** [comment]
Listo, cómo lo ves ahora?

**Comment by Topi99** [comment]
LGTM 👍

**Comment by albertcastaned** [comment]
- A lo mejor podria está dividido en más pasos, una instrucción por etapa.
- La guia de reporte de estado manda a la misma página. No se si se este trabajando en la guia ahorita.
- El último paso en el futuro podríamos enlazar a un proceso de retroalimentación que nos recomendó Lalo en la mañana

**Comment by LaloGlzMlz** [comment]
Si tienes razón algunos pasos están un poco largos. Los puedo separar y si la guía apenas se definirá. Lo subiré a la wiki así como está y le haré estas mejoras en la semana
