### ISSUE TITLE
P24 Definir Trazabilidad de un Requerimiento

### ISSUE THREAD

**Issue by A01702321** [Solify-IT/docs#38]
# P24 : Definir Trazabilidad de Requerimiento

## Objetivos

  1. Establecer la trazabilidad de requerimientos
  2. Tener acceso y conocimiento acerca de los componentes de un requerimiento.
  3. Tener acceso y conocimiento acerca de los requerimientos que afectan un componente.

## Involucrados
  1. Miembros de equipo

## Entradas

  1. Requerimientos
  2. Matriz de trazabilidad
  3. Componentes del proyecto
  4. Repositorio

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Practica del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan=2>Registro (Opcional)</td>
      <td>En caso de ser un nuevo requerimiento o historia de usuario registrar en matriz de trazabilidad.</td>
      <td rowspan=2>Miembro de equipo</td>
      <td rowspan=2>RM 1.1 RM 1.2</td>
    </tr>
    <tr>
      <td>Agregar recursos de análisis y diseño de la historia de usuario: Wireframes, descripción, diagrama de comunicación, etc.</td>
    </tr>
    <tr>
      <td rowspan=3>Modificar matríz</td>
      <td>Al terminar una historia de usuario, actualizar estado de la historia.</td>
      <td rowspan=3>Responsable de historia de usuario.</td>
      <td rowspan=3> RM 1.4</td>
    </tr>
    <tr>
      <td>Agregar enlace de los archivos de los componentes de backend y frontend del repositorio del proyecto</td>
    </tr>
    <tr>
      <td>Agregar enlace a evidencia de pruebas del requerimiento.</td>
    </tr>
  </tbody>
</table>

## Salidas

  1. Matriz de Trazabilidad Actualizada

## Referencias

**Comment by Topi99** [comment]
@A01702321 ¿Sí se incorporó a la wiki?
