### ISSUE TITLE
P04 Política de revisión en parejas

### ISSUE THREAD

**Issue by arcosmarce** [Solify-IT/docs#39]
## Objetivos

  * Agilizar la revisión de productos de trabajo.
  * Aumentar la calidad de los productos de trabajo.

## Indicaciones
En caso de ser:
   * Inspección de código fuente, se debe seguir el proceso de inspección de código
   * Inspección de código fuente en desarrollo, se debe seguir el proceso de <a href="https://github.com/Solify-IT/docs/wiki/P15-Programar-en-Parejas"> Programar en parejas</a>
   * Revisión de pull request se debe seguir el proceso para <a href="https://github.com/Solify-IT/docs/wiki/P13-Revisar-un-Pull-Request"> Revisar un pull request</a>
   * Evaluación de proceso, se debe seguir el proceso para <a href="https://github.com/Solify-IT/docs/wiki/P19-Evaluar-procesos"> Evaluar procesos</a>
   * Seguimiento y mejora de procesos, se debe seguir el proceso de Auditorías

## Artículos

1. Los productos de trabajo a evaluar deben estar definidos en los <a href="https://github.com/Solify-IT/docs/wiki/G15-Identificaci%C3%B3n-de-elementos-de-la-configuraci%C3%B3n-y-l%C3%ADneas-base"> Elementos de la configuración</a>
2. Las inspecciones a los productos y procesos de trabajo debe realizarse en pares, siguiendo los procesos correspondientes descritos en el apartado Indicaciones de esta página
3. En caso de no realizar la inspección en pares, entonces debe seguirse el proceso para cada inspección dependiendo del producto a evaluar, siguiendo los procesos correspondientes descritos en el apartado Indicaciones de esta página

   3.1 Cuando se haya finalizado la inspección, la persona encargada debe pedir una revisión para validar que se haya hecho de manera correcta
4. Las inspecciones y seguimiento de mejora de procesos siempre deben generar un registro que pueda ser consultado por todo el departamento.

**Comment by Topi99** [comment]
LGTM! Solamente habría que ponerle puntos finales a todas las oraciones. 👍
