### ISSUE TITLE
mejora: P13 Revisar Pull Request

### ISSUE THREAD

**Issue by Topi99** [Solify-IT/docs#40]
## Objetivos

  * Verificar y validar los cambios del Pull Request (PR).
  * Medir el estado de calidad del código que se quiere incorporar a través de defectos.

## Involucrados
  * Revisores del PR (miembros del equipo).
  * Dueño del PR.

## Entradas

  * Un PR listo para revisión. 

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Práctica del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan=3>Pre revisión.</td>
        <td>
          De acuerdo al checklist del dueño del PR definido al escribir la descripción, realiza la verificación de los items escritos. Si algo no se encuentra presente, registra el defecto en el Defect Log actual y corrige a la brevedad. 
        </td>
        <td rowspan=3>Autor del PR.</td>
        <td>VER1.1, M&A2.1, M&A2.3</td>
    </tr>
    <tr>
        <td>
          Determina qué entorno de verificación será usado en estas revisiones. Los entornos pueden estar en Heroku (el enlace se deberá proveer en la descripción del PR) o en local (con instrucciones de cómo probar y verificar los cambios en la descripción).
        </td>
        <td>VER2.1, CM2.1</td>
    </tr>
    <tr>
        <td>
          Comunica con el equipo de trabajo que tienes un PR listo para revisión. Solicita a mínimo 2 compañeros que realicen la revisión de tu PR. Asigna a los revisores en el PR, en la sección de "Reviewers (Revisores)".
        </td>
        <td>VER2.2</td>
    </tr>
    <tr>
      <td rowspan=5>Revisión estática</td>
      <td>Lee la descripción del PR para saber más sobre los nuevos cambios a línea base del producto de trabajo. En la descripción encontrarás el enlace al ticket con los criterios de aceptación, entre más datos.</td>
        <td rowspan=11>Team member.</td>
      <td>VER1.3, VER2.1</td>
    </tr>
    <tr>
      <td>Para identificar los componentes relacionados, revisa la pestaña "Files Changed (Archivos cambiados)" del Pull Request. Los archivos marcados con rojo y/o verde son los que necesitan una revisión.</td>
      <td>VER1.1</td>
    </tr>
    <tr>
      <td>Abre el ticket relacionado al PR (el enlace debería estar en la descripción del PR, en la sección de "tickets relevantes".), entiende los criterios de aceptación y cualquier diagrama o modelo proporcionado en el ticket, servirán para realizar la verificación del cambio.</td>
      <td>VER1.1</td>
    </tr>
    <tr>
      <td>Realiza una revisión del código de acuerdo al checklist propuesto por el encargado del PR en la descripción del mismo. Si algo se cumple, marca la casilla correspondiente. Realicen esto en parejas para mejorar la detección de defectos. Registra cualquier defecto en el Defect Log.</td>
      <td>VER1.2, M&A2.1, M&A2.3</td>
    </tr>
    <tr>
      <td>Si hay modelos del código presentes en el ticket, verifica que estén implementados de manera correcta.</td>
      <td>VER2.2, VER3.1</td>
    </tr>
    <tr>
      <td rowspan=3>Revisión con el cambio corriendo.</td>
      <td>Si el ambiente de verificación/validación es local, descarga los cambios, aplica migraciones y cualquier otra configuración establecida en la descripción del PR. Si el ambiente es en la nube, solamente abre el link proporcionado.</td>
      <td>VER1.2, CM2.1</td>
    </tr>
    <tr>
      <td>Verifica que los criterios de aceptación estén presentes y se cumplan. Si alguno no se cumple, registralo en el Defect Log actual.</td>
      <td>VER3.1, M&A2.1, M&A2.3</td>
    </tr>
    <tr>
      <td>Verifica que los modelos de interfaz gráfica se cumplan. Si alguno no se cumple, registralo en el Defect Log actual.</td>
      <td>VER3.1</td>
    </tr>
    <tr>
      <td rowspan=3>Post revisión.</td>
        <td>
          Si encontraste defectos, una vez registrados en el Defect Log, solicita cambios en el PR para que sean atendidos por el dueño a la brevedad, comunicando los defectos registrados en el Defect Log. Puedes revisar el <a href="https://github.com/Solify-IT/docs/wiki/P18-Gestionar-m%C3%A9tricas">Proceso para gestionar métricas</a> si es necesario.
        </td>
        <td>VER2.3, M&A2.4</td>
    </tr>
    <tr>
        <td>
          Analiza los resultados de las métricas y toma decisiones a partir de esto. Se recomienda que el análisis sea semanal para tener suficientes datos. Puedes revisar el <a href="https://github.com/Solify-IT/docs/wiki/P18-Gestionar-m%C3%A9tricas">Proceso para gestionar métricas</a> si es necesario. También, consulta la guía de análisis de defectos.
        </td>
        <td>VER3.2, M&A2.4</td>
    </tr>
    <tr>
        <td>
         Si no se encontraron defectos, aprueba los cambios del PR para poder hacer merge y hacer deploy a staging (si aplica). 
        </td>
        <td>M&A2.4</td>
    </tr>
  </tbody>
</table>

## Salidas

  * Posible aprobación de PR.
  * Posibles cambios solicitados al PR. 
  * Posibles nuevas entradas al Defect Log.

## Referencias

[Proceso para gestionar métricas](https://github.com/Solify-IT/docs/wiki/P18-Gestionar-m%C3%A9tricas)

**Comment by Topi99** [comment]
@Solify-IT/wiki-owners

**Comment by LaloGlzMlz** [comment]
Lo veo bien, solo opino que para hacer más corto cada paso del proceso, podríamos evitarnos algunas descripciones dentro de los pasos y hacer esa parte en una guía que vaya de la mano con el proceso. 

En cuestiones de formato solo veo que la etapa "Pre-revisión" está dos veces.

**Comment by albertcastaned** [comment]
Lo veo bien. Esto falta por determinar pero los archivos modificados se agregarían a la matriz de trazabilidad al crear el PR? O durante la codificación? Si seria en el PR podríamos ponerlo como etapa

**Comment by Topi99** [comment]
@albertcastaned Sí, voy a poner la etapa.

**Comment by Topi99** [comment]
Pensandolo bien, no lo voy a añadir. Este proceso es solo para revisar un PR. El mejor lugar sería en el proceso para crear el PR.
