### ISSUE TITLE
PIP: P20 Gestionar requerimientos

### ISSUE THREAD

**Issue by albertcastaned** [Solify-IT/docs#42]
## Objetivos

  * Transformar las necesidades de stakeholders a una lista de requisitos.
  * Definir el plan de gestión de requerimientos

## Involucrados
  * Miembros del equipo
  * Stakeholder
 
## Entradas

  * Necesidades identificadas del socio para la solución 

## Etapas y descripciones

<table>
<tbody>
  <tr>
    <td>Etapa</td>
    <td>Actividad</td>
    <td>Encargado</td>
    <td>Práctica del CMMI</td>
  </tr>
  <tr>
    <td rowspan="4">Análisis</td>
    <td>Traducir las necesidades de las partes interesadas en requisitos.</td>
    <td>PO</td>
    <td rowspan="2">RD 1.2</td>
  </tr>
  <tr>
    <td>Definir las restricciones de los requisitos en base a las reglas de negocio de los interesados y los atributos de calidad necesarios para el proyecto.</td>
    <td>PO, AO</td>
  </tr>
  <tr>
    <td> Evaluar los requerimientos en base a los criterios establecidos para la aceptación de una lista de requerimientos. </td>
    <td>PO</td>
    <td>RM 1.1</td>
  </tr>
  <tr>
    <td> Identificar los posibles riesgos de los requisitos con la guía de gestión de riesgos. </td>
    <td>Miembros del equipo</td>
    <td>RM 1.2, RSKM</td>
  </tr>
  <tr>
    <td rowspan="2">Compromiso</td>
    <td>Negociar cambios a compromisos de requisitos existentes si es necesario. Los compromisos pendientes deberán ser atendidos antes de cualquier compromiso nuevo.       </td>
    <td>Miembros del Equipo, Stakeholder</td>
    <td>RM 1.2,</td>
  </tr>
  <tr>
    <td>Evaluar el impacto de los nuevos requisitos o la modificación de requisitos solicitados. La trazabilidad bidireccional puede ser utilizada como herramienta para evaluar el impacto.        </td>
    <td>Miembros del Equipo</td>
    <td>RM 1.2, 1.3</td>
  </tr>
  <tr>
    <td rowspan="2">Documentación</td>
    <td>Documentar los cambios de la línea base de requisitos en la Bitácora de Cambios de la Matriz de Trazabilidad, con base en el Checklist para Documentación de Cambios de Requisitos.</td>
    <td>PO</td>
    <td>RM 1,3 1.5, CM 2.2</td>
  </tr>
  <tr>
    <td>Modificar la matriz de trazabilidad utilizando la información de los nuevos requisitos y/o los requisitos modificados.</td>
    <td>PO</td>
    <td>RM 1.4</td>
  </tr>
</tbody>
</table>

## Salidas

  * Lista de requisitos para la solución del proyecto.
  * Matriz de trazabilidad actualizada.
  * Compromisos

## Enlaces
[Criterios establecidos para la aceptación de una lista de requerimientos.](https://github.com/Solify-IT/docs/issues/46)

[Checklist para Documentación de Cambios de Requisitos](https://github.com/Solify-IT/docs/issues/47)

**Comment by Topi99** [comment]
@albertcastaned ¿puedes validar este proceso con alguien de la comunidad de prueba y/o con el profe Lalo?

**Comment by Topi99** [comment]
¿Está listo para revisar?

**Comment by albertcastaned** [comment]
Ya fue revisado por Ray. Lo ve bien, pero nos recomienda tener un proceso aparte para identificar las necesidades para que la salida de esas necesidades lleguen de entrada a este proceso.

**Comment by Topi99** [comment]
Super bien. LGTM

**Comment by albertcastaned** [comment]
Cerrare esta propuesta y la integrare a la wiki. Me pondré de acuerdo con @A01702321 para integrar su parte posteriormente.
