### ISSUE TITLE
PL4 Matriz de trazabilidad.

### ISSUE THREAD

**Issue by scarlosro** [Solify-IT/docs#44]
https://docs.google.com/spreadsheets/d/1i_MUeXDYdBC0C0HPrj--DVzxDx8GVxod2I5DcM-PBGs/edit#gid=2108397575

Propuesta de matriz de plantilla, se ajusta a nivel proyectos y departamento, no se agrego el estado porque sería tedioso agregar a otra lista el estado, cuando ya lo tenemos en nuestra lista de trabajo.

**Comment by albertcastaned** [comment]
Agregaria el mapeo de necesidades con los objetivos también. Igual artefactos de análisis y diseño relacionados al requisito/user story. No se si los criterios de aceptación podría ser bueno agregarlo desde la misma matriz. Max @A01702321 estaba encargado de la matriz de trazabilidad y tuvo asesoría con Lalo sobre esto a lo mejor podrías validarlo con el también.

**Comment by scarlosro** [comment]
@Topi99  @albertcastaned Cambios hechos agregando análisis y diseño en las columnas. Lo de necesidades lo analice con Topi y creo que eso esta de mas, ya que lo mas importante es ir con el objetivo.

Favor de su validación para proceder a implementarla en Soolers y que Rocket agregue estos campos necesarios.
Gracias.

**Comment by Topi99** [comment]
LGTM

**Comment by scarlosro** [comment]
Ok, lo cierro e incorporo a plantilla
