### ISSUE TITLE
P26 Realizar auditoría

### ISSUE THREAD

**Issue by arcosmarce** [Solify-IT/docs#45]
## Objetivos

  * Mejora continua de la forma de trabajo
  * Monitoreo de la forma de trabajo
 
## Involucrados
  * Auditor 1
  * Auditor 2
  * Encargado de proceso
  
## Entradas

  * <a href="https://docs.google.com/document/d/1tL0oHrttKqHvtn7hW4eL29pJxbjIE-APwM65ENuBpA4/edit">Plantilla de informe de auditoría</a>
  * <a href="https://docs.google.com/spreadsheets/d/1P-Xas2U-75T7mmUkr48rBJb1RE7R5jmV7j3Jo3NWhnE/edit#gid=0">Bitácora de auditorías y no conformidades</a>
  * <a href="https://docs.google.com/spreadsheets/d/1_KIhmVJvDel9i-Et1jryszM8FFvb53lXBMxy_-eRjY0/edit#gid=0">Plantilla de criterios de auditoría</a>
  * <a href="https://docs.google.com/spreadsheets/d/1P-Xas2U-75T7mmUkr48rBJb1RE7R5jmV7j3Jo3NWhnE/edit#gid=1657165314">Plantilla de no conformidades</a>
   
## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Práctica del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan=4>Análisis</td>
      <td>Definir el <a href="https://github.com/Solify-IT/docs/wiki/G15-Identificaci%C3%B3n-de-elementos-de-la-configuraci%C3%B3n-y-l%C3%ADneas-base">elemento de la configuración</a> (proceso, guía, platilla, checklist o política) que se va a auditar</td>
      <td>Auditor 1 y Auditor 2</td>
      <td> VER SP1.1, CM SP1.1</td>
    </tr>
    <tr>
      <td>Hacer una copia de la última versión del <a href="https://docs.google.com/document/d/1tL0oHrttKqHvtn7hW4eL29pJxbjIE-APwM65ENuBpA4/edit">Informe de auditoría</a> y nombrarla con el identificador:  AU(Número de 
                auditoría)_(Nombre del proceso a auditar) y guardarla en la carpeta Auditorías</td>
      <td >Auditor 1</td>
      <td> PPQA SP2.2, VER SP1.2, CM SP2.1</td>
    </tr>
 <tr>
      <td>Definir el objetivo de la auditoría</td>
      <td>Auditor 1 y Auditor 2</td>
      <td> VER SP1.2</td>
    </tr>
 <tr>
      <td>De acuerdo al <a href="https://docs.google.com/document/d/1tL0oHrttKqHvtn7hW4eL29pJxbjIE-APwM65ENuBpA4/edit">Informe de auditoría</a> plantilla, llenar los campos correspondientes para iniciar con la auditoría </td>
      <td >Auditor 1 y Auditor 2</td>
      <td>VER SP1.2</td>
    </tr>
    <tr>
      <td rowspan=2>Preparación</td>
      <td>Abrir el documento donde se encuentra la plantilla<a href="https://docs.google.com/document/d/1tL0oHrttKqHvtn7hW4eL29pJxbjIE-APwM65ENuBpA4/edit">Criterios de auditoría</a> correspondiente al elemento de configuración a auditar: ( <a href="https://docs.google.com/spreadsheets/d/1_KIhmVJvDel9i-Et1jryszM8FFvb53lXBMxy_-eRjY0/edit#gid=1686741355">proceso</a>,<a href="https://docs.google.com/spreadsheets/d/1_KIhmVJvDel9i-Et1jryszM8FFvb53lXBMxy_-eRjY0/edit#gid=26989366">guía</a>, <a href="https://docs.google.com/spreadsheets/d/1_KIhmVJvDel9i-Et1jryszM8FFvb53lXBMxy_-eRjY0/edit#gid=1607334260">política</a>, <a href="https://docs.google.com/spreadsheets/d/1_KIhmVJvDel9i-Et1jryszM8FFvb53lXBMxy_-eRjY0/edit#gid=1505476367">checklist</a>,  <a href="https://docs.google.com/spreadsheets/d/1_KIhmVJvDel9i-Et1jryszM8FFvb53lXBMxy_-eRjY0/edit#gid=1396401321">plantilla</a> )  , hacer una copia en el mismo documento y colocarla en una hoja nueva, nombrarla con el nombre de su informe de auditoría correspondiente</td>
      <td>Auditor 1 </td>
<td>VER SP1.2</td>
    </tr>
    <tr>
      <td>Abrir el documento <a href="https://docs.google.com/spreadsheets/d/1P-Xas2U-75T7mmUkr48rBJb1RE7R5jmV7j3Jo3NWhnE/edit#gid=0">Bitácora de auditoría</a>  y en la página principal registrar los links del informe y de la copia correspondiente de criterios de auditoría, con el nombre de su informe de auditoría correspondiente</td>
      <td>Auditor 1</td>
      <td>PPQA SP2.2, VER SP1.2, CM SP2.2</td>
    </tr>
     <tr>
      <td rowspan=6>Ejecución</td>
      <td>Abrir el <a href="https://github.com/Solify-IT/docs/wiki/G15-Identificaci%C3%B3n-de-elementos-de-la-configuraci%C3%B3n-y-l%C3%ADneas-base">elemento de la configuración</a> seleccionado para la auditoría</td>
      <td> Auditor 2</td>
      <td>VER SP1.2 </td>
    </tr>
      <td>Los elementos de la configuración deben ser auditados paso por paso. Si es un proceso el que se audita, para revisar que los pasos de este sean correctos, se debe revisar la evidencia de su cumplimiento en la forma de trabajo de Solify. </td>
      <td> Auditor 2</td>
      <td>PPQA SP1.1, PPQA SP2.2</td>
    </tr>
</tr>
</tr>
      <td>De acuerdo al documento criterios de evaluación, inspeccionar los pasos del elemento de la configuración seleccionado, registrando en el documento la resolución de cada uno de ellos, en caso de haber no conformidades, registrarlas</td>
      <td> Auditor 2</td>
      <td>PPQA SP1.1, PPQA SP2.2, VER SP1.3,  VER SP 2.2,  VER SP 3.1</td>
    </tr>
      <tr>
      <td>Para el registro de las no conformidades se crea una hoja nueva con el nombre de su informe de auditoría correspondiente, copiar y pegar la <a href="https://docs.google.com/spreadsheets/d/1P-Xas2U-75T7mmUkr48rBJb1RE7R5jmV7j3Jo3NWhnE/edit#gid=1657165314">Plantilla de no conformidades</a> y registrar las no conformidades </td>
      <td>Auditor 2 </td>
      <td>PPQA SP1.1, PPQA SP2.1, PPQA SP2.2, VER SP 3.2, CM SP 2.1</td>
    </tr>
  <tr>
      <td>Registrar las recomendaciones en el <a href="https://docs.google.com/document/d/1tL0oHrttKqHvtn7hW4eL29pJxbjIE-APwM65ENuBpA4/edit">Informe de auditoría</a>para que la persona encargada de la resolución de las no conformidades tenga mayor contexto</td>
      <td> Auditor 2</td>
      <td>PPQA SP1.1, PPQA SP2.2, VER SP 3.2, CM SP 2.1</td>
    </tr>
<tr>
   <td>Asignar a un responsable para dar seguimiento y resolución a cada no conformidad encontrada en la auditoría</td>
      <td> Auditor 1 y Auditor 2</td>
      <td>PPQA SP2.1,  VER SP 2.3, CM SP 2.1</td>
    </tr>
<tr>
      <td rowspan=1>Verificación</td>
      <td>Asegurarse que los documentos tengan el formato correcto, sin faltas de ortografía y estén completos</td>
      <td>Auditor 1 y Auditor 2 </td>
      <td>PPQA SP1.1, VER SP1.3</td>
    </tr>
    </tr>
<tr>
      <td rowspan=2>Comunicación de resultados</td>
      <td>Notificar por medio de Slack en el canal solify-evaluacion-procesos a los encargados de cada proceso  (designados en la junta de departamento)  que la auditoría finalizó</td>
      <td>Auditor 1 </td>
      <td>PPQA SP2.1</td>
    </tr>
<tr>
      <td>Acordar una reunión entre los Auditores y los Encargados de los procesos para comunicar los resultados de la auditoría y establecer las fechas límite para atender las no conformidades</td>
      <td>Auditor 1,  Auditor 2 y Encargado de proceso</td>
      <td>PPQA SP2.1, CM SP 2.1</td>
    </tr>
<tr>
      <td rowspan=1>Calendarización de las auditorías</td>
      <td>Una vez finalizada la inspección, los auditores deben fijar la fecha de la siguiente auditoría dependiendo de los resultados obtenidos (los auditores se elegirán en la junta de coordinación del departamento)</td>
      <td>Auditor 1 y Auditor 2 </td>
      <td>PPQA SP1.1, VER SP2.1</td>
    </tr>
<tr>
<tr>
      <td rowspan=2>Seguimiento de las no conformidades</td>
      <td>Los encargados de los procesos deben corregir las no conformidades antes de la fecha límite estipulada en la reunión con los auditores</td>
      <td>Encargado de proceso </td>
      <td>PPQA SP1.1, PPQA SP2.1, CM SP 2.1</td>
    </tr>
<tr>
      <td>Los encargados de los procesos deben comunicar por medio de Slack en el canal solify-evaluacion-procesos al departamento cuando hayan finalizado las correcciones</td>
      <td>Encargado de proceso </td>
      <td>PPQA SP2.1</td>
    </tr>
  </tbody>
</table>

## Salidas

  1. Informe de auditoría
  2. Bitácora de auditoría y no conformidades llena

**Comment by albertcastaned** [comment]
## Checklist
- [ ] El título del proceso tiene un identificador único, un nombre como verbo en infinitivo y es descriptivo
El título del proceso podría ser una acción o un verbo en infinitivo mas especifico.
- [x] Estructura organizada, siguiendo los lineamientos establecidos en la [plantilla de procesos](https://github.com/Solify-IT/docs/wiki/PL0---Plantilla-para-procesos)
- [ ] Para cada actividad tener asignada una práctica de CMMI de manera completa y correcta.

- La actividad 1.1 podria tener un enlace a la guia de [elementos de configuracion](https://github.com/Solify-IT/docs/wiki/G15-Identificaci%C3%B3n-de-elementos-de-la-configuraci%C3%B3n-y-l%C3%ADneas-base)
- La actividad 1.2 puede cambiarse a que se cree una copia de la última versión o la línea base de la plantilla de auditoría. (CM SP 2.1)
- La actividad 2.2 también involucra CM SP 2.2. La bitácora servirá para tener un historial de las revisiones de los elementos de configuración.
- La última actividad no creo que tenga la práctica CM SP 2.1

- [x] Todas las actividades deben estar asignadas a una etapa
- [x] Todas las actividades deben tener un encargado
- [ ] El contenido cumple con los objetivos del proceso
En mi opinión los objetivos podrían cambiar para que contesten el por que del proceso. ¿Que se quiere lograr haciendo auditorias?
- [x] Las entradas y salidas tienen congruencia con las etapas y descripciones
- [x] Para listas se utilizan elementos numerados si es relevante el orden de importancia o una secuencia específica, de lo contrario utilizar siempre bullet points.
- [x] El proceso no tiene faltas ortográficas o errores gramaticales.
- [x] La sintaxis de markdown funciona.

## Notas

- Creo que no tenemos encargados de procesos como tal aun. A lo mejor tenemos que definir eso.
- Siento que nos regañarian por poner Whatsapp como medio de comunicación. A lo mejor generalizarlo a comunicar por mensaje.

**Comment by arcosmarce** [comment]
Muchas gracias!

1. Cambié el título
2. Todos los enlaces los pondré cuando tenga todos las rubricas y herramientas (mañana), para aprovechar y poner todo en una vez
3. Hice los cambios en redacción y de prácticas
4. Cambié los objetivos
5. Mencioné que asignamos los encargados de los procesos en la daily
6. Cambié Whatsapp por slack
