### ISSUE TITLE
CL4 Criterio de aceptación para lista de requerimientos

### ISSUE THREAD

**Issue by albertcastaned** [Solify-IT/docs#46]
- [ ] Claros y correctamente enunciados.

- [ ] Hay consistencia entre los requerimientos

- [ ] Tienen identificadores únicos

- [ ] Consistente con la arquitectura del proyecto y sus prioridades de atributos de calidad

- [ ] Están dentro del alcance del proyecto

- [ ] Se pueden verificar y probar

- [ ] Brindan valor al negocio del stakeholder

**Comment by Topi99** [comment]
LGTM

**Comment by domerent97** [comment]
Yo lo veo bien, listo para agregar a la wiki :)
