### ISSUE TITLE
G16 Guía de demo para socio formador

### ISSUE THREAD

**Issue by A01702321** [Solify-IT/docs#49]
# G16 Demostración y validación con socio formador

## Objetivo

* Especificar la manera de presentar un demo del proyecto al socio formador.
* Validar productos de trabajo con el socio formador.

## Antes del Demo

Es muy importante previo a la demostración decidir primero qué es lo que se va a mostrar en el demo. Decidir si la demostración va a ser de algun requisito ya implemetado en el sistema, de diseño del sistema, etc.

Al tener establecido lo que se va a demostrar se debe llenar ahora la <a href="https://github.com/Solify-IT/docs/wiki/PL07-Validaci%C3%B3n-de-productos-de-trabajo">plantilla de validación de productos de trabajo</a>, es necesario llenar

* Requerimiento(s)
* Componente(s) a validar
* Criterios de aceptación
* Entorno de validación
* Flujo de demostración
* ¿Se necesita adquirir algo?

## Tipo de Demostración

Ya con la plantilla completa es necesario establecer el tipo de demostración que se va a presentar:
* Video
* En vivo

Se puede grabar un video de la demostración que se hará al socio formador.

También se puede preparar el ambiente para hacer la demostración en vivo, es decir compartiendo pantalla en una reunión.

  
## Preparación

Antes de la demostración hay que estar preparados. Si es que se va a hacer en video, es bueno realizar la grabación previamente y tomando en cuenta todos los puntos establecidos en la <a href="https://github.com/Solify-IT/docs/wiki/PL07-Validaci%C3%B3n-de-productos-de-trabajo">plantilla de validación de productos de trabajo</a>. En caso de ser en vivo la demostración es necesario hacer una prueba completa de lo presentado antes y asegurar que el ambiente este funcionando bien.

Es importante tomar en cuenta que la demostración es al socio formador, lo presentado debe ser claro y conciso. El socio formador no sabe utilizar el sistema y debe ser fácil de entender lo que se esta demostrando.
    
 
## Presentación

A la hora de la presentación del demo hay que tener la <a href="https://github.com/Solify-IT/docs/wiki/PL07-Validaci%C3%B3n-de-productos-de-trabajo">plantilla de validación de productos de trabajo</a> a la mano para llenarla con comentarios del socio formador. 

Lentamente y por pasos se deben mostrar los componentes en cuestión, hay que mostrar todos los pasos de manera detallada para que el socio formador pueda ver y entender el componente a profundidad.

## Retroalimentación

Al hacer una demostración del sistema buscamos retroalimentación de parte del socio formador. Hay que fomentar que el socio haga preguntas y de retroalimentación de lo mostrado.

Al terminar la demostración del sistema, se debe compartir la Validación de productos al socio formador y pedir aprobación por parte del socio llenando el log de demostración ([ejemplo de log de Team Rocket](https://docs.google.com/spreadsheets/d/1rlwUdQekTLXOhD_nHkib2UmEqrVPj_7cw9bRQ_Rm97Q/edit#gid=1200967876)).

## Pila de cambios

- 20/05/2021 - Se crea la guía.

**Comment by Topi99** [comment]
@A01702321 ¿Ya está lista?

**Comment by A01702321** [comment]
Ya esta completa y editada, cambiamos el título y poco del contenido

**Comment by Topi99** [comment]
Creo que ya puedes cerrar el issue y añadirla a la wiki.

**Comment by scarlosro** [comment]
Se ve bien la guía, ¿Ya la documentaste? Para cerrar el issue y no crear un cuello de botella.

**Comment by LaloGlzMlz** [comment]
La subo a la wiki
