### ISSUE TITLE
propuesta: P26 Convertir retroalimentación a tarea del plan

### ISSUE THREAD

**Issue by Topi99** [Solify-IT/docs#50]
## Objetivos

  * Reconocer tareas para atender retroalimentación de stakeholders.

## Involucrados

  * Miembros del equipo.

## Entradas

  * Retroalimentación de reporte de estado.
  * Retroalimentación de SCAMPI.
  * Retroalimentación de presentación de avance.
  * Retroalimentación del socio formador.
  * Defectos de productos de trabajo.

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Práctica del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan=2>Recolección</td>
      <td>Recolecta la retroalimentación a ser analizada de acuerdo a la <a href="https://github.com/Solify-IT/docs/wiki/G7-Gu%C3%ADa-para-atender-retroalimentaci%C3%B3n">Guía para atender retroalimentación.</a>.</td>
      <td rowspan=5>Team Leader o Program Manager</td>
      <td rowspan=2>PMC2.1</td>
    </tr>
    <tr>
      <td>Basandote en la <a href="https://github.com/Solify-IT/docs/wiki/G7-Gu%C3%ADa-para-atender-retroalimentaci%C3%B3n">guía</a>, determina si los elementos son elegibles para una acción correctiva.</td>
    </tr>
    <tr>
      <td rowspan=4>Corrección</td>
      <td>De acuerdo a la <a href="https://github.com/Solify-IT/docs/wiki/G7-Gu%C3%ADa-para-atender-retroalimentaci%C3%B3n">guía</a>, determina y documenta las acciones a realizar en los elementos identificados.</td>
      <td rowspan=2>PMC2.2</td>
    </tr>
    <tr>
      <td>Habla con el equipo y los stakeholders involucrados sobre si las acciones identificadas son las correctas para llevar a cabo las correcciones.</td>
    </tr>
  </tbody>
</table>

## Salidas

  * Lista de tareas a ser atendidas en el plan.

## Enlaces

  * [Guía para atender retroalimentación](https://github.com/Solify-IT/docs/wiki/G7-Gu%C3%ADa-para-atender-retroalimentaci%C3%B3n)

## Cambios

- 20/05/2021 - Se define el proceso.

**Comment by Topi99** [comment]
La guía sigue pendiente.

**Comment by ricardo-esc** [comment]
Estaria bien añadir un paso que sea como monitorear el desarrollo o finalización de la tarea?

**Comment by AdrizPaola** [comment]
Súper bien, creo que también sería necesario añadir los enlaces de los documentos, por ejemplo, el de acciones correctivas, ya sea como plantilla o como link en la actividad nadamas :D.

**Comment by Topi99** [comment]
@ricardo-esc creo que ese sería parte de otro proceso. Si añadimos ese paso a este proceso, haríamos dos actividades en dos fechas u horas diferentes. Pienso que en la junta de coordinación diaria podemos hacer ese monitoreo.

**Comment by Topi99** [comment]
🚀
