### ISSUE TITLE
Cambio P20 Gestionar Requisitos

### ISSUE THREAD

**Issue by A01702321** [Solify-IT/docs#51]
## Objetivos

  * Analizar las necesidades del cliente
  * Listar los criterios para distinguir los requerimientos apropiados
  * Crear un conjunto de requerimientos

## Involucrados
  * Miembros del equipo
 
## Entradas

  * Las necesidades identificadas del socio para la solución 
  * Objetivos de proyecto

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Práctica del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan=2>Identificación</td>
      <td>Reunión con socios Formadores: 
Esto promueve estar con los socios para conocer los criterios de su problema, por ese motivo se necesita estar con las personas indicadas que conozcan la gestión de la empresa y una claridad sobre lo que se requiere.</td>
      <td>PO</td>
      <td>PMI 2.1, REQM</td>
    </tr>
    <tr>
      <td>Identifica la necesidad del socio.</td>
      <td>PO, Miembros del Equipo</td>
      <td>RM 1.1, REQM</td>
    </tr>
    <tr>
      <td rowspan=4>Análisis</td>
      <td>Analiza si la necesidad añade valor a la solución</td>
      <td>PO, Miembros del Equipo</td>
      <td>RM 1.1, REQM</td>
    </tr>
    <tr>
      <td>Establece el criterio de aceptación para los requerimientos:
      <p>*Clara y correctamente enunciados.</p>              <p>* Completos</p>
<p>
* Consistencia entre requerimientos. *
</p>
<p>
* Identificador único
</p>
<p>
* Consistencia con el enfoque arquitectónico y atributos de calidad. 
</p>
<p>
* Apropiados de implementar.
</p>
<p>
* Verificable
</p>
<p>
* Alcanzable
</p>
<p>
* Atado a valor del negocio.
</p>
<p>* Identificado como una prioridad para el cliente.</p>
      </td>
      <td>PO, Miembros del Equipo</td>
      <td>RM 1.1, REQM</td>
    </tr>
    <tr>
      <td>Priorizar los requerimientos con su grado de valor ágil.</td>
      <td>PO, Miembros del Equipo</td>
      <td>RM 1.2, REQM</td>
    </tr>
     <tr>
      <td>Identificar los posibles riesgos de los requisitos.</td>
      <td>PO, Miembros del Equipo</td>
      <td>RM 1.2, REQM</td>
    </tr>
    <tr>
      <td rowspan=2>Revisión</td>
      <td>Evalúa los requerimientos con base en los criterios establecidos.</td>
      <td>PO, Miembros del Equipo</td>
      <td>RM 1.3, REQM</td>
    </tr>
    <tr>
      <td>Documentar requisitos en Plan de valor ganado y matriz de trazabilidad.</td>
      <td>PO, Miembros del Equipo</td>
      <td>RM 1.3, REQM</td>
    </tr>
    <tr>
      <td rowspan=2>Cambios</td>
      <td>Al presentarse en la necesidad de hacer un cambio de los requerimientos, documentar dicho cambio en la Bitácora de Cambios de la Matriz de Trazabilidad.</td>
      <td>PO, Miembros del Equipo</td>
      <td>RM 1.3/1.5, REQM</td>
    </tr>
        <tr>
      <td>La bitácora de cambios debe incluir la fecha del cambio, un resumen explicando el qué y por qué, el tipo de cambio (nuevo requisito, cambio), requerimientos afectados, impacto y notas.</td>
      <td>PO, Miembros del Equipo</td>
      <td>RM 1.3/1.5, REQM</td>
    </tr>
    <tr>
    <td rowspan=1>Aceptación</td>
      <td>Validar y entender los requerimientos.
      <p>
        *Verificación con stakeholder
        *Validación de la necesidad a solucionar.
      </p>
      </td>
      <td>PO, Miembros del Equipo</td>
      <td>RM 1.4, REQM</td>
    </tr>
  </tbody>
</table>

## Notas (*)
- Para revisar la consistencia entre requisitos hay que analizar el requisito como tal. Primeramente revisar que el requisito este alineado con el plan y objetivos del proyecto. Responder la pregunta: ¿Al implementar este requisito, estoy más cerca de cumplir el objetivo y satisfacer la necesidad del socio? Si la respuesta es 'no' reevaluar el requisito y quitar de la lista. Si la respuesta es 'si' continuar con el análisis. También es necesario analizar si el requisito tiene conflictos con otro, si este requisito impide cumplir a otro o viceversa entonces es necesario reevaluar ambos para poder cumplir con el objetivo.

## Salidas

  * Lista de requisitos para la solución del proyecto.

## Enlaces

[Reunión Stakeholders](https://github.com/Solify-IT/docs/wiki/P2-Realizar-juntas-con-socios-formadores)

**Comment by A01702321** [comment]
Aqui agrego el analisis de incosistencias al proceso de gestion de requisitos.

**Comment by Topi99** [comment]
Hay conflictos con #42. Habla con @albertcastaned para solucionarlos.

**Comment by albertcastaned** [comment]
Este proceso sera eliminado junto con P9 para combinarse en el P10 y P20. Se cerrará el issue.
