### ISSUE TITLE
Editar P7 Planificar iteración

### ISSUE THREAD

**Issue by A01702321** [Solify-IT/docs#52]
## Objetivos

  * Establecer y mantener planes que definan las actividades de la iteración

## Involucrados
  * Team members
  * Product Owner
  * Architecture Owner
  * Team Leader
  * Planning Owner (si aplica)

## Entradas
  * Ítems de trabajo

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Práctica del CMMI</th>
    </tr>
  </thead>
  <tbody>
<tr>
      <td>Pre-planificación</td>
      <td>Revisar los planes que afectan al proyecto</td>
      <td>PO, TM, AO</td>
      <td>PP 3.1</td>
    </tr>
   <tr>
      <td>Retroalimentación</td>
      <td>Tomar en cuenta el documento de lecciones aprendidas de la iteración anterior, para la nueva planeación.</td>
      <td>Todos los miembros del equipo</td>
      <td>PP 2.1</td>
    </tr>
    <tr>
      <td>Disponibilidad de Equipo</td>
      <td>Compartir la cantidad de horas disponibles para trabajar en el proyecto.</td>
      <td>Miembro del departamento involucrado</td>
      <td>PP 2.4</td>
    </tr>
    <tr>
      <td rowspan=8>Definición de Elemento de Trabajo</td>
      <td>Seleccionar un elemento de trabajo.</td>
      <td>Product Owner</td>
      <td> RD, TS </td>
   </tr>
      <tr>
	      <td>Obtener los detalles del elemento de trabajo.</td>
	      <td>Product Owner</td>
	      <td>PP 2.1</td>
	   </tr>
      <tr>
	      <td>Realizar proceso de <a href="https://github.com/Solify-IT/docs/wiki/P20-Gestionar-requerimientos">Gestión de Requisitos</a></td>
	      <td>Product Owner</td>
	      <td>REQM</td>
	   </tr>
    <tr>
      <td>Modelar una solución potencial.</td>
      <td>Miembros del equipo</td>
      <td> TS </td>
   </tr>
    <tr>
      <td>Descomponer el elemento de trabajo en tareas.</td>
      <td>Miembros del equipo</td>
      <td>PP 1.1</td>
   </tr>
    <tr>
      <td>Asignar responsable del cumplimiento del elemento de trabajo</td>
      <td>Miembros del equipo</td>
      <td>PP 3.3, PMC 1.2 RM 1.2</td>
   </tr>
    <tr>
      <td>Agregar elemento de trabajo a la pila de tareas</td>
      <td>Miembros del equipo</td>
      <td></td>
   </tr>
    <tr>
      <td>Actualización de la estimación.</td>
      <td>Miembro del departamento involucrado</td>
      <td>PP 1.4</td>
   </tr>
   <tr>
    <td rowspan=3>Sanity Check</td>
    <td>Revisar la sensatez del plan (sanity check).</td>
    <td>Miembros del equipo</td>
    <td>PMC 1.1, PMC 1.3</td>
  </tr>
    <tr>
      <td>Asignar de manera voluntaria una tarea a cada miembro para ser encargados de desarrollarla</td>
      <td>Miembro del departamento involucrado</td>
      <td>PP 3.3, PMC 1.2 RM 1.2</td>
   </tr>
    <tr>
      <td>Verificar si los miembros del equipo se compromenten a completar sus tareas.</td>
      <td>Team Leader</td>
      <td>PP 3.3</td>
   </tr>
  </tbody>
</table>

## Salidas

  * Plan de la iteración
  * Pila de tareas
  * Sanity check

**Comment by A01702321** [comment]
Agregar realizar proceso de Gestión de Requisitos

**Comment by Topi99** [comment]
¿Ya validaste este proceso en con alguien de la comunidad de práctica?
