### ISSUE TITLE
PIP P19: Institucionalizar Proceso

### ISSUE THREAD

**Issue by scarlosro** [Solify-IT/docs#53]
## Objetivos

- Institucionalizar un proceso dentro de la wiki de Solify
- Monitorear la corrección y estado de los procesos de la wiki

## Involucrados
- Autor
- Evaluador

## Entradas
-  Propuesta de proceso o PIP

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Práctica del CMMI</th>
    </tr>
  </thead>
  <tbody>
<tr>
      <td rowspan=3>Propuesta</td>
      <td>Abre un nuevo issue en la wiki de Solify con el nombre del proceso identificado</td>
      <td>Autor</td>
      <td>OPD SP1.1</td>
    </tr>
    <tr>
      <td>Verifica que cumpla con el Check List para evaluar procesos y la plantilla publicada en la wiki. </td>
      <td>Autor</td>
      <td> OPD SP1.1, VER SP1.3</td>
    </tr>
    <tr>
      <td>Solicita la revisión para que realicen la revisión del nuevo proceso</td>
      <td >Autor</td>
      <td> OPD SP1.3 </td>
   </tr>
    <tr>
      <td rowspan=4>Análisis</td>
      <td>Lee detalladamente el proceso a evaluar</td>
      <td>Evaluador</td>
      <td>CM SP1.1, VER SP1.1</td>
    </tr>
    <tr>
      <td>Lee detalladamente la rúbrica de evaluación
      <td>Evaluador</td>
      <td> CM SP1.1, VER SP1.3</td>
    </tr>
    <tr>
      <td> Crea un documento con el nombre "Evaluación de procesos (número de evaluación) <fecha de evaluación></td>
      <td >Evaluador</td>
      <td> CM SP2.2, VER SP1.2</td>
   </tr>
 <tr>
      <td> Copia la rúbrica de evaluación al documento creado para cada proceso </td>
      <td >Evaluador</td>
      <td> CM SP2.2,  VER SP1.2</td>
   </tr>
    <tr>
      <td rowspan=4>Evaluación</td>
      <td>Revisa el contenido del proceso con cada criterio de evaluación de la rúbrica</td>
      <td>Evaluador</td>
      <td> PPQA SP1.1</td>
    </tr>
    <tr>
      <td>Si se identifica que está incorrecto, entonces marca la casilla "Cumple" con la opción "No" y la casilla "Estado" con la opción "Identificado"</td>
      <td>Evaluador</td>
      <td>PPQA SP1.1, PPQA SP1.2, VER SP3.1</td>
    </tr>
<tr>
      <td>Si se identifica que está incorrecto, entonces en la casilla "Comentarios" escribe las observaciones para su corrección</td>
      <td>Evaluador</td>
      <td>CM SP2.1, PPQA SP1.1, PPQA SP1.2, VER SP3.1</td>
    </tr>
<tr>
      <td>Documenta los resultados de la revisión de acuerdo con el Check List como un comentario del issue para su historial</td>
      <td>Evaluador</td>
      <td>PPQA SP2.2</td>
    </tr>
  <tr>
      <td rowspan=2>Comunicación</td>
      <td>Se Comunica al departamento por medio del canal de slack #solify-centro-de-notificaciones, de forma automática.</td>
      <td>Evaluador</td>
      <td> PPQA SP2.1</td>
    </tr>
    <tr>
      <td>En la junta de coordinación diaria se debe asignar a responsables de hacer las correcciones en los procesos</td>
      <td>Evaluador</td>
      <td>PPQA SP2.2, CM SP2.2, VER SP3.2</td>
    </tr>

  </tbody>
</table>

## Salidas

- Nuevo proceso implementado o corregido

## Referencias
* [Checklist para revisión de procesos](https://github.com/Solify-IT/docs/wiki/CL1---Revisión-de-procesos)
* [Plantilla para procesos](https://github.com/Solify-IT/docs/wiki/PL0---Plantilla-para-procesos)

**Comment by scarlosro** [comment]
Se cambia el nombre a Institucionalizar un proceso ya que hace mas referencia a el de evaluar procesos, además que incluimos el proceso inicial de esto, que es la persona que ha detectado o es el proponente de este proceso es que lo "licita" en la wiki para que sea en un determinado momento aprobado y utilizado en su área correspondiente.

**Comment by albertcastaned** [comment]
@scarlosro 
- La entrada podría cambiar a ser una propuesta de proceso o un PIP.
- La actividad 5.1 podría cambiar a ser el canal de slack #solify-centro-de-notificaciones. En este canal, se sube notificaciones de issues y sus cambios de forma automatizada.
- El error de HTML que menciono Topi.
-  El checklist para evaluar procesos  y la rúbrica de evaluación veo que es lo mismo. Creo que hacer un archivo nuevo para cada revisión seria muy tardado e innecesario. Creo que podríamos seguir manejando como que el evaluador ponga la checklist revisada en el issue. Este issue se quedará guardado aun cuando se cierre.
-

**Comment by scarlosro** [comment]
@Topi99 @albertcastaned de favor su revisión, se realizaron los cambios procedentes.

**Comment by albertcastaned** [comment]
👍

**Comment by Topi99** [comment]
LGTM :+1:
