### ISSUE TITLE
PIP: P023 Hacer un reporte de estado (agregar patrones y antipatrones)

### ISSUE THREAD

**Issue by ricardo-esc** [Solify-IT/docs#54]
<table>
<thead>
  <tr>
    <th>Etapa</th>
    <th>Actividad</th>
    <th>Encargado</th>
    <th>Práctica del CMMI</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td rowspan="2">Planeación</td>
    <td> 			Seleccionar a un miembro de cada equipo para ayudar en el desarrollo del reporte de estado a nivel departamento.   </td>
    <td>PM</td>
    <td rowspan="2"> 		M&amp;A 2.3, 2.4</td>
  </tr>
  <tr>
    <td>Delegar la distribución de tareas de la etapa de ejecución.</td>
    <td>TL</td>
  </tr>
  <tr>
    <td rowspan="7">Ejecución</td>
    <td>Analizar datos obtenidos de las métricas, comparando con resultados de análisis anteriores para observar tendencias y tomar nuevas decisiones. Con este análisis se busca responder a las preguntas clave: ¿Dónde estoy?, ¿Dónde debería estar?, ¿Cuánto me ha costado?, ¿Por qué estoy dónde estoy? y ¿Cómo está la calidad?</td>
    <td>PM, Cada equipo</td>
    <td rowspan="4">M&amp;A 2.2, 2.4, PMC 1.1</td>
  </tr>
  <tr>
    <td>Recuperar las métricas del plan de valor ganado de cada proyecto. </td>
    <td rowspan="4">Equipo</td>
  </tr>
  <tr>
    <td>Monitorear el progreso del proyecto con el valor planeado y el valor ganado acumulado a la fecha del reporte de estado..</td>
  </tr>
  <tr>
    <td>Monitorear el costo acumulado del proyecto a la fecha del reporte de estado.</td>
  </tr>
  <tr>
    <td>Registrar desviaciones significativas detectadas y las acciones correspondientes a su solucion en la bitacora de desviaciones del proyecto.</td>
    <td>PMC 2.1</td>
  </tr>
  <tr>
    <td>Presentar estado de respectivo proyecto al resto del departamento.</td>
    <td>PM, TL</td>
    <td>M&amp;A 2.2, 2.4, PMC 1.1</td>
  </tr>
  <tr>
    <td>Asignar a los presentadores que presenten el estado de otro proyecto para la etapa de presentación.</td>
    <td>Todo el departamento</td>
    <td>M&amp;A 2.2, 2.4, PMC 1.1</td>
  </tr>
    <tr>
  <td>Evaluación de la Forma de Trabajo</td>
   <td>Comparar la forma de trabajo con los patrones y antipatrones identificados de la fase correspondiente.</td>
    <td>Equipo</td>
    <td>PMC 1.6</td>
  </tr>
  <tr>
    <td rowspan="2">Presentación</td>
    <td>Presentar reporte a asesores para obtener retroalimentación.</td>
    <td>Presentadores</td>
    <td>M&amp;A 2.4</td>
  </tr>
  <tr>
    <td>Registrar retroalimentación obtenida de los asesores para atender para el siguiente reporte de estado.</td>
    <td>Todo el departamento</td>
    <td>SP 1.2</td>
  </tr>
</tbody>
</table>

**Comment by ricardo-esc** [comment]
Creo que falta un paso que diga como, poner todos los datos en la presentación o algo asi :)

**Comment by Topi99** [comment]
En el último paso de `Presentación`, el encargado debería ser el `Program Manager` en lugar de `Todo el departamento`.

**Comment by scarlosro** [comment]
Este issue ya lleva más de 9 días @ricardo-esc

**Comment by ricardo-esc** [comment]
https://github.com/Solify-IT/docs/wiki/P23-Hacer-un-reporte-de-estado
