### ISSUE TITLE
P23: Revisión explícita del progreso, problemas y desempeño de los equipos y proyectos

### ISSUE THREAD

**Issue by domerent97** [Solify-IT/docs#55]
<table>
<thead>
  <tr>
    <th>Etapa</th>
    <th>Actividad</th>
    <th>Encargado</th>
    <th>Práctica del CMMI</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td rowspan="2">Planeación</td>
    <td> 			Seleccionar a un miembro de cada equipo para ayudar en el desarrollo del reporte de estado a nivel departamento.   </td>
    <td>PM</td>
    <td rowspan="2"> 		M&amp;A 2.3, 2.4</td>
  </tr>
  <tr>
    <td>Delegar la distribución de tareas de la etapa de ejecución.</td>
    <td>TL</td>
  </tr>
    <td rowspan="7">Ejecución</td>
    <td>Analizar datos obtenidos de las métricas, comparando con resultados de análisis anteriores para observar tendencias y tomar nuevas decisiones. Estos datos nos dan información del progreso, los problemas y el desempeño de los proyectos. Con este análisis y revisión se busca responder a las preguntas clave: ¿Dónde estoy?, ¿Dónde debería estar?, ¿Cuánto me ha costado?, ¿Por qué estoy dónde estoy?, ¿Cómo está la calidad? y ¿Cómo puedo mejorar?</td>
    <td>PM, Cada equipo</td>
    <td rowspan="4">M&amp;A 2.2, 2.4, PMC 1.1, PMC 1.6, PMC 1.7</td>
  </tr>
  <tr>
    <td>Recuperar las métricas del plan de valor ganado de cada proyecto. </td>
    <td rowspan="4">Equipo</td>
  </tr>
  <tr>
    <td>Monitorear el progreso del proyecto con el valor planeado y el valor ganado acumulado a la fecha del reporte de estado..</td>
  </tr>
  <tr>
    <td>Monitorear el costo acumulado del proyecto a la fecha del reporte de estado.</td>
  </tr>
  <tr>
    <td>Registrar desviaciones significativas detectadas y las acciones correspondientes a su solucion en la bitacora de desviaciones del proyecto.</td>
    <td>PMC 2.1</td>
  </tr>
  <tr>
    <td>Presentar estado de respectivo proyecto al resto del departamento.</td>
    <td>PM, TL</td>
    <td>M&amp;A 2.2, 2.4, PMC 1.1</td>
  </tr>
  <tr>
    <td>Asignar a los presentadores que presenten el estado de otro proyecto para la etapa de presentación.</td>
    <td>Todo el departamento</td>
    <td>M&amp;A 2.2, 2.4, PMC 1.1</td>
  </tr>
    <tr>
  <td>Evaluación de la Forma de Trabajo</td>
   <td>Comparar la forma de trabajo con los patrones y antipatrones identificados de la fase correspondiente.</td>
    <td>Equipo</td>
    <td>PMC 1.6</td>
  </tr>
  <tr>
    <td rowspan="2">Presentación</td>
    <td>Presentar reporte a asesores para obtener retroalimentación.</td>
    <td>Presentadores</td>
    <td>M&amp;A 2.4</td>
  </tr>
  <tr>
    <td>Registrar retroalimentación obtenida de los asesores para atender para el siguiente reporte de estado.</td>
    <td>Todo el departamento</td>
    <td>SP 1.2</td>
  </tr>
</tbody>
</table>

**Comment by albertcastaned** [comment]
¿Cuales son los cambios que se hace al proceso de reporte de estado?

**Comment by Topi99** [comment]
Revisa con @ricardo-esc porque los dos están editando el mismo proceso.

**Comment by domerent97** [comment]
> ¿Cuales son los cambios que se hace al proceso de reporte de estado?

En el paso, _Analizar datos obtenidos de las métricas, comparando con resultados de análisis anteriores para observar tendencias y tomar nuevas decisiones. Estos datos nos dan información del progreso, los problemas y el desempeño de los proyectos. Con este análisis y revisión se busca responder a las preguntas clave: ¿Dónde estoy?, ¿Dónde debería estar?, ¿Cuánto me ha costado?, ¿Por qué estoy dónde estoy? y ¿Cómo está la calidad?_ Se le agregó la parte de _progreso, los problemas y el desempeño de los proyectos_ para hacerlo de manera explícita.

También se le agregó las áreas de PMC 1.6 y PMC 1.7

**Comment by domerent97** [comment]
> Revisa con @ricardo-esc porque los dos están editando el mismo proceso.

¡Ok! Me pongo de acuerdo con él :)

**Comment by Topi99** [comment]
¿Nos puedes avisar cuando ya esté listo el proceso? Por favoe

**Comment by scarlosro** [comment]
@domerent97 ¿Aún no está listo?
