### ISSUE TITLE
G18 Gestión de métricas de defectos

### ISSUE THREAD

**Issue by JuanCarlosCV** [Solify-IT/docs#56]
# Gestión de métricas de defectos

## Objetivos

* Profundizar en el uso de la hoja de monitoreo de defectos.

## Ubicación

La hoja de monitoreo de defectos se puede encontrar en el repositorio de métricas de cada equipo en la pestaña de "Bitácora de defectos" (ver [sección de enlaces](https://hackmd.io/k4OEdlXRQ76oH0Wpb2ezFQ?both#Enlaces)).

## Tipos de defectos detectables

* **Error de ortografía**: este tipo de defecto ocurre cuando existen faltas de ortografía que se vean reflejados en las interfaces del sistema.
* **Nombres**: este defecto se manifiesta como un nombre poco descriptivo o poco apropiado para elementos como columnas de tablas, archivos, etc.
* **Estándares**: cuando en el código no se está siguiendo alguna regla establecida por los estándares de codificación establecidos, se manifiesta un defecto de deste tipo,
* **Llamadas**: este tipo de defectos son reconocibles por las llamadas del sistema como errores o advertencias.
* **Arquitectura**: este tipo de defectos ocurren cuando no se está respetando la arquitectura establecida (arquitectura limpia).
* **Estilos**: este tipo de defectos ocurren cuando hay inconsistencias en el uso de aspectos como colores, tipos de letra o tamaños en las interfaces del sistema.
* **Otros**: comentarios innecesarios, líneas innecesarias, cualquier defecto que no encaje en las demás categorías.

## Bitácora de defectos

**Etapas de inyección y de detección**: estas se refieren al punto durante el desarrollo del proyecto en el cuál se metieron los defectos en el código y a cuándo fueron detectados, respectivamente. En la bitácora de defectos debe hacerse explícito qué miembro del equipo detectó cada tipo de defecto.

**Fecha de identificación y de resolución**: al detectar un defecto, este debe ser agregado a la bitácora junto con la fecha del día actual (el día en que se detectó). Se debe notificar al equipo y acordar quién lo resolverá.

**Resolución del defecto**: Una vez que se haya resuelto el defecto, en la bitácora debe anotarse el tiempo que tomó resolverlo en la columna apropiada. Finalmente, en las últimas dos columnas se deberá especificar al miembro del equipo que detectó el defecto, y quién lo resolvió, respectivamente.

## Jerarquía para resolución de defectos

La columna de "Severidad" en la bitácora de defectos se utiliza para categorizar el defecto con respecto al impacto que este tiene sobre el sistema. Existen cuatro [categorías de severidad definidas por IBM](https://www.ibm.com/support/pages/what-are-severity-levels-and-how-do-i-know-which-one-use):

1. El sistema deja de funcionar
2. Funcionalidades mayores deshabilitadas o incorrectas
3. Problema menor
4. Error cosmético sin impacto en la operación

Los defectos identificados deberán ser atendidos según su clasificación de severidad, comenzando por los de nivel de severidad 1, luego por el 2 y así sucesivamente.

## Enlaces

* [Repositorio de métricas Team Rocket](https://docs.google.com/spreadsheets/d/1x022IPg3fytUQ_NxFjkgHFoTU2oBt1hXvNUFo9ZFTHs/edit#gid=0)
* [Repositorio de métricas Soolers](https://docs.google.com/spreadsheets/d/1MVEE5b19y5CxzQJxFSf31RyKIn8mhyHfYt4_y15_M5A/edit#gid=616715226)

**Comment by Topi99** [comment]
Estaría bien que se mencionara como analizar estas métricas, para tener criterios de análisis y tomar mejores decisiones. Puedes hablar con @scarlosro, él está muy enterado sobre eso.

**Comment by albertcastaned** [comment]
Lo veo bien. Una sugerencia podría ser agregar una columna de "severidad" que indique la categoría de severidad del defecto para poder priorizar la resolución de los mismos. Actualmente estamos utilizando las siguientes categorías en el equipo Soolers (basadas en nivel de severidad IBM):

**Comment by LaloGlzMlz** [comment]
Buena recomendación, se la puedo agregar yo.

**Comment by Topi99** [comment]
> Buena recomendación, se la puedo agregar yo.

¡Gracias!

**Comment by LaloGlzMlz** [comment]
Cómo lo ven ahora? @albertcastaned @Topi99

**Comment by albertcastaned** [comment]
Lo veo bien

**Comment by Topi99** [comment]
LGTM

**Comment by Topi99** [comment]
¿Pueden agregar el enlace en el repo de métricas en la columna de toma de decisiones?
