### ISSUE TITLE
P##: Identificar necesidades del cliente.

### ISSUE THREAD

**Issue by scarlosro** [Solify-IT/docs#57]
## Objetivos

  * Conocer a nuestros clientes y su forma de trabajo para poder analizar la información e identificar las necesidades.

## Involucrados
  * Clientes
  * Equipo de desarrollo

## Entradas

  * Proyecto

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Práctica del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan=3>Planificación</td>
      <td>Agenda reunión con clientes para identificación de necesidades. Agenda de acuerdo con  la Guía de Calendario.</td>
      <td>PO</td>
      <td> PP 3.3, PMC 1.5</td>
    </tr>
    <tr>
      <td>Investiga previo a la junto acerca de los clientes para tener una base de conocimiento y realiza una tormenta de idea para rescatar ideas principales y proponer preguntas. Los criterios serán ubicar aquellas actividades o procesos que les cuesta y genera afectación para el desarrollo de otras actividades. </td>
      <td>Cada uno</td>
      <td>PMC 1.5, PP 2.5</td>
    </tr>
    <tr>
        <td>Realiza la agenda de la junta</td>
        <td>PO, TL, AO</td>
        <td> PP 2.6</td>
      </tr>
    <tr>
      <td rowspan=3>Junta</td>
      <td>Presenta la agenda de la reunión así como especifica el propósito. </td>
      <td> TL </td>
      <td> PP 2.6 </td>
    </tr>
    <tr>
      <td>Escucha la forma de trabajo del cliente e identifica las necesidades o ideas importantes y pregunta dudas al final.</td>
      <td>Team member</td>
      <td>RD 1.1, PP 3.3/td>
    </tr>
    <tr>
      <td>Documenta en la minuta del día</td>
      <td>Team member</td>
      <td>RD 1.1, CM1 1.3</td>
    </tr>
    <tr>
      <td rowspan=3>Análisis</td>
      <td>Lee la minuta completa y comenta en la reunión de análisis</td>
      <td> Team member </td>
      <td> RD 1.1</td>
    </tr>
    <tr>
      <td>Realiza una tormenta de ideas sobre las necesidades y dialoga sobre ellas</td>
      <td>Team member</td>
      <td>RD 1.1, REQM 1.5</td>
    </tr>
    <tr>
      <td>Documenta las necesidades en estrategia inicial</td>
      <td>PO</td>
      <td>RD 1.1, </td>
   </tr>

  </tbody>
</table>

## Salidas

  * Lista de necesidades del stakeholder

## Enlaces
  * [Guía de Calendario](https://github.com/Solify-IT/docs/wiki/G1-Uso-de-Calendario-de-Solify)

## Cambios

- <fecha de creación en 25/05/2021> - Se define el proceso.

**Comment by Topi99** [comment]
Hay que definir si las actividades van a tener un identificador o no. Creo solo un par de procesos los tienen.

**Comment by Topi99** [comment]
Aparte de mi comentario, LGTM.

**Comment by albertcastaned** [comment]
Se podria cambiar el nombre de la salida para que coincida con la entrada del [proceso P20](https://github.com/Solify-IT/docs/wiki/P20-Gestionar-requerimientos)

**Comment by scarlosro** [comment]
@Topi99 @albertcastaned Listo para su revisión nuevamente

**Comment by albertcastaned** [comment]
No lo puse en mi comentario anterior pero viéndolo bien el paso 1.2 creo que podría ser mucho más detallado para contestar el cómo se identifica, qué criterios se utilizan, etc.

**Comment by Topi99** [comment]
Igual podemos sustituir `cada uno` por `Team Members`.

**Comment by Topi99** [comment]
Aparte de eso y el comentario de @albertcastaned, LGTM

**Comment by scarlosro** [comment]
Listo

**Comment by arcosmarce** [comment]
Super! Después de todas las correcciones

**Comment by arcosmarce** [comment]
Estaría bien si agregas la guía del calendario en el primer paso

**Comment by scarlosro** [comment]
Listo @arcosmarce su VOBO para pasarlo ya a la wiki.

**Comment by arcosmarce** [comment]
Listo

**Comment by Topi99** [comment]
¿Ya está en la Wiki?

**Comment by scarlosro** [comment]
La paso
