### ISSUE TITLE
G17 Guía para monitorear y analizar la forma de trabajo

### ISSUE THREAD

**Issue by A01702321** [Solify-IT/docs#58]
# G17 Guía para monitorear y analizar la forma de trabajo

## Descripción
Esta guía busca explicar cómo llevar el monitoreo y el análisis de la forma de trabajo actual.

## Objetivos
* Explicar la manera de llevar monitoreo de la forma de trabajo.
* Explicar como llevar el análisis de los resultados de la forma de trabajo.

### Cambios en la forma de trabajo (WoW)

Para llevar el monitoreo de la forma de trabajo es importante tener un registro de los cambios que se hacen a la forma de trabajo. No es fácil llevar monitoreo de la forma de trabajo si no se lleva un registro físico. En el documento de [Repositorio de Métricas](https://docs.google.com/spreadsheets/d/1ZEUXSo0LrmqnJTHx2xrcmL-rcAsgTSesZFuTCGmkGBE/edit#gid=358377326) del departamento, en la pestaña: historial de propuestas de WoW se anotan las propuestas de cambios para la forma de trabajo al igual que una fecha donde se pueda hacer el análisis de resultados. 
Al llegar la fecha de análisis se deben anotar resultados que se puedan observar por el cambio en la forma de trabajo. Estos resultados deben ser objetivos y deben de mostrar datos en los que se puedan ver resultados ya sean positivos o negativos para la propuesta dada anteriormente y así poder tomar decisiones con base en ellos.

### Evaluación de la propuesta

Para analizar los resultados de la propuesta de cambio, deben ya estar establecidas las métricas con las que se pueda llegar a una conclusión y tomar acciones. En caso de no tener suficientes datos para llegar a una conclusión se puede extender la fecha para seguir probando la forma de trabajo y poder conseguir ya suficientes datos.
Si los resultados obtenidos muestran un cambio positivo o negativo en áreas como productividad, eficiencia, estado de animo, etc. planteados en la hipótesis del cambio se puede tomar acción al respecto. Se evaluará la propuesta, si los resultados muestran cambios positivos se tomará la acción de mantener esa forma de trabajo en el departamento o equipo. Si los resultados son negativos entonces se debe tomar al decisión de regresar a la forma de trabajo anterior o sugerir una nueva que pueda mostrar resultados positivos. 
La conclusión a la que se haya llegado, debe ser también anotada en el [Repositorio de Métricas](https://docs.google.com/spreadsheets/d/1ZEUXSo0LrmqnJTHx2xrcmL-rcAsgTSesZFuTCGmkGBE/edit#gid=358377326), en la columna de Aceptada/Negada. 

## Pila de cambios

- 25/05/2021 - Se crea la guía.

**Comment by Topi99** [comment]
LGTM. Cuando la agregues a la Wiki, también recuerda agregarla a los criterios de análisis del repo de métricas.
