### ISSUE TITLE
P4 Reportar falta al código de ética

### ISSUE THREAD

**Issue by JavierIQ** [Solify-IT/docs#60]
## Objetivos

  * Dar a conocer al comité de ética una falta al código
  * Recibir protección durante el proceso de la denuncia
  * Ver por la integridad del departamento Solify

## Involucrados
  * Afectados
  * Comité de ética

## Entradas

  * Dilema ético

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Área del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan=2>Generar Reporte</td>
      <td>Identificar el problema e involucrados.</td>
      <td>Resopnsable del reporte</td>
      <td>RSKM 2.1</td>
    </tr>
    <tr>
      <td>Escribir la problemática; debe ser puntual y lo más específica posible.</td>
      <td>Resopnsable del reporte</td>
      <td>RSKM 2.2</td>
    </tr>
    <tr>
      <td rowspan=3>Crear denuncia</td>>
      <td>En Slack, en el canal #solify-denuncias se debe postear el reporte. Se puede hacer de manera anónima. </td>
      <td>Resopnsable del reporte</td>
      <td rowspan=2>RSKM 3.1</td>
      </tr>
    <tr>
      <td>Firmar o no la denuncia. El reporte puede ir o no firmado. En caso de estar firmado, el comité se comunicará lo antes posible para confirmar de recibido. De otra forma, se recibirá la denuncia anónima y se trabajará como tal. No se enviará mensaje de confirmación. </td>
      <td>Resopnsable del reporte</td>
    </tr>
       <tr>
      <td>Asistir al comité de ética en la manera que sea solicitada. El comité de ética puede pedir ayuda, más opiniones o incluso testimonios para llevar a cabo el seguimiento de la problemática. </td>
      <td>Resopnsable del reporte</td>
      <td>RSKM 3.2</td>
    </tr>
  </tbody>
</table>

## Salidas

  * Reporte de una denuncia
  * Acciones correctivas de parte del comité de ética

## Referencias

  * [Código de Ética del departamento Solify](https://drive.google.com/file/d/1c7z5rHN5rwLAT8tL74jsHMQQBJlrXi3e/view?usp=sharing)

**Comment by scarlosro** [comment]
Está bien, solo borra el ">" antes de la tabla.

**Comment by scarlosro** [comment]
@JavierIQ Hay que hacer la corrección e integrar a la wiki
