### ISSUE TITLE
P15 Programar en parejas

### ISSUE THREAD

**Issue by A01702321** [Solify-IT/docs#61]
## Objetivos

  * Facilitar la transmisión de habilidades, conocimientos y técnicas.
  * Mejorar la calidad del código.

## Involucrados
  * Team Members

## Entradas

  * User Story a desarrollar

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Práctica del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
     <td rowspan=2> Análisis </td>
     <td> Platica en pareja sobre la posible solución a la historia de usuario </td>
     <td> Team Members </td>
     <td> PP 2.5, TS 1.1 </td>
    </tr>
    <tr>
     <td> Define el algoritmo y validar que la solución sea correcta </td>
     <td> Team Members </td>
     <td> TS 1.1 </td>
    </tr>
    <tr>
     <td rowspan=5> Ejecución </td>
     <td> Un miembro del equipo comienza con la programación, el otro dicta lo que se espera del código y revisa lo que se programa. </td>
     <td> Team Member</td>
     <td> TS 3.1 </td>
    </tr>
     <tr>
     <td> El programador narra lo que va realizando.</td>
     <td> Team Member</td>
     <td> TS 3.1  </td>
    </tr>
    <tr>
     <td> El otro integrante utilizando la <a href="https://github.com/Solify-IT/docs/wiki/Checklist-de-c%C3%B3digo-departamental">Checklist de revisión de código</a> revisa el código para evitar la inyección de defectos. </td>
     <td> Team Member</td>
     <td> PPQA 1.2, TS 3.1, VER 2.1 </td>
    </tr>
  <tr>
     <td> En caso de encontrar un defecto, éste se puede arreglar en el instante que es encontrado y continuar programando. 
    </td>
     <td> Team Member</td>
     <td> PPQA 2.2, VER 2.1, VAL 2.1  </td>
    </tr>
   <tr>
     <td> El miembro que revisa registra el defecto en el defect log como inyectado en la fase de desarrollo. 
    </td>
     <td> Team Member</td>
     <td> VER 2.1, VAL 1.3  </td>
    </tr>
    <tr>
     <td> Rotación </td>
     <td> Después de un tiempo, los roles se intercambian y el miembro que no había programado ahora programa y el otro hace la revisión. </td>
     <td> Team Member</td>
     <td> PP 2.5, TS 3.1 </td>
    </tr>

  </tbody>
</table>

## Salidas

  * Funcionalidad completa de la Hisotria de Usuario (Código)
  * Pruebas
  * Defect log actualizado 

## Referencias
* [Guia para el manejo del tiempo de desarrollo](https://github.com/Solify-IT/docs/wiki/G19-Guia-para-el-manejo-del-tiempo-de-desarrollo)
* [Tuple's pair Programming Guide](https://tuple.app/pair-programming-guide)

**Comment by A01702321** [comment]
Hice pequeños cambios y agregue la checklist de revisión de código.

**Comment by Topi99** [comment]
¿Puedes cambiar los verbos a conjuntivo? `Platicar en pareja` -> `Platica en pareja`.

**Comment by scarlosro** [comment]
También hay que especificar que aunque el defecto se detecto en la misma fase de inyección hay que documentarlo en el defect log.

**Comment by albertcastaned** [comment]
Me gusto esta guia de internet sobre pair programming. En especial la parte de anti patrones. Yo creo que podemos ponerla aqui como referencia. 

https://tuple.app/pair-programming-guide

**Comment by albertcastaned** [comment]
Agregue la guia G19 de Pomodoro que teniamos en Soolers a nivel departamento para poder agregarlo como link a este proceso.
