### ISSUE TITLE
Home page: Agregar Herramientas de trabajo, lecturas y editar forma de trabajo

### ISSUE THREAD

**Issue by domerent97** [Solify-IT/docs#62]
¡Bienvenido al Wiki del departamento Solify!

En este sitio podrás encontrar documentación importante acerca de nuestras políticas, procesos, guías y plantillas.

Para poder navegar rápidamente, al lado derecho encontrarás nuestro menú con todos los enlaces a las páginas importantes.

[Wiki de Equipo Soolers](https://github.com/Solify-IT/psyche/wiki)

[Wiki de Equipo Rocket](https://github.com/Solify-IT/snorlax/wiki)

## Misión
Implementar soluciones informáticas que faciliten e impulsen el desarrollo de organizaciones que impactan positivamente en la sociedad.

## Visión
Formar una comunidad de ingenieros felices 
que sea un ejemplo para la industria del software, 
desarrollando productos a través de procesos 
y estándares de calidad competitivos a nivel internacional.

## Objetivos
1. Crear dos soluciones que deleiten a los clientes en tiempo, costo y alcance para Junio 2021.

2. Formar un ambiente de trabajo que propicie motivación y confianza en el departamento.

3. Consolidar Solify como un departamento de tecnologías de la información con un nivel de madurez 3 en CMMI. 

#### Sociabilidad
Sabemos bien que es importante mantener una buena relación
entre los miembros del equipo, de modo que se pueda trabajar en
ambiente de confianza y armonía. Lo que obviamente impactaría de
forma positiva en el desarrollo del proyecto.

#### Perseverancia
Nos ayudará a mantener la actitud y ese esfuerzo continuo que nos
llevará a cumplir nuestras metas y propósitos. Así como también en
la búsqueda de soluciones para salir de las situaciones complicadas
a las que nos podamos enfrentar.

#### Responsabilidad
Quizá una de las virtudes más valoradas ya que mediante ella cada
uno de los miembros del equipo asumirá el compromiso para
responder ante las tareas que le sean asignadas, y por muy grande o
pequeña que ésta parezca, siempre será importante cumplir ya que
de esto dependerá el éxito del proyecto.

#### Calidad
Esto involucra aquel nivel de compromiso para obtener un buen
rendimiento y así cumplir con las necesidades de nuestro cliente.

#### Comprensión
Al ser este un nuevo modo de trabajo y siendo conscientes de que la
situación de cada uno de nosotros es diferente, tenemos el
compromiso de escuchar, ser pacientes y ponernos en el lugar de la
persona.

## Nuestra Forma de Trabajo
En Solify aprovechamos todo lo mejor de la gente, de nuestros procesos y de la tecnología para llevar a cabo nuestros proyectos. Cuando iniciamos un proyecto nuevo, hacemos uso de uno de los ciclos de vida mencionados en [G17 Ciclo de Vida del Proyecto](https://github.com/Solify-IT/docs/wiki/G17-Ciclo-de-Vida-del-Proyecto).

## Nuestras Herramientas de Trabajo
En Solify, hacemos uso de las siguientes herramientas para el desarrollo de los proyectos:

- Git
- Zoom
- Discord
- Miro
- Google Drive

## Lecturas 

Las 2 lecturas indispensables para el departamento Solify son:
- [CMMI for Development 1.3](https://resources.sei.cmu.edu/asset_files/TechnicalReport/2010_005_001_15287.pdf)
- [Choose your WoW!](https://www.amazon.com/Choose-your-WoW-Disciplined-Optimizing-ebook/dp/B087CF2D97) de Mark Lines and Scott Ambler

**Comment by albertcastaned** [comment]
Lo veo bien. A lo mejor agregaria un link a cada herramienta como de invitación por si alguien nuevo llega.
