### ISSUE TITLE
P## Llevar a cabo retrospectiva de iteración

### ISSUE THREAD

**Issue by LaloGlzMlz** [Solify-IT/docs#64]
# P## Llevar a cabo retrospectiva de iteración

## Objetivos

  * Reflexionar sobre las decisiones y acciones que se llevarno a cabo durante la iteración terminando.
  * Tomar decisiones que ayudarán a optimizar el trabajo durante la iteración iniciando.

## Involucrados
* Team Leader
* Product Owner
* Architecture Owner
* Team members

## Entradas

  * Iteración actual terminada

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Práctica del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan=5>Preparación</td>
      <td>Todo el equipo de desarrollo debe reunirse en una sesión de Zoom o Discord que permita compartir pantalla.</td>
      <td rowspan=5>Team Leader</td>
      <td rowspan=8>CAR1.1, CAR2.2</td>
    </tr>
    <tr>
      <td>Como team leader, entra a <a href=https://easyretro.io>Easy Retro</a> y haz click en "Get started for free". Posteriormente elige el plan gratuito para crear un nuevo dashboard de retrospectiva.</td>
    </tr>
    <tr>
      <td>Una vez dentro del dashboard, haz click en "Add board". Nombra al nuevo board "Retrospectiva Iteración #" y reemplaza # con el numero al que corresponde la iteración que el equipo viene de terminar. </td>
    </tr>
    <tr></tr>
    <tr>
      <td>Crea cuatro columnas y llámalas "Start", "Stop", "Continue" y "Kudos", respectivamente. En las opciones en la parte inferior selecciona todas las casillas excepto la última que dice "Show card author". Termina haciendo click en "Create".</td>
    </tr>
    <tr>
        <td rowspan=3>Ejecución</td>
        <td>Inicia un timer de 3 minutos</td>
        <td>Team Leader</td>
    </tr>
    <tr>
        <td>En silencio y sin compartir pantalla, todo el equipo deberá utilizar el tiempo del timer para agregar la mayor cantidad de tarjetas posibles a la columna de "Start". Cada tarjeta que se agregue debe contener ideas de actividades o prácticas que cada quién considere que se deberían comenzar a hacer iniciando la siguiente iteración. Las tarjetas que cada quien agregue deberían aparecer ocultas para los demás.</td>
        <td rowspan=2>Team Leader, Product Owner, Architecture Owner, Team Members</td>
    </tr>
    <tr>
        <td>Repetir las dos actividades anteriores para llenar el resto de las columnas del board. La columna "Stop" se debe llenar con actividades o prácticas que cada quién considere que se deban dejar de hacer para la siguiente iteración, mientras que la columna de "Continue" con actividades o prácitcas que deban continuarse ejecutando para la siguiente iteración. La columna de Kudos está dedicada a hacer menciones y reconocimientos a prácticas, actividades, miembros o actitudes de la iteración terminando.</td>
    </tr>
<tr>
    <td rowspan=3>Revisión</td>
    <td>En la sección de ajustes (el engrane en la esquina superior derecha) desselecciona la opción de "hide cards" para revelar a todos las tarjetas que cada quien haya creado.</td>
    <td rowspan=3>Team Leader</td>
    <td rowspan=3>CAR1.2</td>
</tr>
<tr>
    <td>Comparte pantalla para que entre todos repasen cada tarjeta de cada columna. Siempre que dos tarjetas de una misma columna traten del mismo tema, mézclalas (merge) arrastrando una encima de la otra. Es posible mezclar tarjetas con mezclas de tarjetas existentes. </td>
</tr>
<tr>
    <td>Inicia un timer de 3 minutos, entre todos aprovechen este tiempo para votar por las cinco tarjetas (o mezclas de tarjetas) más importantes sin importar la columna en la que se encuentren a excepción de la de "Kudos". Para votar, desselecciona la opción de disable voting para revelar el botón de votar.</td>
</tr>
<tr>
    <td rowspan=2>Decisiones</td>
    <td>Entre todo el equipo, revisen cuáles tarjetas fueron las más votadas. Con respecto a ellas, dependiendo de su naturaleza, creen elementos de trabajo o tareas que las satisfagan durante la siguiente iteración.</td>
    <td>Team Leader, Product Owner, Architecture Owner, Team Members</td>
    <td>CAR2.1, CAR2.3</td>
</tr>
<tr>
    <td>Asignen responsables a cada tarea generada de esta manera.</td>
    <td>Team Leader</td>
    <td>RM1.2</td>
</tr>
  </tbody>
</table>

## Salidas

  * Elementos de trabajo para la siguiente iteración
  * Tablero de retrospectiva completado

## Enlaces

  * [Easy Retro](https://easyretro.io)

## Cambios

* 31/05/2021 - Se define el proceso.

**Comment by scarlosro** [comment]
En la retrospectiva también hay que hacer referencia a que se toman decisiones con base en las métricas las cuales también forman parte de las hipótesis que se realizan para mejorar la forma de trabajo.

**Comment by albertcastaned** [comment]
Si puedes checa la área de CAR. Va fuertemente asociada a la área.

**Comment by LaloGlzMlz** [comment]
Listo 👍🏼
