### ISSUE TITLE
G20 Recolección de habilidades

### ISSUE THREAD

**Issue by ricardo-esc** [Solify-IT/docs#65]
## Objetivo 
1. Recolectar información sobre las capacidades y habilidades del equipo.

## Introducción a GitHub Discussions
GitHub Discussions es un foro de comunicación colaborativa que nos permite tener diálogos transparentes y accesibles entre el equipo, sin necesidad de ser rastreadas en el tablero de un proyecto. 
Las discusiones brindan un espacio en dónde la información estará centralizada y será de fácil acceso.

## Guía rápida 
Para crear una nueva discusión:

1. En GitHub, dirígete a la página principal del repositorio.

2. Dar click en *Discussions*.

3. Seleccionar *New discussion*.

4. Elige alguna categoría para la nueva discusión.

5. Escribe el título y el contenido para la discusión.

6. Por último, click en *Start discussion*.

**Comment by Topi99** [comment]
Igual estaría bien que se mencionara en `Guía rápida` sobre qué escribir en la discusión. Tal vez podemos poner un ejemplo.

**Comment by domerent97** [comment]
¡Lo veo muy bien! Creo que podemos agregar un hyperlink en el punto 2 para llevarlos a https://github.com/Solify-IT/docs/discussions :)
