### ISSUE TITLE
P14 Monitorear Riesgos

### ISSUE THREAD

**Issue by JavierIQ** [Solify-IT/docs#66]
## Objetivos

  * Validar la situación de los riesgos y su estado actual.
  * Semanalmente, actualizar los datos y métricas de los riegos, documentar los nuevos riesgos identificados y quitar aquellos que han sido eliminados totalmente.

## Involucrados
  * Equipo del proyecto.
 
## Entradas

  * Proyecto
  * Matriz de riesgos

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Práctica del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan=4>Seguimiento de riesgos</td>
      <td>1.1 Dar a conocer los riesgos que han sucedido, su estado actual y resultados.</td>
      <td>Miembro</td>
      <td>MA 2.4 PMC 1.3</td>
    </tr>
    <tr>
      <td>1.2 Identificar los riesgos nuevos y eliminados de acuerdo con la discusión.</td>
      <td>Miembro</td>
      <td> PMC 1.3 PMC 1.7 PMC 2.2 RSKM 2.2 RSKM 3.1 RSKM 3.2</td>
    </tr>
    <tr>
      <td>1.3 Revaluación de los riesgos restantes para verificar su prioridad y probabilidad, así como su seguimiento.</td>
      <td>Miembro</td>
      <td>PMC 1.7 PMC 2.2 RSKM 2.2 </td>
    </tr>
    <tr>
      <td>1.4 Actualizar y registrar los datos y métricas de acuerdo con la información obtenida en la discusión y elaborar el resumen del status global de acuerdo con los datos previos y actuales.</td>
      <td>Encargado</td>
      <td>MA 2.1MA 2.2MA 2.3MA 2.4, PMC 1.4</td>
    </tr>
    
  </tbody>
</table>

## Salidas

  * Matriz de riesgos actualizada.
  * Decisiones para la forma de trabajo

## Referencias
[G10 - Estructura y manejo de la unidad de Solify en Google Drive ](https://github.com/Solify-IT/docs/wiki/G10-Estructura-y-manejo-de-la-unidad-de-Solify-en-Google-Drive)

**Comment by Topi99** [comment]
¿Cuáles fueron los cambios realizados?

**Comment by Topi99** [comment]
También estaría bien que elimines los números de cada actividad, ya no se usan actualmente. Otra cosa, hay que cambiar la forma de los verbos a conjuntivo: `Actualizar y registrar los datos` -> `Actualiza y registra los datos`.

**Comment by scarlosro** [comment]
@JavierIQ Hay que hacer merge con el [P17 Plantear Matriz de Riesgos](https://github.com/Solify-IT/docs/wiki/P17:-Plantear-Matriz-de-Riesgos) de acuerdo con la retroalimentación del SCAMPI así estaría más completo el proceso y además de también poner las referencias a la guía y plantilla.

**Comment by scarlosro** [comment]
Se cierra el issue y me encargo yo.
