### ISSUE TITLE
PIP: Completar P10 y Eliminar P9 Y P20 

### ISSUE THREAD

**Issue by domerent97** [Solify-IT/docs#67]
# P10: Generar o alimentar una lista de historias de usuario

## Objetivos

  * Crear lista de historias de usuario priorizada

## Involucrados

- Product Owner
- Architecture Owner

## Entradas

  * Lista de necesidades del stakeholder

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Área del CMMI</th>
    </tr>
  </thead>
  <tbody>
     <tr>
    <td rowspan="3">Análisis</td>
    <td>Traduce las necesidades de las partes interesadas a requisitos.</td>
    <td>PO</td>
    <td rowspan="2">RD 1.1</td>
  </tr>
  <tr>
    <td>Define las restricciones de los requisitos con base en las reglas de negocio de los interesados y los atributos de calidad necesarios para el proyecto.</td>
    <td>PO, AO</td>
  </tr>
  <tr>
    <td>Evalúa los requisitos con base en <a href=https://github.com/Solify-IT/docs/wiki/CL4-Criterio-de-aceptación-para-lista-de-requisitos>los criterios establecidos para la aceptación de una lista de requisitos. </td>
    <td>PO</td>
    <td>RM 1.1</td>
  </tr>
 <tr>
    <td >Definición</td>
    <td>Redacta el requisito en formato de historia de usuario. Una historia de usuario está compuesta de 3 elementos importantes:
        <ul>
           <li><strong>¿Quién?</strong>: el usuario que realizará la acción.</li><li><strong>¿Qué?</strong>: la acción a realizarse, descripción de la funcionalidad en palabras del usuario.</li><li><strong>¿Por qué? o ¿para qué?</strong>: explicación de por qué es relevante la esta funcionalidad.</li>
        </ul>
        Ejemplo: <blockquote>Como creador de historias, quiero ver los likes a mis publicaciones más recientes para así saber qué le gusta más a mis lectores.</blockquote>
    </td>
    <td>PO</td>
    <td>RD 1.2</td>
  </tr>
 <tr>
    <td >Priorización</td>
    <td>Ordena las historias de usuario con base al valor que le aportarán al stakeholder.</td>
    <td>PO</td>
    <td>PP 1.4, PP 2.7</td>
  </tr>
 <tr>
    <td >Documentar</td>
    <td>Alimenta la matriz de trazabilidad con las nuevas historias de usuario priorizadas.</td>
    <td>PO</td>
    <td>RM 1.4</td>
  </tr>
  </tbody>
</table>

## Salidas

- Una lista de historias de usuario priorizada
- Matriz de trazabilidad actualizada

**Comment by Topi99** [comment]
Podemos mencionar (en una guía tal vez) cómo se debe redactar el requisito en formato de historia de usuario. Tal vez mencionar sus partes.

**Comment by Topi99** [comment]
Igual se deben cambiar la forma de los verbos: `Alimentar la matriz` -> `Alimenta la matriz`.

**Comment by Topi99** [comment]
Cuando se hagan esas correcciones, LGTM :+1:

**Comment by Topi99** [comment]
Voy a darle seguimiento a este proceso, ya que es de alta prioridad y está bloqueando a otros compañeros.

**Comment by Topi99** [comment]
Voy a darle seguimiento a este proceso, ya que es de alta prioridad y está bloqueando a otros compañeros.

**Comment by Topi99** [comment]
Correcciones fueron atendidas. Cerrando issue.
