### ISSUE TITLE
PIP P1 Definir forma de trabajo

### ISSUE THREAD

**Issue by scarlosro** [Solify-IT/docs#68]
## Objetivos

  * Adoptar prácticas que permitan lograr nuestros objetivos
  * Mejorar la forma de trabajo

## Involucrados
  * Miembros del equipo
 
## Entradas

  * Actividad/necesidad 
  * Área de oportunidad 

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Área del CMMI</th>
    </tr>
  </thead>
  <tbody>
  <tr>
  <td rowspan=2> Conocimiento de nuestras herramientas </td>
  <td> Conoce las políticas, mapa de procesos, procesos, guías y herramientas de la wiki del departamento. </td>
  <td> Team Member </td>
  <td> OPF 3.1 </td>
  </tr>
  <tr>
  <td> Pregunta dudas acerca de la información consultada anteriormente. </td>
  <td> Team Member </td>
  <td> OPF 3.1 </td>
  </tr>
  <tr>
  <td rowspan=5> Definición </td>
  <td> Define los objetivos del proyecto en puerta apegada a la misión del departamento. </td>
  <td> Team Member </td>
  <td> OPF 1.1 </td>
  </tr>
  <tr>
  <td> Define fechas y hora para juntas de planificación de iteración, coordinación, retrospectiva y  reporte de estado,monitoreo de riesgos y métricas. </td>
  <td> Team Member </td>
  <td> PP 2.5, PP 2.6,PP 2.7</td>
  </tr>
  <tr>
  <td> Toma decisiones con base en las métricas generadas día a día e implementa experimentos para mejorar la forma de trabajo. </td>
  <td> Team Leader </td>
  <td> OPF 3.3, MA 2.2, MA 2.3, MA 2.4  </td>
  </tr>
  <tr>
  <td> Mejora los procesos identificados a partir de las decisiones que han sido beneficas. </td>
  <td> Team Member </td>
  <td> OPF, 2.1, OPF 3.2,OPF 3.3,  </td>
  </tr>
  <tr>
  <td> Institucionaliza nuevos procesos importantes en la wiki. </td>
  <td> Team Member </td>
  <td> OPD 1.1 </td>
  </tr>
  </tbody>
</table>

## Salidas

  * Forma de trabajo y mejoras en la forma de trabajo
  * Procesos y/o mejoras en los procesos.

**Comment by Topi99** [comment]
> Toma decisiones con base en las métricas generadas día a día.

Podemos mencionar los PIPs aquí. Algo como esto:

```md
Toma decisiones con base en las métricas generadas día a día siempre con intenciones de mejorar la forma de trabajo.
```

**Comment by Topi99** [comment]
> Toma decisiones con base en las métricas generadas día a día.

Podemos mencionar los experimentos aquí. ¿Qué te parece esto?:

```md
```

**Comment by Topi99** [comment]
Aparte de eso, LGTM 💯

**Comment by Topi99** [comment]
> Define los objetivos del proyecto en puerta apegada a la misión del departamento.

Esto es OPF 1.1

**Comment by scarlosro** [comment]
Listo, ahorita lo paso
