### ISSUE TITLE
P##: Realizar SCAMPI

### ISSUE THREAD

**Issue by Topi99** [Solify-IT/docs#69]
## Objetivos

  * Conocer la madurez del departamento.

## Involucrados
  * Miembros del departamento.
  * Evaluadores.
  * Program Manager.

## Entradas
  * Necesidad de evaluación.
  * Línea base de productos de trabajo del departamento.

## Etapas y descripciones
<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Práctica del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan=2>Solicitud</td>
      <td>Comunícate con el evaluador o la evaluadora para agendar fecha y hora de entrega.</td>
      <td rowspan=4>Program Manager</td>
      <td rowspan=7>OPF 1.2</td>
    </tr>
    <tr>
      <td>Comunica al departamento la fecha y hora de entrega de evidencia.</td>
    </tr>
    <tr>
      <td rowspan=3>Preparación</td>
      <td>Forma equipos que serán encargados de reunir las las evidencias de cada área de proceso.</td>
    </tr>
    <tr>
    <td>Realiza una copia de las <a href="https://docs.google.com/spreadsheets/d/1VeQ-4VDZKUfrcKXS09EYEAmBFbDaSttBZ_FQwrTXxJI/edit?usp=sharing">Checklists de SCAMPI</a>.</td>
    </tr>
    <tr>
      <td>Realiza una copia de la hoja <a href="https://docs.google.com/spreadsheets/d/1VeQ-4VDZKUfrcKXS09EYEAmBFbDaSttBZ_FQwrTXxJI/edit?usp=sharing">Plantilla areas de proceso</a> por cada área a evaluar.</td>
      <td>Equipo encargado del área de proceso</td>
    </tr>
    <tr>
      <td rowspan=2>Recolección de evidencias</td>
      <td>En la checklist actual para el SCAMPI, identifica el entregable para la evaluación.</td>
      <td rowspan=2>Miembros del departamento</td>
    </tr>
    <tr>
      <td>Sigue la checklist para saber qué llenar. Principalmente hay que obtener evidencia de definición y ejecución de cada práctica específica de las áreas a evaluar. Llena las columans correspondientes del entregable.</td>
    </tr>
    <tr>
      <td rowspan=3>Verificación de áreas de proceso</td>
      <td>Realiza la revisión de acuerdo a la checklist del área de proceso que tienes asignada. Si cumple, llena la casilla de "¿Cumple?".</td>
      <td rowspan=2>Equipo encargado del área de proceso</td>
      <td rowspan=3>OPF 1.2, VER, PPQA</td>
    </tr>
    <tr>
      <td>Comunica al PM sobre la finalización de la verificación.</td>
    </tr>
    <tr>
      <td>Una vez todas las áreas han sido verificadas de acuerdo a la checklist, como PM debes revisar que todo esté correcto con una nueva verificación. En caso de existir defectos, comunícalo al equipo encargado del área para que sea arreglado a la brevedad.</td>
      <td rowspan=5>Program Manager</td>
    </tr>
    <tr>
      <td rowspan=2>Entrega</td>
      <td>Envía el enlace al entregable al evaluador o la evaluadora para iniciar la evaluación.</td>
      <td rowspan=4>OPF 1.2</td>
    </tr>
    <tr>
      <td>El evaluador o la evaluadora indicará la fecha de sesión de retroalimentación. Agéndala en el calendario del departamento. Comunica la fecha y hora.</td>
    </tr>
    <tr>
      <td>Retoalimentación</td>
      <td>Asistir a la sesión de retroalimentación y anotar las observaciones en el mismo archivo que se entregó a los evaluadores.</td>
    </tr>
    <tr>
      <td>Corrección</td>
      <td>De las observaciones obtenidas, añade tareas al plan <a href="https://docs.google.com/spreadsheets/d/1BTbGB1RKFBkkToQ1RRVmxgYjYspxON3u4X9_Voejf3c/edit?usp=sharing">del departamento</a> para tomar acciones correctivas. Para mas detalles, consulta el <a href="https://github.com/Solify-IT/docs/wiki/P27-Convertir-retroalimentaci%C3%B3n-a-tareas-del-plan">Proceso para Convertir retroalimentación a tareas del plan</a></td>
    </tr>
  </tbody>
</table>

## Salidas
  * Retroalimentación de los evaluadores.

## Cambios

- 02/06/2021 - Se define el proceso.

**Comment by albertcastaned** [comment]
Lo veo bien.  A lo mejor solo quitaria que el evaluador no sea específicamente Eduardo pensando como a futuro

**Comment by scarlosro** [comment]
Se ve bien :)

**Comment by Topi99** [comment]
Perdón por la respuesta tardada, no había visto los comentarios. Voy a generalizar a los evaluadores.
