### ISSUE TITLE
P15: Programar en parejas

### ISSUE THREAD

**Issue by scarlosro** [Solify-IT/docs#70]
## Objetivos

  * Facilitar la transmisión de habilidades, conocimientos y técnicas.
  * Mejorar la calidad del código.

## Involucrados
  * Team Members

## Entradas

  * User Story a desarrollar

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Práctica del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
     <td rowspan=2> Análisis </td>
     <td> Platicar en pareja sobre la posible solución a la US </td>
     <td> Team Members </td>
     <td> PP 2.5, TS 1.1 </td>
    </tr>
    <tr>
     <td> Definir el algoritmo y validar que la solución sea correcta </td>
     <td> Team Members </td>
     <td> TS 1.1 </td>
    </tr>
    <tr>
     <td rowspan=4> Ejecución </td>
     <td> Un miembro del equipo comienza con la programación, el otro dicta lo que se espera del código </td>
     <td> Team Member</td>
     <td> TS 3.1 </td>
    </tr>
     <tr>
     <td> La misma persona narra lo que va realizando  </td>
     <td> Team Member</td>
     <td> TS 3.1  </td>
    </tr>
    <tr>
     <td> La otra persona observa el código y comenta sobre los defectos identificados </td>
     <td> Team Member</td>
     <td> PPQA 1.2, TS 3.1, VER 2.1 </td>
    </tr>
  <tr>
     <td> Se registra en la bitácora de defectos, la descripción del defecto </td>
     <td> Team Member</td>
     <td> PPQA 2.2, VER 2.1, VAL 2.1  </td>
    </tr>
    <tr>
     <td> Rotación </td>
     <td> Se intercambian los papeles, ahora uno programa y el otro observa </td>
     <td> Team Member</td>
     <td> PP 2.5, TS 3.1 </td>
    </tr>

  </tbody>
</table>

## Salidas

  * Funcionalidad completa de la User Story (Código)
  * Pruebas
  * Defect log actualizado 

## Cambios
- fecha de creación en 07/04/2021 - Se define el proceso.
- fecha de creación en 07/04/2021 - Modificación de proceso
- fecha de creación en 07/04/2021 - Modificación de proceso.
- fecha de creación en 07/04/2021 - Modificación de proceso.
- fecha de creación en 07/04/2021 - Modificación de proceso.

## Referencias
* [Técnica de Pomodoro](https://github.com/Solify-IT/psyche-ing/wiki/Guia-para-el-manejo-del-tiempo-de-desarrollo)
* [Defect log de Soolers](https://docs.google.com/spreadsheets/d/1MVEE5b19y5CxzQJxFSf31RyKIn8mhyHfYt4_y15_M5A/edit#gid=1880816928)
* [Defect log de Rocket](https://docs.google.com/spreadsheets/d/1x022IPg3fytUQ_NxFjkgHFoTU2oBt1hXvNUFo9ZFTHs/edit#gid=848731056)

**Comment by scarlosro** [comment]
Se añade lo que faltaba el defect los =)

**Comment by albertcastaned** [comment]
Arreglar defectos de markdown. Creo que seria bueno integrar los cambios del proceso de #61

**Comment by albertcastaned** [comment]
Fuera de eso lo veo bien.

**Comment by A01702321** [comment]
Si, agregar en que la persona revisa el codigo y busca defectos utilizando la checklist de revisión. También opino que lso defectos encontrados en esta etapa no debe ser registrados en el defect log porque justamente no se están inyectando. Es decir estan arreglando el defecto antes de ser guardado en el repositorio.

**Comment by scarlosro** [comment]
> Si, agregar en que la persona revisa el codigo y busca defectos utilizando la checklist de revisión. También opino que lso defectos encontrados en esta etapa no debe ser registrados en el defect log porque justamente no se están inyectando. Es decir estan arreglando el defecto antes de ser guardado en el repositorio.

Entonces solo haré el cambio directo de lo que agrego. Y referente a que en teoría si debes documentarlo puesto que si estas corrigiendo es porque lo detectaste y en cierto punto es buena práctica encontrar el error en la misma fase donde lo inyectaste. Estamos hablando que estas mejorando en cálidad.
