### ISSUE TITLE
P16 Definir Objetivos de Proyecto

### ISSUE THREAD

**Issue by A01702321** [Solify-IT/docs#71]
## Objetivos

  * Definir los objetivos del proyecto

## Involucrados
  * Team Leader
  * Project Owner
  * Architecture Owner
  * Team Members
  * Stakeholders

 
## Entradas

  * Necesidades a satisfacer

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Práctica del CMMI</th>
    </tr>
  </thead>
  <tbody>
  <tr>
  <td> Acercamiento </td>
  <td> Comprender las necesidades del proyecto </td>
  <td> Equipo </td>
  <td> PP 2.1</td>
  </tr>
  <tr>
  <td rowspan=2> Identificación </td>
  <td> Identificar restricciones en el calendario  </td>
   <td> Team Leader</td>
  <td> PP 2.1 </td>
  </tr>
  <tr>
  <td>  Definir los objetivos SMART del proyecto </td>
  <td> Equipo</td>
  <td> PP 3.3 </td>
  </tr>
  <tr>
  <td> Documentación</td>
  <td> Registrar los objetivos en el documento de estrategia inicial del proyecto. </td>
   <td> Team Leader & Project Owner</td>
  <td> PP 2.7 </td>
  </tr>
  </tbody>
</table>

## Salidas

  * Objetivos del proyecto

## Cambios
- 03/06/2021 - Modificación de proceso.

**Comment by A01702321** [comment]
Agregamos la parte de Documentación y pequeños cambios en los encargados

**Comment by albertcastaned** [comment]
Lo veo bien
