### ISSUE TITLE
PIP P17 MERGE CON P14 Monitorear Riesgos

### ISSUE THREAD

**Issue by scarlosro** [Solify-IT/docs#72]
## Objetivos

  1. Generar la matriz inicial de riesgos de un proyecto.
  2. Conocer el sistema de evaluación y los puntos importantes para la gestión de riesgos.
  3. Asegurar la obtención, análisis, almacenamiento y comunicación de métricas de los proyectos (incluyendo al departamento). 

## Involucrados
  1. Miembros del equipo

## Entradas

  1. Proyecto

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Practica del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan=2>Conociendo la Guía de Monitoreo de Riesgo.</td>
      <td>Lee la guía de gestión de riesgos para poder conocer la clasificación, evaluación y plan de seguimiento.</td>
      <td>Team Member</td>
      <td> DAR 1.1 DAR 1.2 DAR 1.3 RSKM 1.1 RSKM 1.2</td>
    </tr>
    <tr>
      <td>Conoce la Matriz plantilla de Riesgo con el fin de familiarizarse y conocer los campos a llenar y su significado. </td>
      <td>Team Member</td>
      <td> DAR 1.1 RSKM 1.3 </td>
    </tr>
    <tr>
      <td rowspan=4>Planteo y análisis de riesgos.</td>
      <td>Elijan persona encargada a documentar.</td>
      <td>Team Member</td>
      <td> RSKM 1.3 </td>
    </tr>
    <tr>
      <td>Dialoga sobre los riesgos presentes en el proyecto.</td>
      <td>Team Member</td>
      <td>RSKM 2.1, PMC 1.3</td>
    </tr>
     <tr>
      <td>Documenta el riesgo y evalúa la probabilidad e impacto de acuerdo con la guía.</td>
      <td>Encargado</td>
      <td>PP 2.2 RSKM 2.2 PMC 1.3 </td>
    </tr>
    <tr>
      <td>Documenta el plan de mitigación y contingencia para los riesgos detectados y responsables para el seguimiento a la mitigación de ellos .</td>
      <td>Encargado</td>
      <td>RSKM 3.1 RSKM 3.2 PMC 2.1</td>
    </tr>
<tr>
      <td> Seguimiento</td>
      <td>Acuerden fecha de monitoreo una vez a la semana. </td>
      <td>Team Member</td>
      <td> DAR 1.1 DAR 1.2 DAR 1.3 RSKM 1.1 RSKM 1.2</td>
    </tr>
<tr>
      <td rowspan=4>Seguimiento de riesgos</td>
      <td>Da a conocer los riesgos que han sucedido, su estado actual y resultados.</td>
      <td>Team Member</td>
      <td>MA 2.4 PMC 1.3</td>
    </tr>
    <tr>
      <td>Identifica los riesgos nuevos y eliminados en la reunión de monitoreo.</td>
      <td>Team Member</td>
      <td> PMC 1.3 PMC 1.7 PMC 2.2 RSKM 2.2 RSKM 3.1 RSKM 3.2</td>
    </tr>
    <tr>
      <td>Revaluación de los riesgos restantes y verifica su magnitud y probabilidad, así como su seguimiento.</td>
      <td>Miembro</td>
      <td>PMC 1.7 PMC 2.2 RSKM 2.2 </td>
    </tr>
    <tr>
      <td>Actualiza y registra los datos y métricas de acuerdo con la información obtenida en la discusión y elaborar el resumen del status global de acuerdo con los datos previos y actuales.</td>
      <td>Encargado</td>
      <td>MA 2.1MA 2.2MA 2.3MA 2.4, PMC 1.4</td>
    </tr>
  </tbody>
</table>

## Salidas

  1. Matriz de Riesgos y planes de mitigación y contingencia.

## Referencias
* [Guía de plan de gestión de riesgos](https://github.com/Solify-IT/docs/wiki/Plan-de-Gesti%C3%B3n-de-Riesgos)
* [Plantilla de Matriz](https://docs.google.com/spreadsheets/d/1r24sFOnDGjIt0TvR-WsYcckXOIqTnW4pbiQfAV7dN-0/edit#gid=0)

## Cambios
- 06/05/2021 - Se define el proceso.
- 06/06/2021 - Se modifica el proceso.

**Comment by scarlosro** [comment]
Se unifican los procesos para su mejor seguimiento.

**Comment by Topi99** [comment]
Me gusta, LGTM 👍
