### ISSUE TITLE
G## Integración contínua de manera correcta

### ISSUE THREAD

**Issue by Topi99** [Solify-IT/docs#73]
## Tabla de contenidos

  * [Objetivos](#objetivos)
  * [¿Qué es integración continua?](#qué-es-integración-continua)
    + [Definición](#definición)
    + [¿Qué **NO** es CI?](#qué-no-es-ci)
  * [Estrategias para implementar CI](#estrategias-para-implementar-ci)
    * [Feature Toggles](#feature-toggles)
    * [Dark Releases](#dark-releases)
  * [Herramientas](#herramientas)
  * [Puntos importantes](#puntos-importantes)
    + [Inspecciones estáticas de código](#inspecciones-estáticas-de-código)
    + [Inspecciones dinámicas](#inspecciones-dinámicas)
    + [Pruebas de sistema](#pruebas-de-sistema)
    + [Builds](#builds)
  * [Recursos extras](#recursos-extras)

## Objetivos

* Guiar a los ingenieros de Solify a integrar sus productos de trabajo con la línea base (main, master, trunk, etc.) de la manera correcta.

### Definición

Una de las definiciones más completas es [la de Atlassian](https://www.atlassian.com/continuous-delivery/continuous-integration#:~:text=Continuous%20integration%20(CI)%20is%20the,builds%20and%20tests%20then%20run.):

> Integración Continua (CI) es la práctica de automatizar la **integración** de cambios al código de múltiples contribuidores en un solo proyecto de software.

Podemos complementar con que CI es una de las buenas prácticas de [DevOps](https://www.atlassian.com/devops), ya que permite a los desarrolladores mezclar sus cambios a un repositorio central en donde las construcciones (builds) y pruebas (tests) son ejecutadas.

### ¿Qué **NO** es CI?

Existen muchos modelos de ramas para los sistemas de versiones (ejemplo: Git) que recomiendan la implementación de [_Feature Branches_](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) o _Ramas de Características_ en las que se implementan _features_ o _características_ completas del sistema. En este modelo, el tiempo de vida de una rama (código separado de la "realidad") va desde un par de días hasta semanas o meses. Este extenso tiempo de vida impide que se integren los cambios a la base de código (code base) de manera continua. Por lo tanto, Feature Branches **no son** Integración Continua.

## Estrategias para implementar CI

Para verdaderamente realizar entrega continua, las ramas en nuestros repositorios deben tener una vida de máximo un día, y realizar merges (integraciones a la línea base, main, master, trunk, etc.) periódicamente. Una de las preocupaciones mas usuales con la verdadera integración continua es tener características y funcionalidades incompletas en el producto en producción, pero esto puede ser resuelto de muchas maneras.

### Feature Toggles

Una de estas soluciones (además de las mas sencillas) es implementar el uso de [_Feature Toggles_](https://martinfowler.com/articles/feature-toggles.html) o _Feature Flags_. Si hacemos integración de una funcionalidad parcial, podemos ocultarla de manera muy sencilla con una simple condición, y así se evita el mal funcionamiento al usuario final de nuestros sistemas. 

### Dark Releases

Otra manera de implementar CI es con los llamados [Dark Releases](https://www.split.io/glossary/dark-launch/) o Entregas Oscuras. Muy parecido a las Feature Toggles, las entregas oscuras ocultan la nueva funcionalidad (porque está incompleta o no está lista para ser usada) a los usuarios finales, con el propósito de tener una integración continua con ramas de muy corta vida. Esto puede ser logrado con componentes de la interfaz de usuario construidos de manera que ningún usuario final pueda encontrar o acceder a ellos. 

## Herramientas

Cuando implementamos Integración Continua (CI) pueden surgir problemas relacionados al tiempo invertido en probar que los nuevos cambios de cada integrante del equipo funcionen con la línea base del código. Por estos problemas de tiempo, es recomendado construir un CI Pipeline. Estos pipelines o "tuberías" de integración continua automatizan las pruebas ejecutadas para comprobar que los nuevos cambios funcionan con la base de código mas reciente. A la hora de implementar CI Pipelines contamos con decenas de opciones diferentes, pero de funcionamiento muy similar. A continuación, enlistamos unas de las herramientas más usadas:

* [CircleCI](https://circleci.com/): Cuenta con el soporte de diversos VCS (Version Control Systems) como Github y Bitbucket. Permite realizar pruebas automatizadas, mandar notificaciones y automatizar despliegues. Cuenta con una versión gratuita y de paga con muchas características mas. No necesitas un servidor propio para usar CircleCI. 

* [Github Actions](https://docs.github.com/en/actions): Una de las herramientas más recientes en la industria, cuenta con miles de extensiones y acciones pre programadas para facilitar la vida de los ingenieros que quieren integrar su trabajo. Permite automatizar, personalizar y ejecutar flujos de trabajo en tu mismo repositorio de Github.

* [Jenkins](https://www.jenkins.io/): Escrito en Java, Jenkins es un programa listo para instalarse en un servidor propio con una configuración muy sencilla que permite realizar tareas automatizadas como: pruebas funcionales, pruebas de sistema, empaquetamientos y entregas contínuas. Jenkins es "open source" y puedes descargar su código fuente para hacer "builds" personalizadas.

## Puntos importantes

Tener una buena herramienta para realizar nuestra integración continua no es suficiente, necesitamos tener tareas específicas en nuestro CI Pipeline que nos aseguren que los nuevos cambios se integrarán de manera correcta con la línea base de nuestro proyecto. Por eso, recomendamos los siguientes tipos de tarea que creemos siempre deben añadirse a nuestros flujos de verificación de integración:

### Inspecciones estáticas de código

Las inspecciones estáticas del código son un tipo de tareas que no deben faltar en cualquier CI Pipeline. Una inspección estática se encarga de encontrar errores comunes tanto de estándares como defectos. Algunas herramientas que recomendamos son:

  * Lints: son programas que se encargan de analizar y encontrar problemas con el código de manera automática. También permiten arreglar algunos problemas de manera automática.
  * Typechecks: programas encargados de encontrar problemas e inconsistencias entre los diferentes tipos de variables, constantes y objetos de tu base de código. 

### Inspecciones dinámicas

Además de inspecciones estáticas, queremos tener revisiones dinámicas que encuentren problemas con el código corriendo y detecten defectos lo más temprano posible. Algunos tipos de inspecciones dinámicas son:

  * Pruebas unitarias: son tipo de inspección dinámica que prueban una unidad o parte muy pequeña de los sistemas de manera independiente y con entornos y escenarios controlados. 

  * Pruebas de integración: muy parecidas a las unitarias, las inspecciones de integración nos ayudan a decidir si nuestros nuevos cambios funcionan a la perfección con otras partes de la base de código. Por lo general prueban la integración de varias unidades del sistema y cómo interactúan entre ellas. 

### Pruebas de sistema

Estas son muy parecidas a las inspecciones dinámicas, la diferencia es que no prueban el funcionamiento como tal del proyecto, sino sus capacidades de funcionamiento.

### Builds

Este tipo de actividades se encargan de correr "builds" o "construcciones" de cada aplicación de tu proyecto. Para esta parte, se recomienda el uso de scripts de construcción e instalación para automatizar los procesos. Si se usa un sistema de contenedores (como Docker), las builds se facilitan demasiado, al tener un sistema de ayuda para construir y probar las construcciones de las aplicaciones en un entorno lo más parecido al de producción.

## Recursos extras

[Video - Continuous Integration vs Feature Branch Workflow • Dave Farley • GOTO 2021](https://www.youtube.com/watch?v=pXovk-5J0Lg)

**Comment by albertcastaned** [comment]
👍

**Comment by ricardo-esc** [comment]
👏🏻 Muy completa!

**Comment by domerent97** [comment]
¡Excelente!
