### ISSUE TITLE
PIP: Correcciones de P27 Y P30, eliminación de P21

### ISSUE THREAD

**Issue by domerent97** [Solify-IT/docs#74]
# P27 Convertir retroalimentación a tareas del plan

## Objetivos

  * Reconocer tareas para atender retroalimentación de stakeholders.

## Involucrados

  * Miembros del equipo.

## Entradas

  * Retroalimentación de reporte de estado.
  * Retroalimentación de SCAMPI.
  * Retroalimentación de presentación de avance.
  * Retroalimentación del socio formador.
  * Defectos de productos de trabajo.

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Práctica del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan=2>Recolección</td>
      <td>Recolecta la retroalimentación a ser analizada de acuerdo a la <a href="https://github.com/Solify-IT/docs/wiki/G25-Atender-retroalimentaci%C3%B3n">Guía para atender retroalimentación</a>.</td>
      <td rowspan=4>Team Leader o Program Manager</td>
      <td rowspan=2>PMC2.1</td>
    </tr>
    <tr>
      <td>Basandote en la <a href="https://github.com/Solify-IT/docs/wiki/G25-Atender-retroalimentaci%C3%B3n">Guía para atender retroalimentación</a>, determina si los elementos son elegibles para una acción correctiva.</td>
    </tr>
    <tr>
      <td rowspan=2>Corrección</td>
      <td>De acuerdo a la <a href="https://github.com/Solify-IT/docs/wiki/G25-Atender-retroalimentaci%C3%B3n">Guía para atender retroalimentación</a>, determina y documenta las acciones a realizar en los elementos identificados.</td>
      <td rowspan=2>PMC2.2</td>
    </tr>
    <tr>
      <td>Habla con el equipo y los stakeholders involucrados sobre si las acciones identificadas son las correctas para llevar a cabo las correcciones.</td>
    </tr>
    <tr>
    <td rowspan="2">Documentación</td>
    <td>Documentar los cambios de la línea base de requisitos en la Bitácora de Cambios de la Matriz de Trazabilidad, con base en el Checklist para Documentación de Cambios de Requisitos.</td>
    <td>PO</td>
    <td>REQM 1,3 1.5, CM 2.2</td>
  </tr>
  <tr>
    <td>Modificar la matriz de trazabilidad utilizando la información de los nuevos requisitos y/o los requisitos modificados.</td>
    <td>PO</td>
    <td>REQM 1.4</td>
  </tr>
  </tbody>
</table>

## Salidas

  * Lista de tareas a ser atendidas en el plan.

## Enlaces

  * [Guía para atender retroalimentación](https://github.com/Solify-IT/docs/wiki/G25-Atender-retroalimentaci%C3%B3n)

## Cambios
- 07/06/2021 - Agregar documentación
- 07/06/2021 - Actualizar los links de la guía.
- 20/05/2021 - Se define el proceso.

# P30 Identificar necesidades del cliente
## Objetivos

  * Conocer a nuestros clientes y su forma de trabajo para poder analizar la información e identificar las necesidades.

## Involucrados
  * Clientes
  * Equipo de desarrollo

## Entradas

  * Proyecto o lista de tareas a ser atendida por el plan.

## Etapas y descripciones

<table>
  <thead>
    <tr>
      <th>Etapa</th>
      <th>Actividad</th>
      <th>Encargado</th>
      <th>Práctica del CMMI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan=3>Planificación</td>
      <td>Agenda reunión con clientes para identificación de necesidades. Agenda de acuerdo con  la Guía de Calendario.</td>
      <td>PO</td>
      <td> PP 3.3, PMC 1.5</td>
    </tr>
    <tr>
      <td>Investiga previo a la junto acerca de los clientes para tener una base de conocimiento y realiza una tormenta de idea para rescatar ideas principales y proponer preguntas. Los criterios serán ubicar aquellas actividades o procesos que les cuesta y genera afectación para el desarrollo de otras actividades. </td>
      <td>Cada uno</td>
      <td>PMC 1.5, PP 2.5</td>
    </tr>
    <tr>
        <td>Realiza la agenda de la junta</td>
        <td>PO, TL, AO</td>
        <td> PP 2.6</td>
      </tr>
    <tr>
      <td rowspan=3>Junta</td>
      <td>Presenta la agenda de la reunión así como especifica el propósito. </td>
      <td> TL </td>
      <td> PP 2.6 </td>
    </tr>
    <tr>
      <td>Escucha la forma de trabajo del cliente e identifica las necesidades o ideas importantes y pregunta dudas al final.</td>
      <td>Team member</td>
      <td>RD 1.1, PP 3.3/td>
    </tr>
    <tr>
      <td>Documenta en la minuta del día</td>
      <td>Team member</td>
      <td>RD 1.1, CM1 1.3</td>
    </tr>
    <tr>
      <td rowspan=3>Análisis</td>
      <td>Lee la minuta completa y comenta en la reunión de análisis</td>
      <td> Team member </td>
      <td> RD 1.1</td>
    </tr>
    <tr>
      <td>Realiza una tormenta de ideas sobre las necesidades y dialoga sobre ellas</td>
      <td>Team member</td>
      <td>RD 1.1, REQM 1.5</td>
    </tr>
    <tr>
      <td>Documenta las necesidades en estrategia inicial</td>
      <td>PO</td>
      <td>RD 1.1, </td>
   </tr>

  </tbody>
</table>

## Salidas

  * Lista de necesidades del stakeholder

## Enlaces
  * [Guía de Calendario](https://github.com/Solify-IT/docs/wiki/G1-Uso-de-Calendario-de-Solify)

## Cambios

- fecha de creación en 25/05/2021 - Se define el proceso.

**Comment by A01702321** [comment]
Me parece bien :+1:

**Comment by Topi99** [comment]
LGTM :+1:

**Comment by LaloGlzMlz** [comment]
Cul 👍
