### ISSUE TITLE
G27 Guía para identificar inconsistencias

### ISSUE THREAD

**Issue by BurksonB** [Solify-IT/docs#75]
## ¿Qué es una inconsistencia?

Es una discrepancia, o falta de coherencia entre los elementos del proyecto. Esto incluye los requisitos, procesos, guías, etc.

<b>Ejemplos: </b>
* Productos de trabajo y objetivos de proyecto desalineados.
* Problemáticas entre los productos de requisitos nuevos con existentes.
* Diferencia entre la ejecución y documentación de procesos.
* Información contradictoria en documentos de proyecto.

## Tipos de inconsistencias

<b>1. Comisión: Suceden cuando no se gestionan adecuadamente los cambios en los productos de trabajo.</b>
* Enlaces disfuncionales después de un cambio en un producto de trabajo
* Definición incompleta en productos de trabajo.
* No atender correcciones de cualquier producto de trabajo.
* Mala administración de productos de trabajo (IDs, repetidos, mal almacenados en documentos)

<b>2. Omisión: Suceden cuando no se toman en consideración actividades o productos de trabajo en la etapa de planeación.</b>
* Requisitos faltantes e la etapa de planeación.
* No considerar dependencias de requisitos o procesos
* Productos de trabajo muy grandes que pueden descomponerse en actividades más pequeñas
* No actualizar documentos relevantes con cambios de productos o actividades.

## ¿Cómo se corrigen?

Documentar la inconsistencia de manera acorde donde fue identificada. Por ejemplo; si se identifica en un proceso documentarla en un "issue" de la wiki y avisar al departamento para ser atendido por todos los integrantes y ser resuelto lo antes posible.

**Comment by domerent97** [comment]
Lo veo bien :)

**Comment by Topi99** [comment]
LGTM 💯
